### ISSUE TITLE
Report: Unable to launch containers with exposed ports on RHEL 7.0 + docker 1.6.0-rc2 + selinux

### ISSUE THREAD

**Issue by mbentley** [docker/docker#11868]
Description of problem:  On RHEL 7.0 + docker 1.6.0-rc2 and selinux enabled on the host, I am unable to launch containers with exposed ports.

`docker version`:
Client version: 1.6.0-rc2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): c5ee149
OS/Arch (client): linux/amd64
Server version: 1.6.0-rc2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): c5ee149
OS/Arch (server): linux/amd64

`docker info`:
Containers: 9
Images: 39
Storage Driver: devicemapper
 Pool Name: docker-202:2-16819213-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop2
 Metadata file: /dev/loop3
 Data Space Used: 1.08 GB
 Data Space Total: 107.4 GB
 Data Space Available: 1.873 GB
 Metadata Space Used: 2.449 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 1.873 GB
 Udev Sync Supported: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.10.0-123.20.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.0 (Maipo)
CPUs: 1
Total Memory: 3.519 GiB
Name: ip-172-31-28-201.ec2.internal
ID: ZMHP:4MA3:4XUV:V6DK:BBCA:7PCG:ZA4N:QIBW:6XGM:H2VY:CK6R:VHEZ
Debug mode (server): false
Debug mode (client): true
Fds: 13
Goroutines: 19
System Time: Fri Mar 27 13:37:20 EDT 2015
EventsListeners: 0
Init SHA1: 2858afa354fa56af645c92db74ac85060961662c
Init Path: /usr/bin/docker
Docker Root Dir: /var/lib/docker
Username: mbentley
Registry: [https://index.docker.io/v1/]

`uname -a`:
Linux ip-172-31-28-201.ec2.internal 3.10.0-123.20.1.el7.x86_64 #1 SMP Wed Jan 21 09:45:55 EST 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
RHEL 7.0 in AWS [RHEL-7.0_HVM_GA-20150209-x86_64-1-Hourly2-GP2 (ami-60a1e808)]
Docker Engine 1.6.0-rc2 [Docker version 1.6.0-rc2, build c5ee149]

How reproducible:

Steps to Reproduce:

1. Create AWS RHEL 7.0 instance
2. Install Docker via the AWS extras repo:

    ```
    yum install -y yum-utils wget &&\
    yum-config-manager --enable rhui-REGION-rhel-server-extras &&\
    yum install -y docker &&\
    systemctl enable docker
    ```

3. Download the docker engine 1.6.0-rc2:
    ```
    mv /usr/bin/docker /usr/bin/docker.bak; wget -O /usr/bin/docker "https://test.docker.com/builds/Linux/x86_64/docker-1.6.0-rc2" && chmod +x /usr/bin/docker
    ```

4. Comment out `ADD_REGISTRY='--add-registry registry.access.redhat.com'` in `/etc/sysconfig/docker`
5. Start Docker: `systemctl start docker`
6. Make sure docker is running: `docker version`
7. Attempt to run nginx:

    ```
    docker run -it --rm nginx:latest
    FATA[0000] Error response from daemon: Cannot start container 045a09969867331a534a486047efd81918bf51c52f60cc8f48ffa91b6900752d: [8] System error: Cannot set property DefaultDependencies, or unknown property.
    ```
Disabling selinux or setting to `permissive` allows it to work.

Actual Results:  the container fails to start

Expected Results: containers starts

Additional info:

**Comment by jfrazelle** [comment]
@vbatts wont using the static binary here not work, I realize it is not a devmapper issue but still

**Comment by jfrazelle** [comment]
also ping @rhatdan

**Comment by LK4D4** [comment]
also docker/libcontainer#477

**Comment by rhatdan** [comment]
Does restorecon -v /usr/bin/docker /usr/libexec/docker make it work?

**Comment by mbentley** [comment]
@rhatdan - yes, that makes it work.

Another error, likely not related to docker in specific (I'm guessing selinux), when I run `docker run -p 80:80 nginx:latest`, I'm getting:
```
time="2015-03-27T16:04:38-04:00" level=warning msg="port allocator - using fallback port range 49153-65535 due to error: open /proc/sys/net/ipv4/ip_local_port_range: no such file or directory"
```

but the container starts as expected and I can hit nginx fine.

**Comment by rhatdan** [comment]
Why isn't that file available?

**Comment by mbentley** [comment]
I'm not sure:
```
# ls -l /proc/sys/net/ipv4/ip_local_port_range
-rw-r--r--. 1 root root 0 Mar 27 16:00 /proc/sys/net/ipv4/ip_local_port_range
# ls -Z /proc/sys/net/ipv4/ip_local_port_range
-rw-r--r--. root root system_u:object_r:sysctl_net_t:s0 /proc/sys/net/ipv4/ip_local_port_range
```

**Comment by jfrazelle** [comment]
@rhatdan have you seen any probs with 1.6.0-rc2 on rhel

**Comment by rhatdan** [comment]
Not too many people running it there yet.  I wonder if this is an issue with the code being run before the /proc is mounted?

**Comment by mbentley** [comment]
Here is the daemon debug output when running the following command:  `docker run -P nginx:latest`

```
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="Calling POST /containers/create"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=info msg="POST /v1.18/containers/create"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=info msg="+job create()"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="[deviceset] AddDevice(hash=1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init basehash=db26ae25be158311860ad31f41105e78f4c492df255c2621af4087d4d91434b9)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm info docker-202:2-25166953-db26ae25be158311860ad31f41105e78f4c492df255c2621af4087d4d91434b9  OF   [16384] (*1)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm message docker-202:2-25166953-pool  OF  create_snap 91 14 [16384] (*1)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="registerDevice(91, 1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm message docker-202:2-25166953-pool  OF  set_transaction_id 118 119 [16384] (*1)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="[deviceset] AddDevice(hash=1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init basehash=db26ae25be158311860ad31f41105e78f4c492df255c2621af4087d4d91434b9) END"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="activateDeviceIfNeeded(1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm info docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init  OF   [16384] (*1)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm create docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init  OF   [16384] (*1)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): libdm-common.c:1348 (4) docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init: Stacking NODE_ADD (253,1) 0:0 0600 [verify_udev]"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm reload docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init  OF   [16384] (*1)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm resume docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init  OF   [16384] (*1)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): libdm-common.c:1348 (4) docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init: Processing NODE_ADD (253,1) 0:0 0600 [verify_udev]"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): libdm-common.c:983 (4) Created /dev/mapper/docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="[deviceset] AddDevice(hash=1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3 basehash=1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm info docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init  OF   [16384] (*1)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm suspend docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init  OF   [16384] (*1)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm message docker-202:2-25166953-pool  OF  create_snap 92 91 [16384] (*1)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm resume docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init  OF   [16384] (*1)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): libdm-common.c:1348 (4) docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init: Stacking NODE_ADD (253,1) 0:0 0600 [verify_udev]"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): libdm-common.c:1348 (4) docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init: Processing NODE_ADD (253,1) 0:0 0600 [verify_udev]"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="registerDevice(92, 1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm message docker-202:2-25166953-pool  OF  set_transaction_id 119 120 [16384] (*1)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="[deviceset] AddDevice(hash=1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3 basehash=1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init) END"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="[devmapper] UnmountDevice(hash=1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="[devmapper] Unmount(/var/lib/docker/devicemapper/mnt/1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="[devmapper] Unmount done"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="[devmapper] deactivateDevice(1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm info docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init  OF   [16384] (*1)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="Waiting for unmount of 1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init: opencount=0"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm info docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init  OF   [16384] (*1)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="[devmapper] RemoveDevice START(docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm remove docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init  OF   [16384] (*1)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): libdm-common.c:1351 (4) docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init: Stacking NODE_DEL [verify_udev]"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): libdm-common.c:1351 (4) docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init: Processing NODE_DEL [verify_udev]"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="[devmapper] RemoveDevice END(docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="[deviceset docker-202:2-25166953] waitRemove(docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm info docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init  OF   [16384] (*1)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="Waiting for removal of docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init: exists=0"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="[deviceset docker-202:2-25166953] waitRemove(docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init) END"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="[devmapper] deactivateDevice END(1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="[devmapper] UnmountDevice(hash=1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3-init) END"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="activateDeviceIfNeeded(1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm info docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3  OF   [16384] (*1)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm create docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3  OF   [16384] (*1)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): libdm-common.c:1348 (4) docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3: Stacking NODE_ADD (253,1) 0:0 0600 [verify_udev]"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm reload docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3  OF   [16384] (*1)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm resume docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3  OF   [16384] (*1)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): libdm-common.c:1348 (4) docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3: Processing NODE_ADD (253,1) 0:0 0600 [verify_udev]"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): libdm-common.c:983 (4) Created /dev/mapper/docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="[devmapper] UnmountDevice(hash=1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="[devmapper] Unmount(/var/lib/docker/devicemapper/mnt/1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="[devmapper] Unmount done"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="[devmapper] deactivateDevice(1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm info docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3  OF   [16384] (*1)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="Waiting for unmount of 1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3: opencount=0"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm info docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3  OF   [16384] (*1)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="[devmapper] RemoveDevice START(docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm remove docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3  OF   [16384] (*1)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): libdm-common.c:1351 (4) docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3: Stacking NODE_DEL [verify_udev]"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): libdm-common.c:1351 (4) docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3: Processing NODE_DEL [verify_udev]"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="[devmapper] RemoveDevice END(docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="[deviceset docker-202:2-25166953] waitRemove(docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm info docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3  OF   [16384] (*1)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="Waiting for removal of docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3: exists=0"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="[deviceset docker-202:2-25166953] waitRemove(docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3) END"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="[devmapper] deactivateDevice END(1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="[devmapper] UnmountDevice(hash=1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3) END"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=info msg="+job log(create, 1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3, nginx:latest)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=info msg="-job log(create, 1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3, nginx:latest) = OK (0)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=info msg="-job create() = OK (0)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="Calling POST /containers/{name:.*}/attach"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=info msg="POST /v1.18/containers/1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3/attach?stderr=1&stdout=1&stream=1"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=info msg="+job container_inspect(1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=info msg="-job container_inspect(1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3) = OK (0)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=info msg="+job attach(1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="attach: stdout: begin"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="attach: stderr: begin"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="Calling POST /containers/{name:.*}/start"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=info msg="POST /v1.18/containers/1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3/start"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=info msg="+job start(1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="activateDeviceIfNeeded(1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm info docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3  OF   [16384] (*1)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm create docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3  OF   [16384] (*1)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): libdm-common.c:1348 (4) docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3: Stacking NODE_ADD (253,1) 0:0 0600 [verify_udev]"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm reload docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3  OF   [16384] (*1)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): ioctl/libdm-iface.c:1750 (4) dm resume docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3  OF   [16384] (*1)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): libdm-common.c:1348 (4) docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3: Processing NODE_ADD (253,1) 0:0 0600 [verify_udev]"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="libdevmapper(6): libdm-common.c:983 (4) Created /dev/mapper/docker-202:2-25166953-1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=info msg="+job allocate_interface(1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=info msg="-job allocate_interface(1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3) = OK (0)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=info msg="+job allocate_port(1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="/usr/sbin/iptables, [--wait -t nat -A DOCKER -p tcp -d 0/0 --dport 32774 ! -i docker0 -j DNAT --to-destination 172.17.0.4:443]"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="/usr/sbin/iptables, [--wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.4 --dport 443 -j ACCEPT]"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="/usr/sbin/iptables, [--wait -t nat -A POSTROUTING -p tcp -s 172.17.0.4 -d 172.17.0.4 --dport 443 -j MASQUERADE]"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=info msg="-job allocate_port(1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3) = OK (0)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=info msg="+job allocate_port(1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="/usr/sbin/iptables, [--wait -t nat -A DOCKER -p tcp -d 0/0 --dport 32775 ! -i docker0 -j DNAT --to-destination 172.17.0.4:80]"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="/usr/sbin/iptables, [--wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.4 --dport 80 -j ACCEPT]"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=debug msg="/usr/sbin/iptables, [--wait -t nat -A POSTROUTING -p tcp -s 172.17.0.4 -d 172.17.0.4 --dport 80 -j MASQUERADE]"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=info msg="-job allocate_port(1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3) = OK (0)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=info msg="+job log(start, 1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3, nginx:latest)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=info msg="-job log(start, 1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3, nginx:latest) = OK (0)"
Mar 28 10:36:18 ip-172-31-17-16.ec2.internal docker[744]: time="2015-03-28T10:36:18-04:00" level=info msg="-job start(1f2ae545cb4fa0df5e72754b62a808cdcdf2e39fca58d5415dc66faa5d58c7b3) = OK (0)"```

Just glancing through, I didn't see anything that necessarily caught my eye but hopefully there is something I am missing.

**Comment by jfrazelle** [comment]
so from what I can tell the file is on the host, but when I run a make shell for dind, with --privileged, it is not _in_ the container

**Comment by jfrazelle** [comment]
and thats true on the package 1.5.0 distributed by red hat as well

**Comment by mbentley** [comment]
So I am doing some testing with selinux set to permissive:
```
# sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   permissive
Mode from config file:          permissive
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      28
```

OK, so I was restarting some containers and one of them froze while restarting.  I tried to kill the container and I got:
```
# docker kill af
Error response from daemon: Cannot kill container af: active container for af006ac229c3b1ce72b814ab72bc739217c9418997e8227639ff51f1cc25f80a does not exist
```

I had to restart the docker daemon.  When I then tried to start the container I was trying to restart, I get the following:
```
# docker start af006ac229c3
Error response from daemon: Cannot start container af006ac229c3: [8] System error: Unit docker-af006ac229c3b1ce72b814ab72bc739217c9418997e8227639ff51f1cc25f80a.scope already exists.
FATA[0000] Error: failed to start one or more containers
```

Having seen this before, I tried to stop ` docker-af006ac229c3b1ce72b814ab72bc739217c9418997e8227639ff51f1cc25f80a.scope`:
```
# systemctl stop docker-af006ac229c3b1ce72b814ab72bc739217c9418997e8227639ff51f1cc25f80a.scope
Failed to issue method call: Unit docker-af006ac229c3b1ce72b814ab72bc739217c9418997e8227639ff51f1cc25f80a.scope is not loaded properly.
```

My host just randomly dropped back to the previous state when a restart of a container froze:
```
Error response from daemon: Cannot start container f04c5a32726b: [8] System error: Cannot set property DefaultDependencies, or unknown property.
FATA[0000] Error: failed to start one or more containers
FATA[0000] You cannot attach to a stopped container, start it first
```

Before, restorecon worked but if selinux is in permissive mode, this shouldn't be a problem, right?

**Comment by jfrazelle** [comment]
@rhatdan if you want access to the machine we were planning on hooking up to jenkins I can add your ssh key

**Comment by mbentley** [comment]
Also just as a FYI, I went ahead and did a dynbinary build of docker using c5ee149.  If this needs to be split into another issue as it seems to be deviating from my original problem, just let me know.

**Comment by jfrazelle** [comment]
also https://github.com/docker/docker/pull/11946 fixed this

**Comment by rhatdan** [comment]
@jfrazelle So is this problem fixed now?

**Comment by mbentley** [comment]
@rhatdan - I am still getting the `time="2015-03-31T10:06:03-04:00" level=warning msg="port allocator - using fallback port range 49153-65535 due to error: open /proc/sys/net/ipv4/ip_local_port_range: no such file or directory"` warning but I am not having the other issues now using a docker binary built from #11635.

**Comment by rhatdan** [comment]
Do you get the error in SELinux permissive mode?  Could this be caused by SELinux?

**Comment by mbentley** [comment]
Yes, I am receiving the warning when in permissive mode:
```
# docker run -P nginx:latest
time="2015-03-31T11:13:38-04:00" level=warning msg="port allocator - using fallback port range 49153-65535 due to error: open /proc/sys/net/ipv4/ip_local_port_range: no such file or directory"
```

```
# sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   permissive
Mode from config file:          permissive
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      28
```

I am running a dynamically build docker binary from the PR for the bump to 1.6.0 (f4f9b8b)
```
# docker --version
Docker version 1.6.0-rc2, build f4f9b8b
# docker info
Containers: 191
Images: 112
Storage Driver: devicemapper
 Pool Name: docker-202:2-25166953-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 3.268 GB
 Data Space Total: 107.4 GB
 Data Space Available: 104.1 GB
 Metadata Space Used: 13.38 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.134 GB
 Udev Sync Supported: true
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Kernel Version: 3.10.0-229.1.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.1 (Maipo)
CPUs: 1
Total Memory: 3.519 GiB
Name: ip-172-31-17-16.ec2.internal
ID: PMZR:OMEI:OETU:3GBL:OQED:UI27:NAKW:ZA2N:BKVS:DU2E:EIGF:PMWI
Username: mbentley
Registry: [https://index.docker.io/v1/]
```

**Comment by miminar** [comment]
@mbentley I can confirm that #11946 fixes 

    open /proc/sys/net/ipv4/ip_local_port_range: no such file or directory

issue on RHEL. Unfortunatelly [f4f9b8b](https://github.com/docker/docker/commit/f4f9b8b68103c133cce941993655be0ada53fac1) lacks that fix. I've just tried dynbinary from [20d4e6f](https://github.com/docker/docker/commit/20d4e6f29ef5c7b8bf2f55aa2bedb0130868cd2c) (docker 1.6.0-rc3) and the warning is gone. Could you please recheck?
