### ISSUE TITLE
Container references should not be ambiguous

### ISSUE THREAD

**Issue by jhftrifork** [docker/docker#12628]
On my docker machine, one container has the ID `db2ea256342e`, and another has the name `db`.

Running a command like `docker exec db ...` on my machine executes the command on the container with ID `db2ea256342e`, not the container with name `db`. This is highly confusing and dangerous.

Two potential fixes here are:

* Avoid potential ambiguity. Container references should explicitly say whether they are a reference to an ID or a name, e.g. `docker exec --name=db ...`.
* Docker command should fail if more than one container matches the reference provided.

I am using:

````
> docker --version
Docker version 1.4.0, build 4595d4f
````

**Comment by phemmer** [comment]
This is a dup of #8069 which has been fixed in 1.6

**Comment by thaJeztah** [comment]
Correct, this should be resolved in the current release (1.6), please test on the current release.


I'm going to close this issue, because it should be resolved, but ping me if you're still able to reproduce this in 1.6

**Comment by jhftrifork** [comment]
Ah, thanks. I should upgrade. Though after reading #8069 I am still not clear what the implemented fix was. I would ideally like to be able to specify in my commands that "this is to be interpreted as a name, not as an ID", or vice versa. Is that possible with 1.6?

**Comment by thaJeztah** [comment]
No, not directly, but previously Docker sometimes picked the wrong container (eg the `db` container if you meant container `db17373828` (ID), which should no longer happen.

If you think I closed wrongly, let me know, then I can re-open.

**Comment by jhftrifork** [comment]
If I understand the 1.6 policy correctly, Docker now checks names first, then IDs; i.e., the precedence has been reversed.

This is not sufficient, because the problem also exists in the inverse: e.g. I write "db" meaning an ID, but instead a container with the name "db" is selected.

IMO there needs to be a way to explicitly say, "this is an ID", or, "this is a name".
