### ISSUE TITLE
Install docker on Debian jessie isn't up-to-date

### ISSUE THREAD

**Issue by jarus** [docker/docker#12861]
Hi,

after the release of Debian jessie the package docker.io doesn't exists in the main or backports repository of jessie anymore.
The docs should provide a valid and official way to install docker on jessie.

My currently workaround is to use the docker repository which is provided for ubuntu.
```bash
apt-get install apt-transport-https
apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
echo "deb https://get.docker.com/ubuntu docker main" > /etc/apt/sources.list
apt-get update
apt-get install lxc-docker
```

**Comment by jfrazelle** [comment]
1. yes our ubuntu repo works on debian, we actually make sure it always does
2. the docs have been updated here on the master branch
http://docs.master.dockerproject.com/installation/debian/
they just need to be released

**Comment by jarus** [comment]
1. great to hear.
2. In master there is still the advice to use backports or is there a open pull request to address this issue?

**Comment by kiranos** [comment]
why was this closed, from what I can see in http://backports.debian.org/changes/jessie-backports.html docker.io is missing so the documentation is invalid?

**Comment by terotil** [comment]
Documentation in https://docs.docker.com/installation/debian/#installation is still invalid.

**Comment by kcalliauw** [comment]
Watch out on this line from the above instructions:

`echo "deb https://get.docker.com/ubuntu docker main" > /etc/apt/sources.list`
should be:
`echo "deb https://get.docker.com/ubuntu docker main" >> /etc/apt/sources.list`

**Comment by markusobsidian** [comment]
On Jessie, the easiest thing to do appears to be to run the installation script:

```
curl -sSL https://get.docker.com/ | sh
```

**Comment by jerryjacobs** [comment]
I think the website needs to be updated to match the script as mentioned by markusobsidian

**Comment by thaJeztah** [comment]
@kcalliauw Thanks. I edited the example, just in case someone tried to execute it

**Comment by benallard** [comment]
Docs is still wrong.

**Comment by kebian** [comment]
Yup, docs are wrong.

**Comment by HuStmpHrrr** [comment]
wheezy is no longer the latest stable release. i think this should be fixed too.

**Comment by sabbane** [comment]
After an unsuccessful try with the official docs, I was able to install docker using the following link: http://blog.programster.org/debian-8-install-docker/.
The official docs has to be updated.

**Comment by bvarner** [comment]
This issue should not be closed. @jarus The official docs still do not work.

**Comment by rebootl** [comment]
Still not there...
Sorry, this is totally confusing.
Please fix the docs next time first. Unless I'm missing something, the docs were wrong now for over a month. At least add a clear note there, that can't be so hard.

**Comment by jfrazelle** [comment]
Last time I checked _anyone_ could open a PR instead on commenting here
whining about it

**Comment by lgs** [comment]
@jfrazelle  ... yes but,
if you google `installing docker on debian` the thirds link you're gonna land on, is here.

then just do what the first 2 links (official Docker docs) suggest: 

`curl -sSL https://get.docker.com/ | sh`

**Comment by kiranos** [comment]
https://packages.debian.org/source/docker.io there is a package in backport currently
