### ISSUE TITLE
Mounting /sys is broken in Docker 1.6.1

### ISSUE THREAD

**Issue by vmarmol** [docker/docker#13097]
Docker 1.6.1 broke the ability to mount `/sys` into a container. This is breaking [cAdvisor](https://github.com/google/cadvisor/) as it uses that for cgroup and network stats.

The fix was already merged to libcontainer: https://github.com/docker/libcontainer/pull/576

Can there be a Docker 1.6.2 with this fix?

/cc @vishh @rjnagal @crosbymichael

**Comment by jfrazelle** [comment]
Fwiw I'm +1 a 1.6.2

**Comment by beeyeas** [comment]
Good finding , it works in Docker 1.6.0. I have to hold on my upgrade.
vmarmol : Why cAdvisor need a /var/run:rw ( read-write ) mount? where rest all are RO?

**Comment by thaJeztah** [comment]
other users are reporting this as well; https://github.com/docker/docker/issues/5582#issuecomment-100241430 so +1 on a 1.6.2

**Comment by vmarmol** [comment]
@beeyeas that is to talk to the Docker daemon through it's socket

**Comment by h0tbird** [comment]
+1

```
[0] ~ >> TERM=xterm ssh core@core01
Last login: Sat May  9 09:38:32 2015 from 192.168.1.11
CoreOS alpha (675.0.0)
core@core01 ~ $ docker --version
Docker version 1.6.1-rc2, build 17f157d-dirty
```

**Comment by sielaq** [comment]
+1
It also hits mesos inside container.
sounds like someone did not predict how much projects depends on binded /sys.

Good consensus would be to allow bind anything, when `--privileged` is set.

**Comment by gregory90** [comment]
@sielaq as far as mesos is concerned it is possible to run it inside container with docker 1.6.1 using --cgroups_hierarchy flag for mesos-slave. That's how I'm running it on CoreOS:
```
docker run --rm --net=host --name slave --privileged -v /usr/lib64/libdevmapper.so.1.02:/usr/lib/libdevmapper.so.1.02 -v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/usr/local/bin/docker -v /sys/fs/cgroup:/host/sys/fs/cgroup mesosphere/mesos-slave:0.22.1-1.0.ubuntu1404 --containerizers=docker,mesos --master=zk://${ZOOKEEPER_IPS}/mesos --cgroups_hierarchy=/host/sys/fs/cgroup
```

**Comment by sielaq** [comment]
@gregory90 thx for the hint!

**Comment by crosbymichael** [comment]
Binaries uploaded for testing found in this comment:

https://github.com/docker/docker/pull/13133#issuecomment-101079431

Feel free to test tomorrow if you have time then we will try to do the release on Wednesday.

**Comment by nathwill** [comment]
tested and verified with docker-1.6.2-rc1 on centos 7 with the cadvisor image. thanks for the quick resolution!

**Comment by crosbymichael** [comment]
@nathwill thanks for testing!

**Comment by vieux** [comment]
this is fixed in 1.6.2

**Comment by maxmeyer** [comment]
Hi, is this version active on hub.docker.com? I still get those errors there. Building them locally with docker 1.6.2 works fine.

https://registry.hub.docker.com/u/feduxorg/centos-ruby/build_id/44153/code/bkz889ik2krjhqaqdcep7jx/
https://registry.hub.docker.com/u/feduxorg/centos-ruby/

```
[8] System error: "/var/lib/docker/btrfs/subvolumes/fb7e252e96df1225a8464844893af04d843760628855285fb56b840fee49d950/sys/fs/cgroup" cannot be mounted because it is located inside "/sys"
```

**Comment by maxmeyer** [comment]
Sorry for the noise. Now it seems to be fixed on hub.docker.com. The issue does not occure anymore.

**Comment by thaJeztah** [comment]
@maxmeyer no problem. next time you're having issues with Docker Hub, report those at support@docker.com because those issues are not handled through GitHub

**Comment by maxmeyer** [comment]
Ok. Thanks for the information. Is there any info about this on docker hub? I was not aware that I need to report issues there.

**Comment by thaJeztah** [comment]
Actually, good question. I think it's there, but will have to look if it needs to be more prominent :-)

**Comment by maxmeyer** [comment]
Thanks. :-)

**Comment by thaJeztah** [comment]
Had a look, and agree, it's not very clear where to contact support.

Looking at the current beta for Docker Hub, it has been improved a bit https://hub-beta.docker.com/help/, although a clear "support" link could be even better. Perhaps you can open an issue here (if you think it needs to improved further and no such issue exists): https://github.com/docker/hub-beta-feedback/issues
