### ISSUE TITLE
Key server down for get.docker.com

### ISSUE THREAD

**Issue by trcarden** [docker/docker#13555]
Description of problem:
Key server down for get.docker.com

`docker version`:
Docker version 1.6.2, build 7c8fca2

`docker info`:
Containers: 2
Images: 47
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 51
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-53-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 6
Total Memory: 2.939 GiB
Name: vagrant-ubuntu-trusty-64.localdomain
ID: DID2:SFJ6:6GK2:3AUD:TIM2:4LCH:MWRL:JHCA:6ZMJ:ANUD:6Y3M:SP5R
WARNING: No swap limit support

`uname -a`:
Linux vagrant-ubuntu-trusty-64.localdomain 3.13.0-53-generic #89-Ubuntu SMP Wed May 20 10:34:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):
VirtualBox

How reproducible:
wget -qO- https://get.docker.com/ | sh

Steps to Reproduce:
1. Try to install docker with wget script

Actual Results:

```
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.xIf9seuuMo --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
?: p80.pool.sks-keyservers.net: Host not found
gpgkeys: HTTP fetch error 7:
```

Expected Results:

```
Install successful
```

Additional info:

Instead a workaround was found by changing the key server to be 

```
hkp://keyserver.ubuntu.com:80
```

There should likely be a fallback option so that the script doesn't fail on the off chance the primary key server is down.

**Comment by tianon** [comment]
Is there a p80 subset of the ha pool we could use to mitigate this, I
wonder?

**Comment by tianon** [comment]
Looks like not: https://sks-keyservers.net/overview-of-pools.php

We have to choose between high availability (meaning low likelihood of this particular issue happening) and port 80 (meaning available behind hyper-restrictive corporate firewalls).

**Comment by tianon** [comment]
Perhaps we should switch to the `ha` pool but add a comment that users behind insane firewalls should switch to the `p80` version (and provide it directly in the comment, of course)?

**Comment by labianchin** [comment]
This also affects docker-machine.
"docker-machine create" fails when p80.pool.sks-keyservers.net is not accessible. 

Is there any workaround to make "docker-machine create" to use the key from https://get.docker.com/gpg?

**Comment by trcarden** [comment]
@jfrazelle what was the resolution on this issue?

**Comment by jfrazelle** [comment]
it is back up, and we are already using the poool so idk what the solution
is but like the pool should not go down again, but such is life... i am
unsure what you want from us

**Comment by jfrazelle** [comment]
anything else regarding machine can be opened on that repo

**Comment by trcarden** [comment]
Perhaps some context will help. This script is the "approved" way of installing docker and many use it in their automated deployment and provisioning scripts (not just for interactive installation). It has a single point of failure on a key server. I would hope to have the script fallback to another perhaps the ubuntu key server considering the importance of this script and the reliability of the given key server. It should be pretty simple to add and would increase the reliability of the entire docker community.

**Comment by jfrazelle** [comment]
pull requests welcome ;)

**Comment by krifisk** [comment]
Although this issue is closed, I came across it so thought I'd add a comment. 1) ha.pool is currently not doing anything special, it is kept around for backwards compatibility and will be used down the line for servers that are clustered, but for a while all keyservers in the main pool require a reverse proxy (which was the original use for ha pool). 2) p80.pool exists and this explicitly checks for support on port 80, which is more firewall friendly. 3) There is too little information in the initial report to understand why the DNS request fails, this can be local forwarder issue, or anything intermittent, if you do experience issues with the pool, please contact me directly and include some DNS trace and network information (tracepath etc) so that it is possible to work on debugging it. Contact details at https://sks-keyservers.net/pks/lookup?op=vindex&search=0x0B7F8B60E3EDFAE3

**Comment by DanielDent** [comment]
I too have seen docker build & installs failing because of problems contacting the key servers.

I've been using incantations along these lines as a workaround:
`curl https://apt.dockerproject.org/gpg > docker.gpg.key && echo "c836dc13577c6f7c133ad1db1a2ee5f41ad742d11e4ac860d8e658b2b39e6ac1 docker.gpg.key" | sha256sum -c && apt-key add docker.gpg.key && rm docker.gpg.key`

**Comment by thaJeztah** [comment]
@DanielDent if you're able to reproduce, perhaps you can check the comment above yours, and provide that information there to allow debugging :+1:

**Comment by dhawal55** [comment]
It's happening again:
```
Step 4 : RUN curl -sSL https://get.docker.com/ | sh
 ---> Running in 535105cea61f
modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.1.10-17.31.amzn1.x86_64/modules.dep.bin'
Warning: current kernel is not supported by the linux-image-extra-virtual
 package.  We have no AUFS support.  Consider installing the packages
 linux-image-virtual kernel and linux-image-extra-virtual for AUFS support.
+ sleep 10
+ sh -c apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.LvALDKvBFJ --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
gpg: requesting key 2C52609D from hkp server p80.pool.sks-keyservers.net
?: p80.pool.sks-keyservers.net: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Success
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
The command '/bin/sh -c curl -sSL https://get.docker.com/ | sh' returned a non-zero code: 2
```

**Comment by sonicgao** [comment]
me too :(

**Comment by csandanov** [comment]
same here

**Comment by jfrazelle** [comment]
Ya there is not much we can do since we don't control the server you can use pgp.mit.edu and the instructions on docs.docker.com, commenting that it's down doesn't really do anything because yeah...

**Comment by bizhao** [comment]
@krifisk 
key server is down now. And your contact page is not accessible too.
https://sks-keyservers.net/pks/lookup?op=vindex&search=0x0B7F8B60E3EDFAE3

DNS server has no record to this domain ( sks-keyservers.net).

> server 8.8.8.8
Default Server:  google-public-dns-a.google.com
Address:  8.8.8.8

>  p80.pool.sks-keyservers.net
Server:  google-public-dns-a.google.com
Address:  8.8.8.8

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** Request to google-public-dns-a.google.com timed-out

> pool.sks-keyservers.net
Server:  google-public-dns-a.google.com
Address:  8.8.8.8

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** Request to google-public-dns-a.google.com timed-out

> sks-keyservers.net
Server:  google-public-dns-a.google.com
Address:  8.8.8.8

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** Request to google-public-dns-a.google.com timed-out

**Comment by markeijsermans** [comment]
http://p80.pool.sks-keyservers.net/ && https://sks-keyservers.net/status/ have been down for roughly 2 hrs. This has happened for me on several occasions (although for not as long). Perhaps look into another key service since sks-keyservers.net has generally been unreliable?

On debian/ubuntu it's possible to bypass this via `apt-get install -y --allow-unauthenticated docker-engine` which might be ok for dev/testing, but not for provisioning and breaks automated builds & CM.

**Comment by jfrazelle** [comment]
They all go down even pgp.mit.edu we could host one ourselves but that kinda defeats the purpose

**Comment by markeijsermans** [comment]
@jfrazelle very true. Using hkp://p80.pool.sks-keyservers.net:80 with a fall back to hkp://pgp.mit.edu:80 works for me

**Comment by krifisk** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On 01/14/2016 08:38 AM, Jess Frazelle wrote:
> They all go down even pgp.mit.edu we could host one ourselves but 
> that kinda defeats the purpose
> 
> 
> On Jan 13, 2016, 23:23 -0800, Mark 
> Eijsermans<notifications@github.com>, wrote:
>> 
>> http://p80.pool.sks-keyservers.net/&&https://sks-keyservers.net/statu
s/have
>>
>> 
been down for roughly 2 hrs.

Sorry about that, this time I can confirm that there were issues with
my infrastructure that have now been corrected.

>> This has happened for me on several occasions (although for not
>> as long). Perhaps look into another key service since
>> sks-keyservers.net has generally been unreliable?

This is more news to me, but if it happens please contact me directly
in order to get closer around to debugging it. Also, have you looked
into geographical pools rather than the primary pool in order to
reduce the likelihood of network issues in between?

- -- 
- ----------------------------
Kristian Fiskerstrand
Blog: https://blog.sumptuouscapital.com
Twitter: @krifisk
- ----------------------------
Public OpenPGP key at hkp://pool.sks-keyservers.net
fpr:94CB AFDD 3034 5109 5618 35AA 0B7F 8B60 E3ED FAE3
- ----------------------------
Testis unus, testis nullus
A single witness is no witness
-----BEGIN PGP SIGNATURE-----

iQEcBAEBCgAGBQJWl1wRAAoJECULev7WN52FjzwIAKBFYa/ayrfzLWAfhtDnQhYm
+5HRqxSE/gw1eym0BWkM92oJVglbVA8+Km3nQmL0jJxc/+7iFmZINkoXOo8qx07G
O2Gkfri8Cx1r/cY5K5kbwUy5ylOXBQpRMkP/TaZcl0OCmTJJLoZOB+EpFo+D0Vek
nwnlTKfp/L3HDyG25Pbl7eOTxjSf+qw9bVDwvTiJtngOMZNSovOUWLoTKYM+RIMb
V+KVsiYJu8g62RI/P8N3PKjoVsTbVupemCCPHVeDvrGp/L+P8zzbl/Qql/Qzugej
mLwgJRbpPJViQqFBwhaqFwLYhsbwgm5TfjoGw6movpVxZkRSx5b9I7EukFIaYgY=
=eSQb
-----END PGP SIGNATURE-----

**Comment by thaJeztah** [comment]
Thanks @krifisk !

**Comment by sstarcher** [comment]
@krifisk  Looks like `p80.pool.sks-keyservers.net` is down
```
 curl -sSL https://get.docker.com/ | sh
apparmor is enabled in the kernel and apparmor utils were already installed
+ sh -c apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.AQoM6Mr1rW --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
gpg: requesting key 2C52609D from hkp server p80.pool.sks-keyservers.net
gpg: keyserver timed out
```

**Comment by krifisk** [comment]
[Sent from my iPad, as it is not a secured device there are no cryptographic keys on this device, meaning this message is sent without an OpenPGP signature. In general you should *not* rely on any information sent over such an unsecure channel, if you find any information controversial or un-expected send a response and request a signed confirmation]

> On 20 Jan 2016, at 15:38, Shane Starcher <notifications@github.com> wrote:
> 
> @krifisk Looks like p80.pool.sks-keyservers.net is down
> 

I'm unable to reproduce, could you check the server it tries to connect to in the pool? I get several servers responding correctly here.

**Comment by sstarcher** [comment]
@krifisk I also can't reproduce it now.  I'll let you know if I can reproduce it again and track it back to a server.

**Comment by krifisk** [comment]
[Sent from my iPad, as it is not a secured device there are no cryptographic keys on this device, meaning this message is sent without an OpenPGP signature. In general you should *not* rely on any information sent over such an unsecure channel, if you find any information controversial or un-expected send a response and request a signed confirmation]

> On 20 Jan 2016, at 15:38, Shane Starcher <notifications@github.com> wrote:
> 
> @krifisk Looks like p80.pool.sks-keyservers.net is down
> 

FWIW, you can use  e.g lynx "http://p80.pool.sks-keyservers.net:80/pks/lookup?op=stats" to test  (or do a lookup?op=vindex&search=0xfingerprint etc)

**Comment by krifisk** [comment]
[Sent from my iPad, as it is not a secured device there are no cryptographic keys on this device, meaning this message is sent without an OpenPGP signature. In general you should *not* rely on any information sent over such an unsecure channel, if you find any information controversial or un-expected send a response and request a signed confirmation]

> On 20 Jan 2016, at 15:51, Shane Starcher <notifications@github.com> wrote:
> 
> @krifisk I also can't reproduce it now. I'll let you know if I can reproduce it again and track it back to a server.
> 

If you do, also make sure to check IPv4 vs IPv6 setup to the extent that interferes, in particular if firewalls are involved.

**Comment by basty** [comment]
Well... I'm trying to build the test environment: "docker build -t dry-run-test ." and I have the same problem:

?: p80.pool.sks-keyservers.net: Host not found

but doing a lynx/curl/etc and even an "apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys xxxxx" I get a successful result.

any clue?
thanks!

**Comment by xerebz** [comment]
Trying on the test environment "docker build -t dry-run-test ." and this wouldn't work. Had to run the apt-key commands as sudo, but still no success
```
alain@xenial:~/repos/docker$ docker build -t dry-run-test .
Sending build context to Docker daemon   121 MB
Step 1 : FROM debian:jessie
 ---> f50f9524513f
Step 2 : RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61 	|| apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61
 ---> Running in 1cf957033090
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.0nVEUbPQVn --no-auto-check-trustdb --trust-model always --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61
gpg: requesting key F6B0FC61 from hkp server p80.pool.sks-keyservers.net
^Calain@xenial:~/repos/docker$ apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61
Executing: /tmp/tmp.nUgwzEnuWS/gpg.1.sh --keyserver
hkp://p80.pool.sks-keyservers.net:80
--recv-keys
E871F18B51E0147C77796AC81196BA81F6B0FC61
gpg: requesting key F6B0FC61 from hkp server p80.pool.sks-keyservers.net
gpg: key F6B0FC61: "Launchpad PPA for Native ZFS for Linux" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
alain@xenial:~/repos/docker$ docker build -t dry-run-test .
Sending build context to Docker daemon   121 MB
Step 1 : FROM debian:jessie
 ---> f50f9524513f
Step 2 : RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61 	|| apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61
 ---> Running in 51d7b4da7bc9
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.C2lVqI3h7X --no-auto-check-trustdb --trust-model always --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61
gpg: requesting key F6B0FC61 from hkp server p80.pool.sks-keyservers.net
?: p80.pool.sks-keyservers.net: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Connection timed out
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.C2XVvdXDVF --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --keyserver hkp://pgp.mit.edu:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61
gpg: requesting key F6B0FC61 from hkp server pgp.mit.edu
?: pgp.mit.edu: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Connection timed out
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
The command '/bin/sh -c apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61 	|| apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61' returned a non-zero code: 2
```

**Comment by luigimannoni** [comment]
Same thing happens when I try to provision my Vagrant VM with Docker. In the last 2 days I managed to provision it just few times, especially today had hard time to make the `curl -sSL https://get.docker.com/ | sh` actually work.

Logs below:

```
==> default: Running provisioner: docker...
    default: Installing Docker onto machine...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

curl -sSL https://get.docker.com/ | sh

Stdout from the command:

Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.YpknloXNQw --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
?: p80.pool.sks-keyservers.net: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Success


Stderr from the command:

stdin: is not a tty
+ sh -c apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
gpg: requesting key 2C52609D from hkp server p80.pool.sks-keyservers.net
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
```

**Comment by thaJeztah** [comment]
We recently merged a PR to try multiple key-servers to prevent this. The updated script is not yet live on get.docker.com, but will soon be deployed; https://github.com/docker/docker/pull/20737

**Comment by luigimannoni** [comment]
Awww yeah! Party time!

![http://i.imgur.com/KVegB.gif](http://i.imgur.com/KVegB.gif)

**Comment by thaJeztah** [comment]
Unfortunately, we just discovered issues with those changes, so we need to hold off updating the script, and manually update it after we resolved those issues :cry:

**Comment by weishen** [comment]
`ws186013@ws186013-latitude-e5440:~/docker-repos/docker-fork$ sudo docker build -t dry-run-test .
Sending build context to Docker daemon 121.3 MB
Sending build context to Docker daemon 
Step 0 : FROM debian:jessie
 ---> a582cd499e0f
Step 1 : RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61 	|| apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61
 ---> Running in 26019c196a8d
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.yuGjF2PqBh --no-auto-check-trustdb --trust-model always --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61
gpg: requesting key F6B0FC61 from hkp server keyserver.ubuntu.com
?: keyserver.ubuntu.com: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Connection timed out
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.M5BGchU9RQ --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --keyserver hkp://pgp.mit.edu:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61
gpg: requesting key F6B0FC61 from hkp server pgp.mit.edu
?: pgp.mit.edu: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Connection timed out
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
INFO[0084] The command [/bin/sh -c apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61 || apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61] returned a non-zero code: 2 `
none of  the three keyservers works

**Comment by djskinner** [comment]
```

gpg: requesting key 2C52609D from hkp server p80.pool.sks-keyservers.net
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error

```

**Comment by GinoHereIam** [comment]
Same issue here:
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.MeX9Ml9380 --no-auto-check-trustdb --trust-model always --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61
gpg: requesting key F6B0FC61 from hkp server keyserver.ubuntu.com
?: keyserver.ubuntu.com: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Connection timed out
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.nE6MgY6H9M --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --keyserver hkp://pgp.mit.edu:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61
gpg: requesting key F6B0FC61 from hkp server pgp.mit.edu
?: pgp.mit.edu: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Connection timed out
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
The command '/bin/sh -c apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61      || apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61' returned a non-zero code: 2
make: *** [build] Error 1

**Comment by pananormalny** [comment]
Still there's a problem (UK - Sky)

`apparmor is enabled in the kernel and apparmor utils were already installed
+ sh -c apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.usvWBLje6v --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring
/etc/apt/trusted.gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
gpg: requesting key 2C52609D from hkp server p80.pool.sks-keyservers.net
?: p80.pool.sks-keyservers.net: Network is unreachable
gpgkeys: HTTP fetch error 7: couldn't connect: Network is unreachable
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0

root@ubuntu:~# curl -I p80.pool.sks-keyservers.net
HTTP/1.1 200 OK

root@ubuntu:~# ping p80.pool.sks-keyservers.net
PING p80.pool.sks-keyservers.net (144.76.43.40) 56(84) bytes of data.
64 bytes from obelix.hetzner.computer42.org (144.76.43.40): icmp_seq=1 ttl=53 time=20.3 ms
64 bytes from obelix.hetzner.computer42.org (144.76.43.40): icmp_seq=2 ttl=53 time=20.2 ms


Strange... Someone messed up configuration? Or they have some weird firewall rules? I think there should be an exception to handle that if the key can't be retrieved (for the first time) it should check different host/server.
`

**Comment by thaJeztah** [comment]
We'll update the installation script for docker 1.11, to try alternative locations; it's already in use for the current release candidates, and will be pushed to get.docker.com with the 1.11 release (see the updated script at https://test.docker.com

**Comment by nguyennb9** [comment]
I think it happened because of the dns setting. Just temporary change dns to 8.8.8.8
echo "nameserver 8.8.8.8" | resolvconf -a my_DNS.

**Comment by sjwoodr** [comment]
Happened for me again today.   Even google 8.8.8.8 dns can't resolve that hostname.    ¯\_(ツ)_/¯

**Comment by kris-davison** [comment]
ok I have found a solution at least in the meantime.

try hkp://keyserver.ubuntu.com:80

as neither hkp://p80.pool.sks-keyservers.net:80 or hkp://pgp.mit.edu:80 worked for me today.

output  below.....

sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.msvHI2cEwL --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
gpg: requesting key 2C52609D from hkp server keyserver.ubuntu.com
gpg: key 2C52609D: public key "Docker Release Tool (releasedocker) <docker@docker.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)

**Comment by kanaqsasak** [comment]
Thanks @kris-davison! Works for me too.

**Comment by grzegorz-gn** [comment]
Thanks @kris-davison! - it works !!!

**Comment by dm-wyncode** [comment]
Whatever the source of the exception, it is intermittent. I am spinning up and tearing down servers while testing some ansible playbooks. One of the tasks is to install docker-compose. Sometimes the keyserver address is resolved, sometimes it isn't.

**Comment by shriramsharma** [comment]
The issue still exists. I tried @kris-davison's work around and even that did not work. Any help?

`Step 1 : FROM debian:jessie
 ---> ff978d850939
Step 2 : RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61  || apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61        || apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61
 ---> Running in e6845278d12e
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.tAIznfvWme --no-auto-check-trustdb --trust-model always --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61
gpg: requesting key F6B0FC61 from hkp server p80.pool.sks-keyservers.net
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
?: p80.pool.sks-keyservers.net: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Connection timed out
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.DvHSyRt4lc --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --keyserver hkp://pgp.mit.edu:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61
gpg: requesting key F6B0FC61 from hkp server pgp.mit.edu
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
?: pgp.mit.edu: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Connection timed out
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.X9k0U3r4Fi --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61
gpg: requesting key F6B0FC61 from hkp server keyserver.ubuntu.com
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
?: keyserver.ubuntu.com: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Connection timed out
The command '/bin/sh -c apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61       || apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61        || apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61' returned a non-zero code: 2
make: *** [build] Error 1
`

**Comment by bhujangr** [comment]
Thanks @kris-davison . I have never had luck with ```p80.pool.sks-keyservers.net``` .

**Comment by chrisbrokethetable** [comment]
Does this workaround work on Debian machines too?

**Comment by kris-davison** [comment]
It should work as the Ubuntu url is just a keystore used as part of the installation so nothing Ubuntu specific.

**Comment by sghiassy** [comment]
I encountered the same problem. Try running the command as `sudo`.

**Comment by hsyed** [comment]
This problem does not seem to be getting the attention it deserves..... When this fails servers don't come up...

**Comment by thaJeztah** [comment]
@hsyed the installation script now uses three alternative servers, the first of which is already a pool of servers https://github.com/docker/docker/blob/v1.12.3/hack/install.sh#L31-L35. Do you have any suggestions what further improvements can be made if all of those fail?

**Comment by 27Bslash6** [comment]
It is happening again

/thegiant

**Comment by ipsi** [comment]
Down again. Trying to build a docker image based on several "official" docker images, and they *all* rely on ha.pool.sks-keyservers.net to build... Currently a bit hosed until it comes back up.

**Comment by thaJeztah** [comment]
@ipsi in your case, can you use `pgp.mit.edu` or `keyserver.ubuntu.com` as alternative? Looks like all `sks-keyservers.net` domains are down 😞

**Comment by ipsi** [comment]
@thaJeztah Yeah, the Ubuntu key server works for me, though it means I'm now diverging further away from the official `Dockerfile`, which I'm not super-keen on... At least it builds, though.

**Comment by thaJeztah** [comment]
I think the Dockerfile already uses pgp.mit.edu as backup; https://github.com/docker/docker/blob/master/Dockerfile#L29-L30 Does that fallback not work? If so we should look into that

**Comment by six8** [comment]
Couldn't Docker host the key server and make it more reliable? This really breaks automated builds.

**Comment by renkun-ken** [comment]
```
Executing: /tmp/tmp.dQA83d8sSt/gpg.1.sh --keyserver
hkp://ha.pool.sks-keyservers.net:80
--recv-keys
58118E89F3A912897C070ADBF76221572C52609D
gpg: requesting key 2C52609D from hkp server ha.pool.sks-keyservers.net
?: ha.pool.sks-keyservers.net: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Connection timed out
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver unreachable
gpg: keyserver communications error: public key not found
gpg: keyserver receive failed: public key not found
```

**Comment by thaJeztah** [comment]
@renkun-ken seems to work for me. I see you're from China, could this be a GFW issue? Have you tried one of the other servers as mentioned above? https://github.com/docker/docker/issues/13555#issuecomment-261972620

```
sh -c apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
Executing: /tmp/tmp.53dnnpdbNT/gpg.1.sh --keyserver
hkp://ha.pool.sks-keyservers.net:80
--recv-keys
58118E89F3A912897C070ADBF76221572C52609D
gpg: requesting key 2C52609D from hkp server ha.pool.sks-keyservers.net
gpg: key 2C52609D: public key "Docker Release Tool (releasedocker) <docker@docker.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
```

**Comment by renkun-ken** [comment]
@thaJeztah, `keyserver.ubuntu.com` works for me, thanks! Hope it'd be mentioned on the installation web page for users suffering from the same issue.

**Comment by thaJeztah** [comment]
@renkun-ken yes, the problem occurs sometimes, perhaps you're interested in opening a pull request to add a note? There's an "edit this page" link on the docs; https://docs.docker.com/engine/installation/linux/ubuntulinux/

**Comment by renkun-ken** [comment]
@thaJeztah, https://github.com/docker/docker.github.io/pull/1048

**Comment by justincormack** [comment]
opening a PR to fix this permanently see #29967

**Comment by trcarden** [comment]
🎉🎉🎉🎉 @justincormack
