### ISSUE TITLE
docker login: cannot input value for username on windows + powershell

### ISSUE THREAD

**Issue by jeffdm** [docker/docker#14336]
On windows, cannot input a value for `username`.  Previously opened as #14210, but I think this is an issue with the client on windows.

```
PS C:\> docker login
Username:    <--- cannot type any characters
```

**Comment by ssmith15** [comment]
I'm also having this issue. Your solution in the other thread worked but I am still having issues pushing to my repo regardless of being able to login now

**Comment by AlexZeitler** [comment]
+1

**Comment by ssmith15** [comment]
the solution that worked best for me was doing boot2docker ssh and then docker login. The images are all there when I do that

**Comment by jfrazelle** [comment]
ping @ahmetalpbalkan

**Comment by ahmetalpbalkan** [comment]
ACK. Looks like a problem with our ANSI emulation and reproes on both cmd.exe/powershell.

@jeffdm @AlexZeitler @ssmith15 as a workaround, you can use the `-u`/`-p`/`-e` flags of `docker login`.

**Comment by thaJeztah** [comment]
@ahmetalpbalkan @jhowardmsft will this be resolved by https://github.com/docker/docker/pull/14838?

**Comment by ahmetalpbalkan** [comment]
Unfortuantely, no. 






On Sunday, Jul 26, 2015 at 7:11 AM, Sebastiaan van Stijn <notifications@github.com>, wrote:

@ahmetalpbalkan @jhowardmsft will this be resolved by #14838?

**Comment by thaJeztah** [comment]
@ahmetalpbalkan bummer, just checking if I should've added a "closes xx" there. Thanks!

**Comment by Haiirokage** [comment]
There's still a problem if you have a signature without an email.
You have to put the -e flag not to freeze the command, but you can't provide the -e flag without giving it a value

**Comment by jhowardmsft** [comment]
Fixed in #17738

**Comment by ahmetalpbalkan** [comment]
Awesome
