### ISSUE TITLE
Docs for fedora installation are broken

### ISSUE THREAD

**Issue by aanm** [docker/docker#14364]
The page https://docs.docker.com/installation/fedora/ is broken. It seems there's a `</a>` missing.
Also, the docs are not updated for fedora 22:
```bash
$ sudo yum localinstall --nogpgcheck ./docker-engine-1.7.0-1.fc22.src.rpm
Yum command has been deprecated, redirecting to '/usr/bin/dnf localinstall --nogpgcheck ./docker-engine-1.7.0-1.fc22.src.rpm'.
See 'man dnf' and 'man yum2dnf' for more information.
To transfer transaction metadata from yum to DNF, run:
'dnf install python-dnf-plugins-extras-migrate && dnf-2 migrate'

No such command: localinstall. Please use /usr/bin/dnf --help
It could be a DNF plugin command, try: "dnf install 'dnf-command(localinstall)'"
```

**Comment by LK4D4** [comment]
ping @moxiegirl

**Comment by moxiegirl** [comment]
Thanks for the head's up.  This was fixed https://github.com/docker/docker/pull/14178. Will cherry-pick in and release.

**Comment by aanm** [comment]
@moxiegirl  Sorry but that fix doesn't fix the lack of "dnf" utlity on fedora 22.

**Comment by moxiegirl** [comment]
Thanks for the catch.  I'll cp it in

**Comment by moxiegirl** [comment]
Ok, so I ran an install on a Fedora image.  Our instructions say they were tested on 21 and if you are installing on 20/22 you may need to tweak them.  A user on 22 that attempts the procedure with `yum` gets auto directed to `dnf` if they don't have `dnf` they get a nice error messages:

```
[fedora@ip-172-31-19-198 ~]$ yum list installed | grep docker
Yum command has been deprecated, redirecting to '/usr/bin/dnf list installed'.
See 'man dnf' and 'man yum2dnf' for more information.
To transfer transaction metadata from yum to DNF, run:
'dnf install python-dnf-plugins-extras-migrate && dnf-2 migrate'
```

Essentially, I can't anticipate that a user will or won't have this issue.  If they do, they receive a recovery message from their OS which serves the situation nicely.

**Comment by aanm** [comment]
@moxiegirl Please see the command I was using, I didn't specify the "yum list" I wrote the `sudo yum localinstall --nogpgcheck ./docker-engine-1.7.0-1.fc22.src.rpm` this won't work

**Comment by aanm** [comment]
@moxiegirl Sorry my bad, I was using src.rpm instead of rpm. It works ;-)

**Comment by moxiegirl** [comment]
Yay! :-D
