### ISSUE TITLE
docker build: tls: oversized record received with length

### ISSUE THREAD

**Issue by bitsofinfo** [docker/docker#14793]
```
$ docker build .
Sending build context to Docker daemon
An error occurred trying to connect: Post https://192.168.1.200:2375/v1.19/build?cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&memory=0&memswap=0&rm=1&t=: tls: oversized record received with length 20527
```

On CLIENT
```
$ docker -v
Docker version 1.7.0, build 0baf609
```

On HOST
```
$ docker -v
Docker version 1.7.1, build 786b29d-dirty
```

**Comment by bitsofinfo** [comment]
fixed it w/ 

```
LAPTOP $ unset DOCKER_TLS_VERIFY
LAPTOP $ unset DOCKER_CERT_PATH
```

**Comment by mimoralea** [comment]
Another option is to add the option `INSECURE_REGISTRY='--insecure-registry yourprivateregistry.com:5000'` to your docker config.

https://docs.docker.com/registry/insecure/

**Comment by ssharifi02** [comment]
mine still not fixed after i even tried insecure registry and also the two commands that bitsofinfo said!!!  im stuck

**Comment by thaJeztah** [comment]
@ssharifi02 you'll get this error either when trying to connect to a TLS (secure) socket, but without using TLS, or the other way round; connecting to an unprotected socket, but trying to connect with TLS. It's not a bug in docker, but a configuration issue

**Comment by derekmahar** [comment]
@thaJeztah I'm encountering the same issue as @ssharifi02.  I've set `INSECURE_REGISTRY` on both the registry server and the client, but `docker push` still complains about TLS:

```
derek@derek-lubuntu:~/Projects/docker-library$ grep insecure /etc/default/docker
DOCKER_OPTS="--insecure-registry javaqa:5000"
derek@derek-lubuntu:~/Projects/docker-library$ sudo service docker restart
derek@derek-lubuntu:~/Projects/docker-library$ docker push javaqa:5000/opes/tomcat
The push refers to a repository [javaqa:5000/opes/tomcat]
Get https://javaqa:5000/v1/_ping: tls: oversized record received with length 20527

```

**Comment by thaJeztah** [comment]
@derekmahar note that insecure registry will still try to make a TLS connection first, but allows falling back to non-TLS. Did this setup work before?

**Comment by derekmahar** [comment]
@thaJeztah I can't recall whether I've tried to use an insecure registry.  I recall getting TLS to work using a certificate and I believe a self-signed certificate.  I'd like to get the non-TLS registry working simply because it's a more straightforward setup and this particular registry is strictly internal and behind a firewall.

**Comment by thaJeztah** [comment]
@derekmahar also be sure to check if `/etc/default/docker` is actually used on your system (i.e., it isn't used for systems using `systemd`)

**Comment by derekmahar** [comment]
@thaJeztah I'm running Ubuntu Server 16.04 which uses systemd, so that explains why changing `/etc/default/docker` had not effect on TLS.  Which file(s) should I change when using systemd?

**Comment by thaJeztah** [comment]
Easiest way (and working on both systemd and upstart), is to use a `daemon.json` configuration file; see https://docs.docker.com/engine/reference/commandline/dockerd/#/daemon-configuration-file

In the upcoming docker 1.12, you can even add/remove insecure registries without restarting the daemon (just sending it a `SIGHUP` would work)

**Comment by derekmahar** [comment]
@thaJeztah Should Docker for Ubuntu Server 16.04 have already created `/etc/docker/daemon.json`?  `/etc/docker/daemon.json` doesn't exist on my server.  Without it, how does Docker configure it's daemon?

**Comment by thaJeztah** [comment]
@derekmahar the file isn't there by default; without that file, only the flags in the systemd unit file are used. The daemon checks if a daemon.json file exists, and if it does, loads settings from that. Note, however, that you cannot set the same *both* as a flag *and* in `daemon.json`; in that case, the daemon will show an error when it starts ('conflict'); this is by design. So (in this case), either set the `--insecure-registry` (as a flag), *or* set it in `daemon.json`

**Comment by derekmahar** [comment]
Hooray!  Setting `insecure-registries` in `/etc/docker/daemon.json` worked!

```
derek@derek-lubuntu:~/Projects/docker-library$ sudo cat /etc/docker/daemon.json
{
	"insecure-registries": ["javaqa:5000"]
}
derek@derek-lubuntu:~/Projects/docker-library$ sudo service docker restart
derek@derek-lubuntu:~/Projects/docker-library$ docker push javaqa:5000/opes/tomcat
The push refers to a repository [javaqa:5000/opes/tomcat]
05249acac3bd: Pushed 
d224564db26c: Pushed 
867726bfaf0e: Pushed 
c257c9508e06: Pushed 
9ec8df73ad09: Pushed 
4df3dc4e41db: Pushed 
5fa88c5ac09f: Pushed 
b5d7c200f6f3: Pushed 
a703d1f77f17: Pushed 
9176ec7d1a0c: Pushed 
788c89434030: Pushed 
79aea7ff834f: Pushed 
d1c800db26c7: Pushed 
42755cf4ee95: Pushed 
latest: digest: sha256:f7f3e4620b3b8009687b8c8328d08e2416a517eb1e210d16f76427013e831490 size: 3250
```

Thank you for your help.

**Comment by ssharifi02** [comment]
I'm using docker toolbox on windows, so many things are different,

**Comment by homerakshay** [comment]
Hey there, 

I have been facing the same issue since 2 days now. Drained out thinking about a fix. 

My nonproduction cluster setup : 

2 swarm-managers
2 swarm-nodes
1 consul-server

I have set --insecure-registry in /etc/sysconfig/docker as i am on Amazon linux. All works fine when i try to push images to my private repo which is backed by an s3 bucket. However when i do a push from my jenkins job, i get this error : 

The push refers to a repository [my-registry:5000/my-image]
Get https://my-registry:5000/v1/_ping: tls: oversized record received with length 20527

Please help. Any feedbacks will be great in debugging this issue. :)

**Comment by ssharifi02** [comment]
im new to all this but one time i tried and increased my RAM in my virtualbox vm and it did work also i used the command docker-machine create --driver virtualbox \--engine-insecure-registry yourreponame:5000 vmname to create my vm.

**Comment by homerakshay** [comment]
@ssharifi02 thanks for the quick revert.. But I have managed to fix that issue for now by logging into Jenkins server and running the registry daemon as insecure 🙂 But now there is a new issue.. When trying to push to the repo I get 'trying in 10seconds' for all layers and that continues and eventually a failure in build saying 'blob upload unknown' any idea what this may be? It's really annoying 😁

**Comment by homerakshay** [comment]
@group: I have created a separate ticket for this issue, with all the details needed. Please do look into it and helpppp. :) 

https://github.com/docker/docker/issues/24772

**Comment by vae1314** [comment]
@homerakshay  how do you solve this issue? 

[root@SXNT05 nodejs]# docker push ****:5000/hello-world
The push refers to a repository [*****:5000/hello-world]
Get https://*****:5000/v1/_ping: tls: oversized record received with length 20527

**Comment by vae1314** [comment]
@thaJeztah  hello, how do you solve this issue? I use centos7, Add /etc/docker/daemon.json, docker service start error.

[root@SXNT05 nodejs]# docker push *:5000/hello-world
The push refers to a repository [:5000/hello-world]
Get https://***:5000/v1/_ping: tls: oversized record received with length 20527

**Comment by homerakshay** [comment]
@thaJeztah  Hi.. Firstly could you let me know how many swarm managers you running on your cluster? Also which version? ( I recommend the latest 2.4 ).. Also please remove the daemon.json file for good 🙂 Let me know the details and il help you get it up and running 🙂👍

Best,
Akshay

**Comment by ssharifi02** [comment]
$ docker-machine regenerate-certs nameofyourvirtualmachine  in Docker for windows, did solve my problem

**Comment by abrahamjaison01** [comment]
Hey all.. Thanks.. I too had the same problem of oversized record received..! But after going through the steps I was able to solve that but now I am still unable to push images as another error popped up.. Why does this error occur "No basic auth credentials.."..??

```

> [root@mymachine docker]# docker push 172.30.155.111:5000/default/mycostumedaemon
> The push refers to a repository [172.30.155.111:5000/default/myconstumedaemon]
> 0a4a35d557a6: Preparing
> 025eba1692ec: Preparing
> 5332a889b228: Preparing
> d0965b23760e: Preparing
> 54627db2e9bd: Preparing
> ce929ad33a2c: Waiting
> 955efbe7485a: Waiting
> e7b287e8074b: Waiting
> 2596901171f0: Waiting
> 43ddd31bc316: Waiting
> e1389d3eb37a: Waiting
> b376ebfc5566: Waiting
> 33c3a104206a: Waiting
> 149636c85012: Waiting
> f96222d75c55: Waiting
> no basic auth credentials

```

Any thoughts on this please..??

**Comment by thaJeztah** [comment]
@abrahamjaison01 please submit a post on https://forums.docker.com. The issue tracker is not a general support forum

**Comment by bcgshyam** [comment]
@thaJeztah I am facing a similar issue:
`Get https://registry-1.docker.io/v2/: proxyconnect tcp: tls: oversized record received with length 20527 `
when I do a `docker pull`. The above solution doesn't seem to work.
Running Ubuntu 16.04 on VMware Workstation.
