### ISSUE TITLE
fixed-cidr and default-gateway cause out of range error when subnetting bridge

### ISSUE THREAD

**Issue by TuxInvader** [docker/docker#14859]
The documentation for networking implies that I should be able to set a fixed-cidr which is a subnet of the bridge address. However the daemon barfs if the gateway I chose is not within the fixed-cidr range. This check should be that the gateway is within the CIDR of the bridge, not the fixed-cidr. 

    $ sudo ip addr add 192.168.0.254/24 dev docker1
    $ sudo docker -d --fixed-cidr=192.168.0.0/25 -b docker1 --default-gateway=192.168.0.250
    INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
    INFO[0000] [graphdriver] using prior storage driver "aufs" 
    WARN[0000] Running modprobe bridge nf_nat failed with message: , error: exit status 1 
    FATA[0000] Error starting daemon: Error initializing network controller: Error creating default "bridge" network: requested ip is out of range 

Interestingly; Docker instances do get given the IPPrefexLength of the bridge. In my example /24, so there's no problem with assigning a default gateway outside of the fixed-cidr. 

My use case is that I want to have a bridge attached to a physical/virtual nic on multiple docker hosts, and allow containers on the hosts to share a Layer 2 network and use an external router.

$ docker --version
Docker version 1.7.1, build 786b29d

$docker info
Containers: 19
Images: 35
Storage Driver: aufs
 Root Dir: /home/data/docker/aufs
 Backing Filesystem: extfs
 Dirs: 73
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-41-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 8
Total Memory: 15.39 GiB
Name: goldfish
ID: SEDL:2YVT:EZLV:T44V:VBOB:74ME:NX4C:ZQFX:LBH2:QUXI:WCI3:RIGL
Username: tuxinvader
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

$ uname -a
Linux goldfish 3.16.0-41-generic #57~14.04.1-Ubuntu SMP Thu Jun 18 18:01:13 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cpuguy83** [comment]
ping @mrjana

**Comment by eolamey** [comment]
I had the exact same issue and opened https://github.com/docker/libnetwork/issues/287 some time ago.

**Comment by mrjana** [comment]
@TuxInvader @eolamey There is a PR open in docker/libnetwork to fix this. We will try to get it in docker 1.8 release

**Comment by eolamey** [comment]
@mrjana thanks, that would be awesome!

**Comment by thaJeztah** [comment]
@mrjana want me to add this to the 1.8 milestone?

**Comment by TuxInvader** [comment]
Excellent - Thanks guys!

Apologies for the dupe bug, I didn't spot the previous issue in my searches.

**Comment by mrjana** [comment]
@thaJeztah sure

**Comment by thaJeztah** [comment]
@TuxInvader no problem, you encountered the issue while using Docker; We can't expect you to search the other repos as well. I think it's good to have this issue opened here, so that we can keep track here.

@mrjana added to the milestone; please add a `fixes #14859` when updating the vendored libnetwork

**Comment by thaJeztah** [comment]
Great! @TuxInvader this should now be fixed in master (https://github.com/docker/docker/issues/14966 was merged) and be part of the 1.8 release.

If you want to test if this resolved your issue, you can download binaries from https://master.dockerproject.org. Thanks again for reporting :+1:

**Comment by TuxInvader** [comment]
@thaJeztah I've tested in my lab and there is still a problem. The daemon accepts my settings, but it is now assigning docker containers addresses from the whole IP range, not from the fixed-cidr range.

    + sudo brctl addbr docker1
    + sudo brctl addif docker1 eth0
    + sudo brctl stp docker1 on
    + sudo ip addr add 172.16.0.10/16 dev docker1
    + sudo ip link set dev docker1 up
    + sudo /usr/local/bin/docker daemon --fixed-cidr=172.16.1.0/24 -b docker1 --default-    gateway=172.16.0.254 --dns=10.1.1.1 -g /home/data/docker/
    INFO[0000] [graphdriver] using prior storage driver "aufs" 
    INFO[0000] Option DefaultDriver: bridge                 
    INFO[0000] Option DefaultNetwork: bridge                
    INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
    WARN[0000] Running modprobe bridge nf_nat br_netfilter failed with message: modprobe: WARNING: Module br_netfilter not found. , error: exit status 1 
    INFO[0000] Firewalld running: false                     
    WARN[0000] Your kernel does not support swap memory limit. 
    INFO[0000] Loading containers: start...
    INFO[0000] Loading containers: done.                    
    INFO[0000] Daemon has completed initialization          
    INFO[0000] Docker daemon                                 commit=b04dd6b execdriver=native-0.2 graphdriver=aufs version=1.8.0-dev
    INFO[0043] POST /v1.20/containers/create                
    ERRO[0043] Couldn't run auplink before unmount: exec: "auplink": executable file not found in $PATH 
    ERRO[0043] Couldn't run auplink before unmount: exec: "auplink": executable file not found in $PATH 
    ERRO[0043] Couldn't run auplink before unmount: exec: "auplink": executable file not found in $PATH 
    INFO[0043] POST /v1.20/containers/862d153c10ddc2c872f73c62e36629ab7350e78b8d2fb592eb301a9e6c37c895/start 
    INFO[0047] GET /v1.20/containers/862d153c10ddc2c872f73c62e36629ab7350e78b8d2fb592eb301a9e6c37c895/json 
    INFO[0063] GET /v1.20/containers/862d153c10ddc2c872f73c62e36629ab7350e78b8d2fb592eb301a9e6c37c895/json 
    INFO[0068] GET /v1.20/containers/862d153c10ddc2c872f73c62e36629ab7350e78b8d2fb592eb301a9e6c37c895/json 

But.....

    docker inspect 862d153c10ddc2c872f73c62e36629ab7350e78b8d2fb592eb301a9e6c37c895

    "IPAddress": "172.16.0.1"
    "IPPrefixLen": 16,
    "Gateway": "172.16.0.254",

So it's all fine, except for the IPAddress assignments

Cheers,
Mark

**Comment by thaJeztah** [comment]
ping @mrjana perhaps you can check ^^

**Comment by aboch** [comment]
Thanks @TuxInvader for finding this. It's a genuine issue.
Working on a fix in libnetwork side.

**Comment by LK4D4** [comment]
I am reopening

**Comment by calavera** [comment]
fixed in #15185
