### ISSUE TITLE
Docker is not communicating with remote insecure private registry

### ISSUE THREAD

**Issue by koyadume** [docker/docker#15324]
I am trying to setup a remote private registry as mirror for docker. For this I am running docker with following arguments -

```
sudo docker --insecure-registry=192.168.1.22:5000 --registry-mirror=http://192.168.1.22:5000 -d
```
When I try to pull an image  -
```
docker pull busybox
```
I see following output in docker daemon logs -
```
INFO[0022] POST /v1.19/images/create?fromImage=busybox%3Alatest
ERRO[0022] Unable to create endpoint for http://192.168.1.22:5000/: invalid registry endpoint https://192.168.1.22:5000/v0/: unable to ping registry endpoint https://192.168.1.22:5000/v0/
v2 ping attempt failed with error: Get https://192.168.1.22:5000/v2/: dial tcp 192.168.1.22:5000: connection refused
 v1 ping attempt failed with error: Get https://192.168.1.22:5000/v1/_ping: dial tcp 192.168.1.22:5000: connection refused. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry 192.168.1.22:5000` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/192.168.1.22:5000/ca.crt
```

* ```connection refused``` error is fine as registry is currently not running on a VM with 192.168.1.22 ip. But why it's using ```https``` instead of  ```http``` to ping the repository when I have defined ```--insecure-registry``` flag?

* It's asking to add ```--insecure-registry``` flag but that is already added?

* It's using docker hub as fallback repository which should not be the case if  ```--registry-mirror``` flag has been defined (I believe this is the expected behavior). 

```
docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```

```
docker info
Containers: 0
Images: 3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 3
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-30-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 993.7 MiB
Name: laptop
WARNING: No swap limit support
```

```
uname -a
Linux laptop 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by aidanhs** [comment]
> But why it's using https instead of http to ping the repository when I have defined --insecure-registry flag?

`--insecure-registry` allows two things - https with a self-signed certificate and http. It therefore needs to try both https and http. Besides, it'd be pretty annoying if adding `--insecure-registry` broke access for a secure registry! And secure registries need to try https.

> It's asking to add --insecure-registry flag but that is already added?

I think this is just a boilerplate message when a connection fails. It probably could be better, but I suggest you raise a different issue for that.

> It's using docker hub as fallback repository which should not be the case if --registry-mirror flag has been defined (I believe this is the expected behavior).

Have you read the [documentation](https://docs.docker.com/articles/registry_mirror/) on what the registry mirror is actually for? While the name is could be better, this bit of documentation is particularly helpful:

> The first time you request an image from your local registry mirror, it pulls the image from the public Docker registry and stores it locally before handing it back to you. On subsequent requests, the local registry mirror is able to serve the image from its own storage.

i.e. it's clearly for deliberately caching requests to the docker hub which means it needs to be the first thing visited. It would also be unhelpful if the pull silently redirected to the main registry given this stated intention of helping you enforce bandwidth reduction.

**Comment by koyadume** [comment]
@aidanhs 

* If you look at the logs, you will see that there is no error message for ```http``` v2 endpoint but it should be there as I don't have a private registry running on the remote VM. So it makes me believe that it's not trying ```http``` v2 endpoint at all.

* Regarding you comment on private mirror registry, I will say that you misunderstood my point. Behavior defined for private registry in ```How does it work?``` section is standard behavior for mirror/proxy repositories. However non standard behavior is using docker hub as fallback registry. I am using private registry in development environment for saving bandwidth but in production environment, I would like to use it as trusted repository without mirroring enabled. So if docker is using docker hub as fallback registry in a production environment when it is unable to reach to a private registry or because it's unable to find an image in private registry then its doing something which is not desirable in almost all use cases for private registry.

I think when a person has configured one or more private registries configured then docker should use ONLY these repositories and throw an exception if it is unable to find an image in private registries and should not communicate with docker hub at all.

Also this may give a wrong impression to users where a user feels that docker is puling images from private registry but actually it's pulling images from docker hub.

**Comment by aidanhs** [comment]
Well the way to tell if it's using the v2 endpoint would be to actually start one up and see if it works...

Ah! So you're saying it **is** going to the docker hub and that you don't want it to? In that case we agree, I *thought* you were saying the central registry should still be the primary registry, which made no sense to me.

> in production environment, I would like to use it as trusted repository without mirroring enabled

Wouldn't you achieve this by

1. not enabling `--registry-mirror`
2. only pulling images with names like `my.private.registry.internal/image/name`

I'm not sure if it's possible for a single registry to be used as both a mirror and a private registry at the same time.

**Comment by koyadume** [comment]
@aidanhs 
* I tested it after running registry on the remote VM but I don't see any request for ```http``` v2 endpoint -
```
time="2015-08-06T01:37:50.403710576Z" level=info msg="response completed" environment=development http.request.host="192.168.1.22:5000" http.request.id=668e818d-0b02-4f05-bf23-addd37361a05 http.request.method=GET http.request.remoteaddr="192.168.1.21:49153" http.request.uri="/v1/images/8c2e06607696bd4afb3d03b687e361cc43cf8ec1a4a725bc96e39f05ba97dd55/ancestry" http.request.useragent="docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.16.0-30-generic os/linux arch/amd64" http.response.contenttype="text/plain; charset=utf-8" http.response.duration="482.781µs" http.response.status=404 http.response.written=19 instance.id=a7a6413b-ced5-4515-ab28-a57caf77940b service=registry version=v2.0.1
192.168.1.21 - - [06/Aug/2015:01:37:50 +0000] "GET /v1/images/8c2e06607696bd4afb3d03b687e361cc43cf8ec1a4a725bc96e39f05ba97dd55/ancestry HTTP/1.1" 404 19 "" "docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.16.0-30-generic os/linux arch/amd64"
```

* I am accessing docker over remote api using a UI application where it will not be allowed to prefix an image with registry host name. The reason is that this can allow a user to pull images from a registry other than what docker is configured with and so user can pull non trusted images into docker.

* ```--registry-mirror``` flag does not seem to be an appropriate name to me as  docker daemon can't decide whether a registry will act as a mirror or not since mirroring is something which is configured on registry side. So this should either be called only ```--registry``` or ```--proxy-registry```.

**Comment by anthonygreen** [comment]
I'm seeing this issue too

**Comment by hishamsharif** [comment]
Hi,

It seems like the issue has been resolved in v1.8.1  , 
please check similar issue :  [https://github.com/docker/docker/issues/15494](https://github.com/docker/docker/issues/15494)

**Comment by cpuguy83** [comment]
Is this still a problem in 1.12?

Closing tentatively as there has been a lot of work in the push/pull code. Note that you can also disable v1 support in the daemon options with `--disable-legacy-registry`

**Comment by isanych** [comment]
Looks like issue still there in docker 1.13.0 with registry 2.6.0

```
$ docker info
Server Version: 1.13.0
Insecure Registries:
 docker.acme.com
 registry-proxy.acme.com
 127.0.0.0/8
Registry Mirrors:
 registry-proxy.acme.com
```

As push is not supported when proxy enabled in registry, I'm running separate registry-proxy:
```
docker run -d -p 172.16.177.14:80:5000 -v /data/registry-proxy:/var/lib/registry \
 -e REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io \
 --restart always --name registry-proxy registry
```

there is nothing in registry-proxy logs during docker pull, and docker log contains:

```
Feb 02 11:32:17 jbuild dockerd[19080]: time="2017-02-02T11:32:17.882355444Z" level=warning msg="Error getting v2 registry: Get https://registry-proxy.acme.com/v2/: dial tcp 172.16.177.14:443: getsockopt: connection refused"
Feb 02 11:32:17 jbuild dockerd[19080]: time="2017-02-02T11:32:17.882403803Z" level=error msg="Attempting next endpoint for pull after error: Get https://registry-proxy.acme.com/v2/: dial tcp 172.16.177.14:443: getsockopt: connection refused"
```

```
$ curl http://registry-proxy.acme.com/v2/
{}
$ curl http://registry-proxy.acme.com/v2/_catalog
{"repositories":[]}
```
