### ISSUE TITLE
Why digest fields are displayed as none Type?

### ISSUE THREAD

**Issue by aaae** [docker/docker#15508]
$ docker images --digests=true
    REPOSITORY                         TAG                 DIGEST              IMAGE ID            CREATED             VIRTUAL SIZE
    docker.io/mysql                    5.6.26              <none>              a128139aadf2        2 weeks ago         283.8 MB
    docker.io/redis                    latest              <none>              0ff407d5a7d9        3 weeks ago         109.5 MB
    docker.io/registry                 2.0.1               <none>              f9684be4155a        4 weeks ago         548.6 MB
    docker.io/busybox                  latest              <none>              8c2e06607696        3 months ago        2.43 MB
    gcr.io/google_containers/pause     0.8.0               <none>              6c4579af347b        12 months ago       239.8 kB

and where will use digest?

**Comment by songkemail** [comment]
please try docker images --no-trunc | head

**Comment by cpuguy83** [comment]
Yeah, I don't understand this either.
ping @stevvooe

**Comment by stevvooe** [comment]
@aaae The digest provides a content-address for docker images. The missing values are an unfortunate side-effect of how we store and manage image digests. Currently, these are stored as tags and only under certain conditions. Images that don't have a digest (which can be all of them) will have the digest displayed as `<none>`.

As we better integrate content-addressability into the daemon itself, these values will become more stable and be available for all images.

**Comment by thaJeztah** [comment]
Should we keep this issue open? The original question has been answered

**Comment by stevvooe** [comment]
@thaJeztah We should fix this bug.

@aaronlehmann @tonistiigi Will we get this fixed in the future, such that a digest is available for every image?

**Comment by aaronlehmann** [comment]
In the near future, the image ID will become a content address. In this sense, a digest will be available for every image.

However, the current digest field is used to identify manifest digests for images that have been pulled by digest rather than by tag. This concept will still exist when images are content-addressable. So this particular digest field will still only apply to some images.

**Comment by stevvooe** [comment]
> However, the current digest field is used to identify manifest digests for images that have been pulled by digest rather than by tag. This concept will still exist when images are content-addressable. So this particular digest field will still only apply to some images.

This was more of a side-effect of the implementation rather than an intended feature. If we can remove this behavior, and have a proper digest for everything, it would be a lot better.

**Comment by HackToday** [comment]
It seems this issue still exist.  When will we would fix this ?
``` 
root@dccee5a197a7:/go/src/github.com/docker/docker# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ouruser/sinatra     devel               ffccd5f4334b        6 minutes ago       452.4 MB
ouruser/sinatra     v2                  ffccd5f4334b        6 minutes ago       452.4 MB
ubuntu              latest              1c9b046c2850        10 days ago         187.9 MB
centos              latest              61b442687d68        3 weeks ago         196.6 MB
busybox             latest              d9551b4026f0        5 weeks ago         1.113 MB
nate/dockviz        latest              3668e74867b8        9 weeks ago         5.947 MB
training/sinatra    latest              49d952a36c58        19 months ago       447 MB
root@dccee5a197a7:/go/src/github.com/docker/docker# docker version
Client:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   67929bd
 Built:        Fri Jan 15 03:09:06 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   67929bd
 Built:        Fri Jan 15 03:09:06 2016
 OS/Arch:      linux/amd64
root@dccee5a197a7:/go/src/github.com/docker/docker# docker images --digests
REPOSITORY          TAG                 DIGEST              IMAGE ID            CREATED             SIZE
ouruser/sinatra     devel               <none>              ffccd5f4334b        About an hour ago   452.4 MB
ouruser/sinatra     v2                  <none>              ffccd5f4334b        About an hour ago   452.4 MB
ubuntu              latest              <none>              1c9b046c2850        10 days ago         187.9 MB
centos              latest              <none>              61b442687d68        3 weeks ago         196.6 MB
busybox             latest              <none>              d9551b4026f0        5 weeks ago         1.113 MB
nate/dockviz        latest              <none>              3668e74867b8        9 weeks ago         5.947 MB
training/sinatra    latest              <none>              49d952a36c58        19 months ago       447 MB
root@dccee5a197a7:/go/src/github.com/docker/docker# 447 MB

```

**Comment by stevvooe** [comment]
@aaronlehmann Shouldn't these digests exist in the latest version?

**Comment by thaJeztah** [comment]
Perhaps they should be combined, i.e. currently an image has either a *tag* or a *digest* in the list, in that case the head could show `TAG / DIGEST`

**Comment by stevvooe** [comment]
@thaJeztah They are in no way equivalent and we should not be reinforcing that idea.

**Comment by sirlatrom** [comment]
I can confirm this still is an issue with Docker 1.10.1. It prevents any reasonable form of automation with Docker Content Trust, as the only time the digest is available is in the output from `docker push`, e.g.

```
# docker push redacted.example.com/namespace/image:tag
[The push refers to a repository [redacted.example.com/namespace/image]
b40428476b7a: Layer already exists 
6057236047d9: Layer already exists 
dbcbac958d69: Layer already exists 
ba60a0e9f154: Layer already exists 
4c7a05b9f3c4: Layer already exists 
5f70bf18a086: Layer already exists 
4915f908919a: Layer already exists 
af6d4541205c: Layer already exists 
b90cf634e321: Layer already exists 
b7fb86c085cb: Layer already exists 
e7788833b83a: Layer already exists 
27b7abd92fd9: Layer already exists 
5c5b99a3d7e9: Layer already exists 
ed18fe2d435e: Layer already exists 
628a915caf0d: Layer already exists 
tag: digest: sha256:293bdd0ada30f83d00179cb72123b9377ddf566d7b14fa8f4704184f3ecb90a7 size: 21037
Signing and pushing trust metadata
Enter passphrase for repository key with ID d19614a (redacted.example.com/namespace/image): ](url)
```

Neither `docker images --digests` nor `docker inspect redacted.example.com/namespace/image:tag` will reveal the digest.

**Comment by stevvooe** [comment]
Agreed that this is still a bug:

1. The digests should always be available.
2. The digests available should represent the identifier available in a remote registry.

**Comment by HuKeping** [comment]
Should we close #20931  @thaJeztah

**Comment by jakirkham** [comment]
Also, would expect that after pulling an image by tag and digest that they would show as one image that has a tag and a digest, but that is not the case.

```
$ docker images --digests
REPOSITORY                     TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
debian                         jessie              <none>                                                                    f50f9524513f        5 days ago          125.1 MB
debian                         <none>              sha256:a9c958be96d7d40df920e7041608f2f017af81800ca5ad23e327bc402626b58e   f50f9524513f        5 days ago          125.1 MB
```

**Comment by thaJeztah** [comment]
@HuKeping yes, let me close that one

**Comment by HuKeping** [comment]
As the present code, in a `DCT` pull, daemon will first pull the image by digests and then `tag` it with a tag, `latest` for example. So there are two images after a `DCT` pull and one with <none> in tag field and the other with <none> in digest field. 

How about take the `digest` info with it when doing the `tag` action and delete the digest one when finish the `tag` action?

**Comment by sirlatrom** [comment]
Any milestone for this?

**Comment by ProTip** [comment]
I believe this may be preventing uploading tags on existing images without checking all the layers?

**Comment by haytoo1** [comment]
right now,  this is still a bug

**Comment by thaJeztah** [comment]
Ping @dmcgowan will this be resolved by https://github.com/docker/docker/pull/23996, or are more changes needed?

**Comment by dmcgowan** [comment]
#23996 does address this by ensuring that anytime a manifest is created or pulled the digest is stored. This will reduce the occurrence of "<none>" in the digest field, but they will still occur before an image manifest is created or seen. The UX is also greatly improved in regards to images which do have a digest, no longer will the output show tag and digest as 2 different lines, but combined together when referring to the same image id. 

As for more changes needed, I think we will have to wait and see. Ideally we always have a digest but that is not possible without having the distribution artifact hashes, which are not currently calculated on commit.

**Comment by HuKeping** [comment]
Run a local test, #23996 seems works for me, thanks!

**Comment by dmcgowan** [comment]
The digest field will no longer be `<none>` after push and pull operations. This field can now be used after push to get the manifest digest which was pushed to the registry. Closing this issue as resolved.

**Comment by j0hnsmith** [comment]
@dmcgowan, I'm still seeing this after pushing.

```
$ docker push example.com/foo/bar:master
The push refers to a repository [example.com/foo/bar]
9ce98538809e: Layer already exists 
91a8f3990fa4: Layer already exists 
837094365fb4: Layer already exists 
9708155555f8: Layer already exists 
b91611bea4a8: Layer already exists 
148b5a1af9ed: Layer already exists 
011b303988d2: Layer already exists 
master: digest: sha256:164b5fc83e34c2c1d59a430c7b64ecd010902f13c62ba9dcc50efb771c4060b2 size: 12564
                                                                                                                                                              
$ docker images --digests example.com/foo/bar:master 
REPOSITORY                 TAG           DIGEST              IMAGE ID            CREATED             SIZE
example.com/foo/bar   master              <none>              d594640ae3af        About an hour ago   63.02 MB
                                                                                                                                                              
$ docker images --no-trunc example.com/foo/bar:master
REPOSITORY                         TAG                 IMAGE ID                                                                  CREATED             SIZE
example.com/foo/bar   master              sha256:d594640ae3af27c8552d1274ce766107c3bfbefe9585d42f24f2ca7d2476a6f9   About an hour ago   63.02 MB
                                                                                                                                                              
$ docker version
Client:
 Version:      1.12.2-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   45bed2c
 Built:        Tue Sep 27 23:38:15 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64
```

And it looks like I'm getting two different hashes, `sha256:d594640ae3af27c8552d1274ce766107c3bfbefe9585d42f24f2ca7d2476a6f9` and `sha256:164b5fc83e34c2c1d59a430c7b64ecd010902f13c62ba9dcc50efb771c4060b2`, seems odd?

**Comment by j0hnsmith** [comment]
It seems that the 'image id' shown by `docker images --no-trunc` is not a digest (confirmed in https://github.com/docker/distribution/issues/1662).

```
$ docker images --no-trunc example.com/foo/bar:master
REPOSITORY                         TAG                 IMAGE ID                                                                  CREATED             SIZE
example.com/foo/bar   master              sha256:d594640ae3af27c8552d1274ce766107c3bfbefe9585d42f24f2ca7d2476a6f9   About an hour ago   63.02 MB

$ docker run --rm example.com/foo/bar:master@sha256:d594640ae3af27c8552d1274ce766107c3bfbefe9585d42f24f2ca7d2476a6f9
Unable to find image 'example.com/foo/bar@sha256:d594640ae3af27c8552d1274ce766107c3bfbefe9585d42f24f2ca7d2476a6f9' locally
docker: Error response from daemon: manifest unknown: manifest unknown.
See 'docker run --help'.

$ docker push example.com/foo/bar:master
The push refers to a repository [example.com/foo/bar]
9ce98538809e: Layer already exists 
91a8f3990fa4: Layer already exists 
837094365fb4: Layer already exists 
9708155555f8: Layer already exists 
b91611bea4a8: Layer already exists 
148b5a1af9ed: Layer already exists 
011b303988d2: Layer already exists 
master: digest: sha256:164b5fc83e34c2c1d59a430c7b64ecd010902f13c62ba9dcc50efb771c4060b2 size: 12564

$ docker run --rm example.com/foo/bar:master@sha256:164b5fc83e34c2c1d59a430c7b64ecd010902f13c62ba9dcc50efb771c4060b2
^C⏎ 
```
(the second `docker run ...` worked)

So is there a way to get the _real_ digest for an image that has been pushed already (apart from `docker push ...`)?

WTF: just ran a couple more commands
```
$ docker images --digests quay.io/cerberos/hubnet-frontend:master
REPOSITORY                         TAG                 DIGEST              IMAGE ID            CREATED             SIZE
quay.io/cerberos/hubnet-frontend   master              <none>              d594640ae3af        2 hours ago         63.02 MB
```
This is the command I pasted ^^^, no digest, buuuuuut

```
$ docker images --digests quay.io/cerberos/hubnet-frontend
REPOSITORY                         TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
quay.io/cerberos/hubnet-frontend   master              sha256:164b5fc83e34c2c1d59a430c7b64ecd010902f13c62ba9dcc50efb771c4060b2   d594640ae3af        2 hours ago         63.02 MB
quay.io/cerberos/hubnet-frontend   <none>              sha256:6fd65f7141dc61adeb9f262784b1aca9848866d2d4b68c3a10ecf0aa2d1edef6   1c270a40466d        3 days ago          63.02 MB
quay.io/cerberos/hubnet-frontend   <none>              sha256:0b9e94db5aaedb6f6407778d803e99b0e7dd2e710842611873411717dd51e7b8   c42d40e9c60b        3 days ago          63.02 MB
quay.io/cerberos/hubnet-frontend   <none>              sha256:a5aee68356dba08f0576396d8cbd23cf48630391e00d3197c2b237cbedc8a7a2   998b383b2bcb        2 weeks ago         63.02 MB
quay.io/cerberos/hubnet-frontend   <none>              sha256:076ff9b7dc7cadf2a74d7bf5b7226c0b69ef18e9d29834c2c2e0f3efca019aba   a6df32f2ad19        2 weeks ago         62.08 MB
quay.io/cerberos/hubnet-frontend   <none>              sha256:a8a4411a3f6f89c9215a24adfa5ae3c62d04052c53039fd594002a78118ecf1d   7bc456afeef5        2 weeks ago         62.08 MB
quay.io/cerberos/hubnet-frontend   <none>              sha256:eb448ad5b5d1a6b8d425e90c37056c82c90809ffbf3e6486f601351893fe2785   973e019e1f45        4 weeks ago         429.8 MB
```
I'm going to create a separate issue for digest not shown when image tag specified.

**Comment by dmcgowan** [comment]
@j0hnsmith thanks for creating separate issue. Excluding the digest when listing a specific tag vs including when no tag is given is not intended behavior.

**Comment by j0hnsmith** [comment]
https://github.com/docker/docker/issues/29901
