### ISSUE TITLE
timeouts pulling from official registry

### ISSUE THREAD

**Issue by harmw** [docker/docker#15949]
Hi,

Probably since upgrading to 1.8.1 (plus, I'm currently checking out 1.9.0-dev) I'm having a hard time pulling images.

>DEBU[1725] Calling POST /images/create
>INFO[1725] POST /v1.20/images/create?fromImage=harmw%2Fbla%3A2
>DEBU[1725] Warning: client and server don't have the same version (client: 1.8.1, server: 1.9.0-dev)
>DEBU[1725] Trying to pull harmw/bla from https://registry-1.docker.io v2
>DEBU[1725] Pulling tag from V2 registry: "2"
>DEBU[2054] Error trying v2 registry: Error parsing HTTP response: invalid character '<' looking for beginning of value: "<html><body><h 1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n\n"
>DEBU[2054] Trying to pull harmw/bla from https://index.docker.io v1
>DEBU[2054] hostDir: /etc/docker/certs.d/docker.io
>DEBU[2054] [registry] Calling GET https://index.docker.io/v1/repositories/harmw/bla/images
>DEBU[2054] Not continuing with error: Error: image harmw/bla:1.4 not found

This image is obviously non-existent, but the timing here shows the issue: The pull starts, trying the v2 registry and after a considerable amount of time it errors and pulls from the v1 registry - there it fails right away, as it should. 

Some strace output, didn't find anything easy other then some timeouts which I personally can't interpret.
>5750  clock_gettime(CLOCK_REALTIME, {1441026761, 887174820}) = 0
>5313  <... futex resumed> )             = 0
>5750  futex(0xc2080c27d8, FUTEX_WAKE, 1 <unfinished ...>
>5313  clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
>5750  <... futex resumed> )             = 1
>5316  <... futex resumed> )             = 0
>5313  <... clock_gettime resumed> {12886, 922368654}) = 0
>5750  clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
>5316  open("/proc/stat", O_RDONLY|O_CLOEXEC <unfinished ...>
>5313  clock_gettime(CLOCK_REALTIME,  <unfinished ...>
>5750  <... clock_gettime resumed> {12886, 922422605}) = 0
>5750  futex(0x18ca9b8, FUTEX_WAIT, 0, {0, 998566522} <unfinished ...>
>5316  <... open resumed> )              = 12
>5313  <... clock_gettime resumed> {1441026761, 887313805}) = 0
>5316  read(12,  <unfinished ...>
>5313  select(0, NULL, NULL, NULL, {0, 20} <unfinished ...>
>5316  <... read resumed> "cpu  57050 183 14020 2345721 140"..., 128) = 128
>5316  close(12)                         = 0
>5316  epoll_wait(5, {}, 128, 0)         = 0
>5313  <... select resumed> )            = 0 (Timeout)
>5313  clock_gettime(CLOCK_MONOTONIC,  <unfinished ...>
>5316  futex(0xc2080c27d8, FUTEX_WAIT, 0, NULL <unfinished ...>
>5313  <... clock_gettime resumed> {12886, 922717356}) = 0
>5313  clock_gettime(CLOCK_REALTIME, {1441026761, 887638848}) = 0
>5313  select(0, NULL, NULL, NULL, {0, 20}) = 0 (Timeout)
>5313  clock_gettime(CLOCK_MONOTONIC, {12886, 923052424}) = 0
>5313  futex(0x18caee0, FUTEX_WAIT, 0, {60, 0} <unfinished ...>
>5750  <... futex resumed> )             = -1 ETIMEDOUT (Connection timed out)
>5750  clock_gettime(CLOCK_MONOTONIC, {12887, 921345068}) = 0
>5750  futex(0x18caee0, FUTEX_WAKE, 1)   = 1
>5313  <... futex resumed> )             = 0

Running docker like this:
`./docker-1.9.0-dev -d -D --selinux-enabled --dns-search service.consul --dns 172.19.0.1 --log-level=error --bip=172.19.0.1/24 -s overlay`

What would be the first thing to check?

**Comment by brandocorp** [comment]
I'm currently seeing this same issue on an ubuntu 14.04 VM in AWS. I was trying to pull down the busybox image as a test, but I get the same results when I try the swarm image, as well.

```
$ docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64

$ docker info
Containers: 0
Images: 10
Storage Driver: aufs
 Root Dir: /opt/docker/aufs
 Backing Filesystem: extfs
 Dirs: 10
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-36-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 8
Total Memory: 31.42 GiB
Name: ip-10-202-90-241
ID: FCB3:SQAO:SELU:6M3C:7UX5:XHC5:JMIF:F2ZW:NPCY:RT6F:AKZQ:KZSP
Debug mode (server): true
File Descriptors: 10
Goroutines: 19
System Time: 2015-09-23T23:47:36.190690494Z
EventsListeners: 0
Init SHA1:
Init Path: /usr/bin/docker
Docker Root Dir: /opt/docker
WARNING: No swap limit support

$ uname -a
Linux ip-10-202-90-241 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

## Debug Log

```text
$ /usr/bin/docker daemon --graph=/opt/docker -s aufs -D
DEBU[0000] Registering HEAD, /containers/{name:.*}/archive
DEBU[0000] Registering GET, /containers/{name:.*}/export
DEBU[0000] Registering GET, /containers/{name:.*}/top
DEBU[0000] Registering GET, /events
DEBU[0000] Registering GET, /images/json
DEBU[0000] Registering GET, /images/get
DEBU[0000] Registering GET, /containers/ps
DEBU[0000] Registering GET, /containers/{name:.*}/changes
DEBU[0000] Registering GET, /containers/{name:.*}/attach/ws
DEBU[0000] Registering GET, /exec/{id:.*}/json
DEBU[0000] Registering GET, /containers/{name:.*}/archive
DEBU[0000] Registering GET, /_ping
DEBU[0000] Registering GET, /info
DEBU[0000] Registering GET, /images/{name:.*}/history
DEBU[0000] Registering GET, /images/{name:.*}/json
DEBU[0000] Registering GET, /containers/{name:.*}/stats
DEBU[0000] Registering GET, /version
DEBU[0000] Registering GET, /images/search
DEBU[0000] Registering GET, /containers/json
DEBU[0000] Registering GET, /containers/{name:.*}/json
DEBU[0000] Registering GET, /images/{name:.*}/get
DEBU[0000] Registering GET, /containers/{name:.*}/logs
DEBU[0000] Registering POST, /commit
DEBU[0000] Registering POST, /images/load
DEBU[0000] Registering POST, /containers/{name:.*}/kill
DEBU[0000] Registering POST, /exec/{name:.*}/start
DEBU[0000] Registering POST, /exec/{name:.*}/resize
DEBU[0000] Registering POST, /containers/{name:.*}/rename
DEBU[0000] Registering POST, /auth
DEBU[0000] Registering POST, /containers/{name:.*}/pause
DEBU[0000] Registering POST, /containers/{name:.*}/unpause
DEBU[0000] Registering POST, /containers/{name:.*}/restart
DEBU[0000] Registering POST, /containers/{name:.*}/start
DEBU[0000] Registering POST, /containers/{name:.*}/stop
DEBU[0000] Registering POST, /containers/{name:.*}/resize
DEBU[0000] Registering POST, /images/{name:.*}/tag
DEBU[0000] Registering POST, /images/create
DEBU[0000] Registering POST, /containers/{name:.*}/wait
DEBU[0000] Registering POST, /containers/{name:.*}/attach
DEBU[0000] Registering POST, /containers/{name:.*}/copy
DEBU[0000] Registering POST, /containers/{name:.*}/exec
DEBU[0000] Registering POST, /build
DEBU[0000] Registering POST, /containers/create
DEBU[0000] Registering POST, /images/{name:.*}/push
DEBU[0000] Registering PUT, /containers/{name:.*}/archive
DEBU[0000] Registering DELETE, /containers/{name:.*}
DEBU[0000] Registering DELETE, /images/{name:.*}
DEBU[0000] Registering OPTIONS,
DEBU[0000] [graphdriver] trying provided driver "aufs"
DEBU[0000] Warning: could not change group /var/run/docker.sock to docker: Group docker not found
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
DEBU[0000] Using graph driver aufs
DEBU[0000] Using default logging driver json-file
DEBU[0000] Migrating existing containers
DEBU[0000] Creating images graph
DEBU[0000] Restored 10 elements
DEBU[0000] Reloaded graph with 3 grants expiring at 2017-03-22 19:04:46.713978458 +0000 UTC
DEBU[0000] Creating repository list
INFO[0000] Option DefaultDriver: bridge
INFO[0000] Option DefaultNetwork: bridge
WARN[0000] Running modprobe bridge nf_nat br_netfilter failed with message: modprobe: WARNING: Module br_netfilter not found.
, error: exit status 1
INFO[0000] Firewalld running: false
DEBU[0000] /sbin/iptables, [--wait -t nat -D PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]
DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER]
DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT -m addrtype --dst-type LOCAL -j DOCKER]
DEBU[0000] /sbin/iptables, [--wait -t nat -D PREROUTING]
DEBU[0000] /sbin/iptables, [--wait -t nat -D OUTPUT]
DEBU[0000] /sbin/iptables, [--wait -t nat -F DOCKER]
DEBU[0000] /sbin/iptables, [--wait -t nat -X DOCKER]
DEBU[0000] Failed to Initialize Datastore due to datastore initialization requires a valid configuration. Operating in non-clustered mode
DEBU[0000] /sbin/iptables, [--wait -t nat -C POSTROUTING -s 172.17.42.1/16 ! -o docker0 -j MASQUERADE]
DEBU[0000] /sbin/iptables, [--wait -D FORWARD -i docker0 -o docker0 -j DROP]
DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -i docker0 -o docker0 -j ACCEPT]
DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -i docker0 ! -o docker0 -j ACCEPT]
DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT]
DEBU[0000] /sbin/iptables, [--wait -t nat -n -L DOCKER]
DEBU[0000] /sbin/iptables, [--wait -t nat -N DOCKER]
DEBU[0000] /sbin/iptables, [--wait -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]
DEBU[0000] /sbin/iptables, [--wait -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER]
DEBU[0000] /sbin/iptables, [--wait -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8]
DEBU[0000] /sbin/iptables, [--wait -t nat -A OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8]
DEBU[0000] /sbin/iptables, [--wait -t filter -n -L DOCKER]
DEBU[0000] /sbin/iptables, [--wait -t filter -C FORWARD -o docker0 -j DOCKER]
WARN[0000] Your kernel does not support swap memory limit.
INFO[0000] Daemon has completed initialization
INFO[0000] Docker daemon                                 commit=d12ea79 execdriver=native-0.2 graphdriver=aufs version=1.8.1
DEBU[0003] Calling POST /images/create
INFO[0003] POST /v1.20/images/create?fromImage=busybox%3Alatest
DEBU[0003] Trying to pull busybox from https://registry-1.docker.io v2
DEBU[0004] Fetched 1 base graphs at 2015-09-23 23:37:18.221592096 +0000 UTC
DEBU[0004] Reloaded graph with 3 grants expiring at 2017-03-22 19:04:46.713978458 +0000 UTC
DEBU[0004] Pulling tag from V2 registry: "latest"
DEBU[0404] Error trying v2 registry: Error parsing HTTP response: invalid character '<' looking for beginning of value: "<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n\n"
DEBU[0404] Trying to pull busybox from https://index.docker.io v1
DEBU[0405] Fetched 1 base graphs at 2015-09-23 23:43:59.003733134 +0000 UTC
DEBU[0405] hostDir: /etc/docker/certs.d/docker.io
DEBU[0405] [registry] Calling GET https://index.docker.io/v1/repositories/library/busybox/images
DEBU[0405] Reloaded graph with 3 grants expiring at 2017-03-22 19:04:46.713978458 +0000 UTC
DEBU[0405] Retrieving the tag list
DEBU[0405] Got status code 200 from https://registry-1.docker.io/v1/repositories/library/busybox/tags/latest
DEBU[0405] Registering tags
DEBU[0405] Ancestry: [d7057cb020844f245031d27b76cb18af05db1cc3a96a29fa7777af75f5ac91a3 cfa753dfea5e68a24366dfba16e6edf573daa447abf65bc11619c1a98a3aff54]
DEBU[0620] Calling GET /version
INFO[0620] GET /v1.20/version
DEBU[0622] Calling GET /info
INFO[0622] GET /v1.20/info
```

**Comment by harmw** [comment]
@brandocorp the solution here was lowering MTU to 1500, since per default AWS blocks ICMP.

**Comment by brandocorp** [comment]
@harmw, thanks for the info!

**Comment by thaJeztah** [comment]
Based on the above, it looks like this is resolved, so I'll close this. Feel free to comment if you think I closed this by mistake

**Comment by jamshid** [comment]
Thanks @harmw, running `sudo /sbin/ifconfig eth1 mtu 1500 up` also fixed the problem for me where `docker pull centos:centos7` was hanging, eventually showing the below error. I don't know why my Ubuntu 14 vm running a docker server was configured with mtu 9000 in /etc/network/interfaces, or if lowering it has any side-effects.
```
Error parsing HTTP response: invalid character '<' looking for beginning of value: "<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n\n"
```

**Comment by keviocastro** [comment]
This problem still Occurs to me.
I changed the MTU to 1500 and not solved.
Any suggestion?

docker --version
Docker version 1.10.1, build 9e83765

docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.714 GiB
Name: kevio
ID: E26Z:TZU6:MAIS:RNVO:DLH4:MUKD:H3HQ:PRMR:C4YY:POKF:PQL7:KBZL
WARNING: No swap limit support

uname -a
Linux kevio 4.2.0-27-generic #32-Ubuntu SMP Fri Jan 22 04:49:08 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
ubuntu 15.10

**Comment by hpc-training** [comment]
Had the same problem today with my VirtualBox Ubuntu/Docker-VM. However, the MTU already was 1500. Reducing it to 1000 helped.

**Comment by SiddiquiImran** [comment]
https://github.com/moby/moby/issues/22635#issuecomment-284956961

**Comment by Red-M** [comment]
Please reopen this.
I've had this error on 3 separate systems all installed at different times all with somewhat new versions of docker and none of them are on AWS. Lowering the MTU has worked around this issue but this is ridiculous.
