### ISSUE TITLE
Bash completion syntax error on OSX

### ISSUE THREAD

**Issue by poislagarde** [docker/docker#16326]
I installed docker using [brew](http://brew.sh) and sourced the bash completion script with `. $(brew --prefix)/etc/bash_completion.d/docker` but I get this error:

```
-bash: /usr/local/etc/bash_completion.d/docker: line 142: syntax error near unexpected token `('
-bash: /usr/local/etc/bash_completion.d/docker: line 142: `			@($option_glob) )'
```

**Comment by poislagarde** [comment]
* `docker version`:
```
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   0a8c2e3
 Built:        Sun Sep 13 08:20:28 UTC 2015
 OS/Arch:      darwin/amd64
Get http://%2Fvar%2Frun%2Fdocker.sock/v1.20/version: dial unix /var/run/docker.sock: connect: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
```

* `docker info`:
```
Get http://%2Fvar%2Frun%2Fdocker.sock/v1.20/info: dial unix /var/run/docker.sock: connect: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
```

* `uname -a`:
```
Darwin pol-mac.local 15.0.0 Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64 x86_64
```

This is a physical Macbook Air 2014 notebook

Steps to reproduce the issue:
1. Install docker using brew
2. Souce docker bash completion script from the terminal
3. Syntax error

**Comment by thaJeztah** [comment]
Would you be able to test if the current version on master works for you? There are some issues with completion on OS X, because OS X has an older version OS Bash installed.

https://github.com/docker/docker/blob/master/contrib/completion/bash/docker

(Be sure to keep the one you have currently installed around, because the "master" version may contain parts that rely on options not yet in docker 1.8.2)

/cc @albers

**Comment by poislagarde** [comment]
It's still failing:

```
-bash: /usr/local/etc/bash_completion.d/docker: line 190: syntax error near unexpected token `('
-bash: /usr/local/etc/bash_completion.d/docker: line 190: `			@($option_glob) )'
```

Also note that I tried installing a newer version of bash via brew and the result was the same. According to `$BASH_VERSION` it is `4.3.42(1)-release`.

**Comment by thaJeztah** [comment]
Thanks for testing! I included @albers into this discussion, who's really a magician for this stuff, so Im sure he's able to fix this :+1:

**Comment by albers** [comment]
#dibs

**Comment by albers** [comment]
You get this warning on systems where the extglob shell option is not set.
@poislagarde does this error still happen if you issue `shopt -s extglob` before sourcing the completion script?

**Comment by albers** [comment]
@poislagarde I created a PR which should fix this issue.
Can you please verify whether the problem exists in [this file](https://raw.githubusercontent.com/albers/docker/0a5aac1ff6cbacfeefb34702b4726a4e189b1bb9/contrib/completion/bash/docker)?

**Comment by poislagarde** [comment]
The extglob shell option fixed it! I will add that to my bash profile for the time being.
That newer version works too, wether I have extglob set or not.

Thank you! :+1:

**Comment by calavera** [comment]
Fixed by #16326 :tada:

**Comment by thaJeztah** [comment]
Thanks for reporting @poislagarde, and the very fast fix @albers !

**Comment by albers** [comment]
@poislagarde I still do not understand why you do not have extglob set. 
This is important for me so that I can upgrade my test environment to cover your case.

Can you please tell me what version of bash completion you have installed?
You should find that in the comment at the top of `/etc/bash_completion`.

**Comment by poislagarde** [comment]
@albers I was not using the full-blown bash-completion package, but manually sourcing scripts from my profile. I've never had any issues with other scripts before but I guess I'll just install it to avoid future headaches.

Thank you!

**Comment by albers** [comment]
@poislagarde Well, in this case it's not very surprising that you had issues. Bash completion ensures that the extglob shell option is set.
