### ISSUE TITLE
Creating fail with Could not find container for entity id <id> after upgrading to 1.9.0

### ISSUE THREAD

**Issue by gionn** [docker/docker#17691]
```

Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

Linux gt-xps 3.19.0-31-generic #36~14.04.1-Ubuntu SMP Thu Oct 8 10:21:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Containers: 1
Images: 37
Server Version: 1.9.0
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-31-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 7.372 GiB
Name: gt-xps
ID: 2562:2TQM:TR3I:CDFJ:T6JP:WXBN:AV4F:LZYT:HIAX:ZFYC:MMWD:Q7AN
Username: gionn
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

Before I was using 1.8.3 with aufs storage driver.

```
$ docker run --rm -it --name cloudesire_broker_1 ubuntu
Error response from daemon: Could not find container for entity id 72845af4d9964d42eab55fd84c1a2cc25d7b32b8c587ed47b766d9a7a8fe5396

$ docker inspect cloudesire_broker_1
Error: No such image or container: cloudesire_broker_1
[]

$ docker inspect 72845af4d9964d42eab55fd84c1a2cc25d7b32b8c587ed47b766d9a7a8fe5396
Error: No such image or container: 72845af4d9964d42eab55fd84c1a2cc25d7b32b8c587ed47b766d9a7a8fe5396
[]

$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

First debug happened in compose issue tracker since it appeared related to it: https://github.com/docker/compose/issues/2316

> I've a feeling that has something to do with containers that was existing before the upgrade to 1.9.0 from 1.8.3, with the contextual switch from storage driver aufs to overlay.

**Comment by cpuguy83** [comment]
@gionn Hmm, yes I think this is probably it. Maybe remove all containers, and then remove `/var/lib/docker/linkgraph.db`.
Not sure if this is feasible for your setup.
There's a PR to namepsace these link graphs per graph driver.

**Comment by dnephin** [comment]
There's some relevant discussion here: https://github.com/docker/docker/pull/17389/files#r43595659

**Comment by markmandel** [comment]
I just ran into the same issue, on my local machine.

I tried everything above, and also reinstalled docker - solution for me - start the container with a different `--name` value. YMMV.

**Comment by abhas** [comment]
The only way I could fix this issue was by deleting the contents of `/var/lib/docker/containers` and also deleting the `/var/lib/docker/linkgraph.db` file. Thanks @cpuguy83.

**Comment by jbq** [comment]
Same for me while migrating from `devicemapper` storage  to `overlay`.  I had to manually remove the aforementioned low-level docker files.

**Comment by ruudud** [comment]
Same for me, migrated with a clean cut from aufs to overlay. Had to remove `linkgraph.db` to to be able to start a container with the same name as one I had been using before with aufs.

**Comment by adrienkeendo** [comment]
I've just update docker to 1.9 and I've got the same issue.
Thank @abhas, I've deleted the directory /var/lib/docker/containers and the file /var/lib/docker/linkgraph.db and it worked.

**Comment by naag** [comment]
Same here. It didn't happen for all containers though, in some cases even just one container as affected.

```
$ docker info
Containers: 7
Images: 1834
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1948
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.0-16-generic
Operating System: Ubuntu 15.10
CPUs: 4
Total Memory: 15.56 GiB
Name: phuong-HP-ProBook-6470b
ID: QWGD:PGHS:24JH:Q4D2:UMU3:HICM:TLNV:CEFS:47GM:MHCE:SA5M:GDKW
WARNING: No swap limit support

$ docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:48:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:48:04 UTC 2015
 OS/Arch:      linux/amd64

$ uname -a
Linux phuong-HP-ProBook-6470b 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

The actual error message was `Error response from daemon: Could not find container for entity id b36386384e81a15c8891708502ee40419a312a41dd1db733eb114293572c8541`. Problem was also fixed by deleting `/var/lib/docker/containers/*` and `/var/lib/docker/linkgraph.db`.

**Comment by gionn** [comment]
hey guys, we already had multiple confirmation of this bug, please avoid repeating that you got this bug and you fixed it with the suggested workaround.

Use subscribe button if you want updates.

Cheers

**Comment by zymtx5g79k** [comment]
Всем привет!
__docker version:__
```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
```
__docker info:__
```
Containers: 26
Images: 30
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 82
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-68-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 4
Total Memory: 7.704 GiB
Name: laptop-U36SG
ID: WXB3:ENML:LQFP:XFZB:WSDZ:J2X6:ENDV:P3AT:ZNH3:OJ4R:GOI4:XXSJ
WARNING: No swap limit support
```
__uname -a:__
```
Linux laptop-U36SG 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

__Provide additional environment details (AWS, VirtualBox, physical, etc.):__
На локальной машине. Обновил штатными средствами ubuntu и приехал. Пробовал перегрузиться. Удалять все контейнеры и образы. Не помогло ):

__List the steps to reproduce the issue:__
1. Собрать контейнер. __Dockerfile__: https://gist.github.com/zymtx5g79k/a39e1196d93ae9c4067d
2. Запустить
3.

__Describe the results you received:__
```
Error response from daemon: Could not find container for entity id 92ab1a4d2e7ffb6ff29cefca5ea735387cdf6be8fefa7142c282d41ca7a0eb25
```
__Describe the results you expected:__
```Ожидал увидеть вывод супервизора, работающего в контейнере.```

__Provide additional info you think is important:__
```
Не все образы постигла такая участь. Вот этот контейнер запускается !без проблем Dockerfile: https://gist.github.com/zymtx5g79k/80270f08124e2d461215
```

**Comment by zymtx5g79k** [comment]
Ty @naag
> deleting /var/lib/docker/containers/* and /var/lib/docker/linkgraph.db.
* удалил все контейнеры и образы
* /var/lib/docker/containers/ была пустой
* /var/lib/docker/linkgraph.db удалил руками
* перезапустил службу docker `service docker restart`
* собрал контейнер по новой.

__Заработало!__ (:

**Comment by thaJeztah** [comment]
@zymtx5g79k could you please edit your comments and translate it to English, most people here won't be able to read it otherwise.

**Comment by error10** [comment]
docker version:
Client:
 Version:         1.9.1-fc23
 API version:     1.21
 Package version: docker-1.9.1-2.git78bc3ea.fc23.x86_64
 Go version:      go1.5.1
 Git commit:      f7c1d52-dirty
 Built:           Fri Nov 20 21:07:14 UTC 2015
 OS/Arch:         linux/amd64

Server:
 Version:         1.9.1-fc23
 API version:     1.21
 Package version: docker-1.9.1-2.git78bc3ea.fc23.x86_64
 Go version:      go1.5.1
 Git commit:      f7c1d52-dirty
 Built:           Fri Nov 20 21:07:14 UTC 2015
 OS/Arch:         linux/amd64

docker info:
Containers: 9
Images: 123
Server Version: 1.9.1-fc23
Storage Driver: devicemapper
 Pool Name: docker-253:1-573125-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/docker-volumes/docker-data
 Metadata file: /dev/docker-volumes/docker-meta
 Data Space Used: 2.518 GB
 Data Space Total: 42.9 GB
 Data Space Available: 40.38 GB
 Metadata Space Used: 5.562 MB
 Metadata Space Total: 46.14 MB
 Metadata Space Available: 40.57 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.109 (2015-09-22)
Execution Driver: native-0.2
Logging Driver: journald
Kernel Version: 4.2.6-300.fc23.x86_64
Operating System: Fedora 23 (Twenty Three)
CPUs: 4
Total Memory: 3.86 GiB
Name: docker2..com
ID: JG2X:PHQM:DX2R:IYCR:UREV:3AWO:O5DC:3NKY:7YTW:26V2:NNLY:HABR
uname -a:

Provide additional environment details (AWS, VirtualBox, physical, etc.):
KVM virtual machine

List the steps to reproduce the issue:
1. On Fedora 23, updated docker-1.8.2 to docker-1.9.1 with dnf update
2. Restarted Docker

Describe the results you received:
Nov 25 23:57:18 docker2..com docker[780]: time="2015-11-25T23:57:18.055177233Z" level=error msg="HTTP Error" err="Could not find container for entity id 985b3b0c08cd6b139c5029cb486eab28aca9fb8ab73992380285275e9395bc23" statusCode=500

Describe the results you expected:
Containers starting normally

Provide additional info you think is important:
**We did not change the storage driver during this update.** It remained devicemapper, with the same backing store. The workaround of deleting containers and linkgraph.db restored normal operation.

**Comment by ikor** [comment]
For anyone who is still encountering this issue, this is a workaround:
* Remove **rm -f /var/lib/linkpgraph.db** (or if you modified **graphdb=/opt/docker** : **rm -rf /opt/docker/linkgraph.db**)
* Remove **rm -rf /var/lib/containers/**
* Restart docker daemon :  (for Ubuntu) sudo service docker restart

**Comment by cturra** [comment]
i too have run into this across a small fleet of docker host i run. the instructions noted above by @ikor got us back on track, but to make sure this doesn't bite us again, i have rolled back docker-engine on these nodes to 1.8.3.

**Comment by areidyOTH** [comment]
This problem occurs when the tables *'edge'* and *'entity'* in the SQLite database **/var/lib/linkgraph.db** contain records for a container name already but **/var/lib/containers** has no data for the corresponding containerid. I think it's caused by aee54863741fc3f012c423d1a445d1a6b687966a which was added to 1.9.0 to fix #17389 

Previously, if you tried to start a container that had records in linkgraph.db but there was no data in **/var/lib/containers** then the records would be deleted from the database. Now this error occurs instead.

I can't work out what causes the mismatch between the records in linkgraph.db and /var/lib/containers - abnormal termination maybe?

The fixes are:
- downgrade to 1.8.3, or
- manually delete the records in linkgraph.db every time the error occurs

**Comment by thaJeztah** [comment]
ping @tonistiigi ^^

**Comment by iwidanalage** [comment]
We hit the same issue with 1.9.0. But deleting all containers was not an option for us. So did a  very hacky workaround by going in to modifying the record on the edge table using sqllite cli. 

```
 sqlite3 linkgraph.db 

update edge set name='some-random-container-name' where name='failing-container-name';

```

Hope this helps.

**Comment by nazar-pc** [comment]
Same here on Docker 1.9.1, BTRFS, Ubuntu 16.04, Kernel 4.4-rc4
Happened after machine stuck (I have a lot of experimental software here, not sure why it happened, this is for the first time).
After reboot one of containers doesn't start using Docker Compose, while other even from the same image starting fine.
I'm removing all containers & volumes and it fails when I want to start the same container with Docker Compose again.
I do have directory with such ID under `/var/lib/docker/btrfs/subvolumes` and `/var/lib/docker/containers`, but one under `/var/lib/docker/containers` is completely empty. Also, container is present in `/var/lib/docker/linkgraph.db` in both tables, but not visible in `docker ps -a`.
After this:
```
sudo rmdir /var/lib/docker/containers/5d85dd4a476f7c05a667676bcd53ad7cd8e1653db0f4c1288257759eb39ac142
sudo btrfs subvolume delete /var/lib/docker/btrfs/subvolumes/5d85dd4a476f7c05a667676bcd53ad7cd8e1653db0f4c1288257759eb39ac142
sudo btrfs subvolume delete /var/lib/docker/btrfs/subvolumes/5d85dd4a476f7c05a667676bcd53ad7cd8e1653db0f4c1288257759eb39ac142-init
```
Error still happens, so there is a need for some mechanism to handle empty directory under `/var/lib/docker/containers/` nicely and normalize `/var/lib/docker/linkgraph.db`

**Comment by TJC** [comment]
We've been seeing this occur on some production machines on docker version 1.9.1-0~trusty. But luckily, not all machines.

Pretty disappointing to have services going down due to this bug.. We skipped 1.9.0 and went straight to 1.9.1, but I don't think that's relevant.

**Comment by niccokunzmann** [comment]
Having this in 1.9.1

    Client:
     Version:      1.9.1
     API version:  1.21
     Go version:   go1.4.2
     Git commit:   a34a1d5
     Built:        Fri Nov 20 13:20:08 UTC 2015
     OS/Arch:      linux/amd64

    Server:
     Version:      1.9.1
     API version:  1.21
     Go version:   go1.4.2
     Git commit:   a34a1d5
     Built:        Fri Nov 20 13:20:08 UTC 2015
     OS/Arch:      linux/amd64


    Error response from daemon: Could not find container for entity id 33f6f30a91eb31a86e9c715a1fba4cc28c8031ab62826d93c799e3849c341d26

When removing the `--name` parameter for `docker run`, it works.

**Comment by dennybaa** [comment]
+1 recently run the same ugly issue. I've deleted all containers, images partly and anyway(

**Comment by kolis** [comment]
Same problem. Was able to solve it by removing `/var/lib/docker/containers` and `/var/lib/docker/linkgraph.db` and then restarting the docker-machine vm

**Comment by mikeatlas** [comment]
Encountered same issue here while switching kernel versions from 3.13.76 (avoiding the buggy AUFS kernel issue #18180) to 3.19 in order to use overlayfs (development box only)... able to work around the problem by removing `/var/lib/docker/containers` and `/var/lib/docker/linkgraph.db` and then restarting the docker daemon (in my case, with the storage driver explicitly set to overlay):

```
$ sudo rm -rf /var/lib/docker/containers
$ sudo rm /var/lib/docker/linkgraph.db
$ sudo service docker restart
$ docker info
Containers: 6
Images: 141
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-47-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 2
Total Memory: 7.774 GiB
```

After rebuilding my docker-composed images and projects, all working again (although you tend to forget how many layers need to be re-downloaded and rebuilt in situations like this... a lot of finger tapping)...

**Comment by raimille1** [comment]
For people using docker in more of a production-like environment and don't want to rm the world, I just did this and it worked:

`sudo sqlite3 /var/lib/docker/linkgraph.db`
`delete from edge where entity_id = '<conflicting-entity-id-sha-1>';`
`delete from entity where id = '<conflicting-entity-id-sha-1>';`

Where <conflicting-entity-id-sha-1> is the entity id causing you trouble like: 33f6f30a91eb31a86e9c715a1fba4cc28c8031ab62826d93c799e3849c341d26

**Comment by cpuguy83** [comment]
All, this is fixed in 1.10 as we no longer use this sqlite db.

**Comment by Cohedrin** [comment]
Still having this happen, albeit more rarely, on 1.10. Is there any information I could give that could help debug this? @cpuguy83 

Basic information:
`docker info`
```
Containers: 92
 Running: 91
 Paused: 0
 Stopped: 1
Images: 172
Server Version: 1.10.0
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-2.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 78.64 GiB
Name: arizona5.kickback.gs.securedservers.com
ID: 4UIZ:P5HD:NPGR:OTRS:SEIX:KYXN:SMXA:3ZTT:OSYK:2GA2:JLZG:MO3F
Username: trianglegs
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

error: 
```
'Conflict. The name "/server-1454829848" is already in use by container 3992d274d9f7673490606a245cc4145481c54bcf21d37258009806b453405441. You have to remove (or rename) that container to be able to reuse that name.
```

**Comment by cpuguy83** [comment]
@Cohedrin this is not the same issue.
Please open a new issue with details about how to reproduce.

**Comment by Cohedrin** [comment]
will do

**Comment by estevaoam** [comment]
It's impressive how every time docker gets updated, it solves an issue and creates ten more. 
It's a +1.0 tool that feels like beta. Sad.

I got this bug while trying to switch over to overlayfs, because aufs was taking so much space that my 500GB server got at a point that I couldn't do a simple `ls`.

**Comment by cpuguy83** [comment]
@estevaoam As you can see this issue is resolved.

**Comment by mikeatlas** [comment]
@estevaoam at least in terms of semantic versioning, the major/minor/build version number not imply that any product is bug-free... particularly free, OSS ones. Its indeed rapidly evolving at an insane pace; if you need stability in your functionality, lock down a working version for your environment, or paid support solutions?

**Comment by thaJeztah** [comment]
Thanks @mikeatlas :heart:

**Comment by mikeatlas** [comment]
Welcome @thaJeztah.... but @estevaoam's perspective is definitely not invalid either; many people have to decide whether or not some technology is mature enough for wide-scale adoption into organizations; Docker's pace (evolution, I suppose: 1 step forward, 3 new bugs backward) is indeed enough of a frightening prospect to sell as a viable solution if his/her task is to evaluate the readiness of using it as a reliable tool (or not, perhaps in his case).

**Comment by mikeatlas** [comment]
Anyway that's kinda OT from the OP, but it does underscore perhaps a need for more comprehensive migration testing even for minor releases. I do believe Canonical just bumped the apt package up to 1.10 and as such many people automatically got upgraded and expect a minor version (according to semver rules anways) to not introduce any breaking changes (bugs don't count as breaking changes though!)

**Comment by estevaoam** [comment]
@mikeatlas thank you for your polite answer. Although my message could be a little bit harsh, it was because the tiredness of issues Docker-related in my environment.

Don't get me wrong, Docker made our application deployment process and management a gazillion times easier, but it seriously lack a more mature version where I could rely to run in production. 

I actually use Docker in production for multiple projects, and it works well in a very basic configuration. My suggestion would be in maintaining a LTS version, focusing in more stability than new features. As Docker is a project with several years of development, we should have a production-ready and stable version, which I didn't found since the beginning.

About my size issue, it was some issue with device mapper, aufs and volumes not being deleted correctly. Now that we switched over to overlayfs I ran in this current issue, that @cpuguy83 said is solved in 1.10.

But I'm afraid to update, as I saw many issues opened on this repository addressing CPU-related issues. I don't want to upgrade and get other issues which I'll have to waste time trying to figure out the solution.

Thanks again for taking the time to read my comment and trying to understand my point.

**Comment by mikeatlas** [comment]
@estevaoam @thaJeztah one of my favorite quotes ever, from a joke Twitter (HorseJS):
["open source is letting people down that you’ve never met"](https://twitter.com/horse_js/status/584893061085274113 )

**Comment by thaJeztah** [comment]
> I actually use Docker in production for multiple projects, and it works well in a very basic configuration. My suggestion would be in maintaining a LTS version, focusing in more stability than new features. As Docker is a project with several years of development, we should have a production-ready and stable version, which I didn't found since the beginning.

Docker, Inc. offers a commercially supported version of docker ("Docker CS"), https://www.docker.com/products/overview, that you may be interested in.

**Comment by Yajo** [comment]
No solution worked for me, and 1.10 is not packaged yet for Fedora. I had to:

```
# rm -Rf /var/lib/docker/*
# lvm lvremove system/docker-pool
# systemctl restart docker-storage-setup.service docker.service
```

And wait for all to be downloaded and built again. :cry:

**Comment by thaJeztah** [comment]
@Yajo the official docker packages for Fedora have 1.10.3; https://docs.docker.com/engine/installation/linux/fedora/

**Comment by grzegorz-dubicki** [comment]
For me a simple restart of docker service helped.
