### ISSUE TITLE
Installing docker on a system with 64-bit processor but 32bit ubuntu 14.04.

### ISSUE THREAD

**Issue by jojkaart** [docker/docker#17845]
I'll start from the conclusion. If you have 64-bit CPU and 32bit Ubuntu 14.04 installed, it's possible to run docker without reinstalling everything. However, this currently requires manual dissection of the debian package and some modification of it's control file to get it to install.

If changes, similar to the ones I made to the control file were introduced to the docker debian package definition, It'd be relatively easy to make it work on 32-bit ubuntu when you have 64-bit processor. The changes I made are a little crude and I wouldn't suggest them as is, but I'm pretty sure there's someone who can easily refine them enough so they could be incorporated into the official package.

Please modify the official docker-engine package so that it can be installed on a 32-bit Ubuntu system with 64-bit kernel plus 64-bit libraries with minimum fuss. The changes needed are very small.

Here are the steps I needed to make:
1. Activate amd64 architecture for dpkg.
    `sudo dpkg --add-architecture amd64`
    `sudo apt-get update`
2. Install amd64 kernel.
    `sudo apt-get install linux-generic-lts-trusty:amd64`
3. In case you have any DKMS compiled display drivers installed, it's a good idea to uninstall them for now. Leaving them might prevent X from starting properly. I have not verified if DKMS is still able to build them.
4. Reboot (with the new kernel that was just installed)
5. Set up docker repositories by invoking the official install script. It'll fail, but this step is still needed. If some cosmetic fixes were made to the official package, this would be the last step.
    `wget -qO- https://get.docker.com/ | sh`
6. Install amd64 versions of the libraries needed for docker.
    `sudo apt-get install libapparmor1:amd64 libc6:amd64 libdevmapper1.02.1:amd64`
7. Fetch the package for docker-engine.
    `apt-get download docker-engine`
8. Unpack the .deb
    `mkdir docker-package`
    `cd docker-package`
    `ar xv ../docker-engine_1.9.0-0~trusty_amd64.deb`
9. The directory will now contain a few files. Let's unpack control.tar.gz too.
    `mkdir control`
    `cd control`
    `tar zxvf ../control.tar.gz`
10. Next we need to edit the file named control. It contains a line that begins with Depends: We need to modify it so it will accept i386 versions of several important packages. The original line looked like this:
    `Depends: iptables, init-system-helpers (>= 1.13~), sysv-rc (>= 2.88dsf-24) | file-rc (>= 0.8.16), perl, libapparmor1 (>= 2.6~devel), libc6 (>= 2.14), libdevmapper1.02.1 (>= 2:1.02.63)`
    I added :i386 after every package name that didn't begin with lib. This is the result:
    `Depends: iptables:i386, init-system-helpers:i386 (>= 1.13~), sysv-rc:i386 (>= 2.88dsf-24) | file-rc:i386 (>= 0.8.16), perl:i386, libapparmor1 (>= 2.6~devel), libc6 (>= 2.14), libdevmapper1.02.1 (>= 2:1.02.63)`
11. Now we need to repackage the .deb and install it. Here're the commands I used.
    `rm ../control.tar.gz`
    `tar zcvf ../control.tar.gz conffiles control md5sums postinst postrm preinst prerm`
    `cd ..`
    `ar rv ../docker-fixed.deb debian-binary control.tar.gz data.tar.xz _gpgbuilder`
    `cd ..`
12. Now we have docker-fixed.deb and all that's left is to install it.
    `dpkg -i docker-fixed.deb`
13. Now try to see if docker works
    `docker run hello-world`

**Comment by exhuma** [comment]
In step 2, you install a 64bit kernel, and then you say to reboot. Does that mean to boot into that new kernel? Won't this cause trouble further down the line? Using a 64bit kernel on an otherwise 32bit system?

**Comment by jojkaart** [comment]
At least I'm not aware of any trouble with that. The system I did those steps for has been running without any issues for the last 28 days.

**Comment by yanndinendal** [comment]
@jojkaart: thanks for the instructions! But I'm stuck at the last step (` dpkg -i docker-fixed.deb`):

``` bash
 $ sudo dpkg -i docker-fixed.deb
(Lecture de la base de données... 673400 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de docker-fixed.deb ...
Dépaquetage de docker-engine (1.9.1-0~vivid) sur (1.9.1-0~vivid) ...
Paramétrage de docker-engine (1.9.1-0~vivid) ...
Job for docker.service failed. See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
dpkg: erreur de traitement du paquet docker-engine (--install) :
 le sous-processus script post-installation installé a retourné une erreur de sortie d'état 1
Traitement des actions différées (« triggers ») pour ureadahead (0.100.0-19) ...
Traitement des actions différées (« triggers ») pour systemd (219-7ubuntu6) ...
Traitement des actions différées (« triggers ») pour man-db (2.7.0.2-5) ...
Des erreurs ont été rencontrées pendant l'exécution :
 docker-engine
```

``` bash
$ systemctl status docker.service -l
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since jeu. 2016-01-28 12:31:21 CET; 54s ago
     Docs: https://docs.docker.com
 Main PID: 11852 (code=exited, status=203/EXEC)

janv. 28 12:31:21 whimsical-wombat systemd[1]: Starting Docker Application Container Engine...
janv. 28 12:31:21 whimsical-wombat systemd[11852]: Failed at step EXEC spawning /usr/bin/docker: Exec format error
janv. 28 12:31:21 whimsical-wombat systemd[1]: docker.service: main process exited, code=exited, status=203/EXEC
janv. 28 12:31:21 whimsical-wombat systemd[1]: Failed to start Docker Application Container Engine.
janv. 28 12:31:21 whimsical-wombat systemd[1]: Unit docker.service entered failed state.
janv. 28 12:31:21 whimsical-wombat systemd[1]: docker.service failed.
```

**Comment by jojkaart** [comment]
Please make sure you're running the 64-bit kernel you installed in step 2. You can see your kernel version and architecture with the command "uname -a". There should be x86_64 somewhere on the line if you're running 64-bit kernel. If it says i386, you're still running 32-bit kernel.

**Comment by yanndinendal** [comment]
Thanks, will try to reboot again. :)

``` bash
$ uname -a
Linux whimsical-wombat 3.13.0-35-generic #62-Ubuntu SMP Fri Aug 15 01:58:01 UTC 2014 i686 i686 i686 GNU/Linux
```

**Comment by yanndinendal** [comment]
Thanks, it works, now. I redid the following steps too. :)

``` bash
$ docker --version
Docker version 1.9.1, build a34a1d5

$ ps aux | grep docker
root      2484  2.0  0.1 366928 32612 ?        Ssl  21:07   0:00 /usr/bin/docker daemon -H fd://

$ docker run hello-world
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

$ docker-compose run ...
ERROR: Couldn't connect to Docker daemon at http://localhost:4243 - is it running?
```

Well... I guess I will debug it later. But thanks for the solution. :)

**Comment by yanndinendal** [comment]
> 5. Set up docker repositories by invoking the official install script. It'll fail, but this step is still needed. If some cosmetic fixes were made to the official package, this would be the last step.  
> `wget -qO- https://get.docker.com/ | sh`

Can you share the modifications needed? You could post the modified script, so people would just need to run it locally instead of `wget`-ing it. :)

**Comment by thaJeztah** [comment]
Looks like this issue is resolved, so I'll close it, but feel free to comment here after I've closed

**Comment by jojkaart** [comment]
This issue isn't really resolved unless the official docker package gets the simple modifications I've detailed here. Today's problem solving was for someone attempting to do the steps manually. Not the main point of this ticket.

yanndinendal, the modifications needed are all described in the first post, which you apparently were following. The docker install script doesn't need any modifications. Just the .deb needs them. Of course, it also requires the 64-bit kernel installed first, which I don't think is a good idea to script.
