### ISSUE TITLE
dnf [install|reinstall|remove|update] docker takes to much time with fedora 23

### ISSUE THREAD

**Issue by aanm** [docker/docker#18316]
Hey every time I get a new update for docker,let's say from `1.9.0` -> `1.9.1` the installation takes to much time and I'm able to see that it's being caused by `restorecon` when is trying to install/remove/update `docker-engine-selinux`.

**Comment by unclejack** [comment]
@vbatts Do you happen to have an idea about this? Have you run into something like this? I know you're using Fedora and thought you could comment or ping someone who might have seen this.

**Comment by vbatts** [comment]
ping @lsm5 @rhatdan

**Comment by aanm** [comment]
I've been thinking about it... I *think* it might be my `/var/lib/docker` size. If it is big, `restorecon` takes more time, but still, is there something to prevent this? (Besides cleaning all images and containers before upgrading docker...)
```
[aanm@aanm-MBP ~]$ sudo du -ch /var/lib/docker/ --max-depth=0
17G     /var/lib/docker/
17G     total
[aanm@aanm-MBP ~]$ docker info 
Containers: 0
Images: 456
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.3.3-300.fc23.x86_64
Operating System: Fedora 23 (Twenty Three)
CPUs: 8
Total Memory: 15.58 GiB
Name: aanm-MBP
ID: L3I2:XPAF:HYX3:TFTI:RVWP:USWP:2ZTD:PA6M:22DR:UFUA:I7QM:GMMW
Username: aanm
Registry: https://index.docker.io/v1/
```

**Comment by rhatdan** [comment]
restorecon/setfiles is attempting to run through /var/lib/docker, which must be huge on your system.  For some reason it thinks /var/lib/docker has changes its labeling.

docker-selinux and docker used to hard code the restorecon /var/lib/docker, but that should not be happening any longer.

@lsm5 We did remove this correct?

**Comment by aanm** [comment]
@rhatdan I don't think 17G huge :-(

**Comment by kifj** [comment]
Takes a very long time for me too, when installing docker-engine-selinux on a fresh VM with low memory footprint; its a fresh install install of fedora 23 netinstall, so /var/lib/docker is empty (more or less)

**Comment by rhatdan** [comment]
Actually it is not size but the number of inodes.  

docker-engine-selinux probably does not have the fix.   Not under my control and not something I support.

Postinstall should not be doing 
```
restorecon -R -v /var/lib/docker
```

This was removed from the distros version, I believe.  docker-selinux.

**Comment by cfstras** [comment]
Same problem on CentOS 7, my /var/lib/docker is a BTRFS running on a spinning harddrive. Restorecon is called whenever I update docker, and takes a few _hours_ to finish. Is this really necessary?

**Comment by rhatdan** [comment]
The newer docker-selinux package no longer does this, but I am not sure we have shipped this to RHEL/Centos yet.  What docker-selinux package are you using?

**Comment by aanm** [comment]
I just update to docker-engine-selinux-1.10.1-1.fc23 and I'm still 
seeing this problem.

**Comment by rhatdan** [comment]
Well I am talking about the Centos/RHEL/Fedora versions of docker and docker-selinux.  I am not sure if Docker Inc grabbed the latest docker-selinux.spec file that fix this issue.

**Comment by aanm** [comment]
@rhatdan yeah but the version I talk about was from the fedora 23 docker repos ;-)

**Comment by cfstras** [comment]
On CentOS 7.2.1511
```
$ yum list installed | grep docker
docker-engine.x86_64                   1.10.0-1.el7.centos             @dockerrepo
docker-engine-selinux.noarch           1.10.0-1.el7.centos             @dockerrepo
docker-engine-selinux.noarch           1.10.1-1.el7.centos             installed
```

Wait, what? Does that mean 1.10.1 got removed from dockerrepo but was available for a short time?

@rhatdan But I am definitely using something >= 1.10, as it seems.

**Comment by thaJeztah** [comment]
@rhatdan which pull request is that fix in?

**Comment by rhatdan** [comment]
docker-engine* does not come from Fedora it is only available directly from Docker.  The packages in Fedora are docker and docker-selinux.

@thaJeztah We have the fixes in the Fedora/RHEL docker.spec file but never put them into docker-selinux.spec.

**Comment by rhatdan** [comment]
Here is the patch.

http://paste.fedoraproject.org/322878/45554763

**Comment by thaJeztah** [comment]
@rhatdan if you think this needs a fix in the `docker-engine-..` package would you be interesting in opening a PR for the docker repository?

**Comment by rhatdan** [comment]
Could you give me a link where this thing lives.

**Comment by thaJeztah** [comment]
Hm, I think that must be here; https://github.com/docker/docker/blob/3720fbfb35b2f8173b47c0a381cb0bdf09ae1a20/hack/make/.build-rpm/docker-engine-selinux.spec

**Comment by rhatdan** [comment]
https://github.com/docker/docker/pull/20332

**Comment by thaJeztah** [comment]
This resolved by https://github.com/docker/docker/issues/20353, so closing, thanks @rhatdan

**Comment by aanm** [comment]
@thaJeztah Still having this problem with `docker-engine-selinux-1.10.2-1.fc23.noarch`

**Comment by thaJeztah** [comment]
@aanm hm... looks like it didn't end up in the 1.10.2 release (I don't remember; it may have been discussed, but not included, because it's not a regression in 1.10).

**Comment by aanm** [comment]
@thaJeztah Still having this problem with `docker-engine-selinux-1.10.3-1.fc23.noarch`. Took around 6/8 minutes.

**Comment by aanm** [comment]
@thaJeztah I confirm the problem is solved. Thanks for the support ;-)

**Comment by thaJeztah** [comment]
@aanm great! thanks for the update
