### ISSUE TITLE
Overlay network doesn't work with multiple daemons in the same host

### ISSUE THREAD

**Issue by umitanuki** [docker/docker#20223]
I am running two docker daemons and each of them is configured to use the same etcd instance.

Now, I create an overlay network using one of the daemons and launch a container on the subnet from each daemon, it fails in the second one saying "file already exists".

Apparently, docker creates /var/run/netns/<something> for the subnet, thinking it has exclusive access to it, but actually not in this multi-daemon case.  Is there any workaround or future improvement on this issue?

Docker version 1.9 on Ubuntu 14.04 kernel 3.19

**Comment by cpuguy83** [comment]
Multiple daemons on a host is not supported (except via docker-ception).
There are lots of globals at play here (iptables, as an example).

**Comment by umitanuki** [comment]
Ok, that's a shame.  We've been running multiple daemons successfully so far by disabling iptables (and maintaining masquerade separately), until we started looking into the overlay network.  It would have many use cases with multiple daemons.

**Comment by umitanuki** [comment]
Described a bit here http://blog.alpaca.ai/run-multiple-docker-daemons-with-net-container/

**Comment by cpuguy83** [comment]
The articles concept of `docker in docker` is wrong.
`docker in docker` is for running a docker daemon inside a container.
You can spin up as many daemons as you like, no hacking around.

Also, the problems mentioned are resolved by following good practices (like version tagging images).
Tagging an image is not solved by multiple daemons unless you only ever use a single host for everything.

**Comment by umitanuki** [comment]
Those are true, fair enough, but I still have problems around container name conflict and human mistakes to delete someone else's containers/images.  Sure they can be worked around again, but it's definitely better if we had support from docker side.

**Comment by cpuguy83** [comment]
@umitanuki You may want to look at something like UCP, which provides authorization out of the box.

**Comment by umitanuki** [comment]
Without having much idea of UCP, I'm not sure how it solves my problem (UCP looks like commercial GUI on top of OSS, typical OSS business model, but I'm looking for something in CLI without commercial stuff).  It's just a shame because the Engine is very close to support it "out of box" with a few more step.

BTW, looks like it's not only me.
https://forums.docker.com/t/share-docker-between-users/5728

**Comment by cpuguy83** [comment]
@umitanuki UCP supports the CLI too.

But in any case, engine supports an authorization plugin API which you can build your own authz scheme for to protect against these issues as well.
Multiple daemons is not a good protection for this and will not likely ever be explicitly supported.

**Comment by umitanuki** [comment]
One of the potential benefits I can think of by having multiple daemons on a host is: you can test machine failure or docker daemon failure in one host.  And it's not one machine failure out of two, but typically you may want to have 3 or 5 nodes to test the quorum-base coordination.  You need that many machines to test such scenario today (I agree it's far better than yesterday where docker wasn't there, but still)

**Comment by umitanuki** [comment]
Bottom line, I would suggest to explicitly state it somewhere in the doc, unless I missed it, rather than not explicitly support it.

**Comment by cpuguy83** [comment]
@umitanuki The scenario you mentioned can be handled by docker-in-docker.

**Comment by umitanuki** [comment]
I'm not sure how docker-in-docker can handle the scenario... sure you can run multiple dockers but you need many hacks to mimic the real environment.  In short, docker-in-docker sounds hackier than running multiple ones flatly, and it sounds odd to me docker-in-docker is supported and multiple daemon is not.

**Comment by cpuguy83** [comment]
@umitanuki docker-in-docker is supported because each docker daemon is segregated into it's own namespaces (because it's in a container) and can run naturally without bumping into the other daemons.
It has it's own iptables, it's own filesystem, networking, etc.
This should be easier to mimick real-life than hacking a host to support multiple daemons.

**Comment by umitanuki** [comment]
@cpuguy83 Having a second look at docker-in-docker, it actually looks, *except* it uses vfs.  Is there any way to use device mapper?

**Comment by umitanuki** [comment]
Sorry for noise.  It seems aufs works in docker-in-docker.

**Comment by cpuguy83** [comment]
Yes, everything should work, you'll want to make sure you put the docker storage dir in a volume though... so `-v /var/lib/docker` should suffice.

**Comment by umitanuki** [comment]
I'm a bit confused with overlay network now... Should it also work with dind?

**Comment by cpuguy83** [comment]
Yes.

**Comment by umitanuki** [comment]
Still not sure if it's true...  The inner daemon has to be given the vxlan address, but it's not reachable from another host because the address has to be of the outer daemon.  I tried even ip alias+DNAT to forward packets from host to the outer daemon, but the inner daemon says "initializing serf instance failed: failed to create cluster node: Failed to start TCP listener. Err: listen tcp 10.122.147.200:7946: bind: cannot assign requested address" since this ip is aliased on the host, not on the outer daemon.
