### ISSUE TITLE
lsetxattr /dev/mqueue operation not permitted when using docker userns with selinux-enabled

### ISSUE THREAD

**Issue by thtanaka** [docker/docker#20798]
Output of `docker version`:
```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   e0e49ff
 Built:        Tue Feb 23 06:11:53 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   e0e49ff
 Built:        Tue Feb 23 06:11:53 2016
 OS/Arch:      linux/amd64
```

Output of `docker info`:

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.10.2
Storage Driver: btrfs
 Build Version: Btrfs v3.19.1
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 4.1.12-32.el7uek.x86_64
Operating System: Oracle Linux Server 7.2
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 47.16 GiB

```

Output of /etc/subuid and /etc/subgid:
```
/etc/subuid
dockremap:100000:65536
/etc/subgid
dockremap:100000:65536
```

List the steps to reproduce the issue:
1. Run the docker daemon with --selinux-enabled --userns-remap=default 
2. docker run -it oraclelinux:7.2 bash

Describe the results you received:
```
Timestamp: 2016-02-29 21:24:14.706357216 -0500 EST
Code: System error

Message: operation not permitted

Frames:
---
0: setupRootfs
Package: github.com/opencontainers/runc/libcontainer
File: rootfs_linux.go@40
---
1: Init
Package: github.com/opencontainers/runc/libcontainer.(*linuxStandardInit)
File: standard_init_linux.go@57
---
2: StartInitialization
Package: github.com/opencontainers/runc/libcontainer.(*LinuxFactory)
File: factory_linux.go@240
---
3: initializer
Package: github.com/docker/docker/daemon/execdriver/native
File: init.go@35
---
4: Init
Package: github.com/docker/docker/pkg/reexec
File: reexec.go@26
---
5: main
Package: main
File: docker.go@18
---
6: main
Package: runtime
File: proc.go@111
---
7: goexit
Package: runtime
File: asm_amd64.s@1721
docker: Error response from daemon: Cannot start container 2b45ea01fc0f0b1ff5b2caffc5183d1379506a401577db0494f2ed3837cc9947: [9] System error: operation not permitted
```
Describe the results you expected:
Container should start successfully.

Provide additional info you think is important:
This is happening when we are trying to setFileLabel on /dev/mqueue in mountToRootfs on file vendor/src/github.com/opencontainers/runc/libcontainer/rootfs_linux.go
```
 97 func mountToRootfs(m *configs.Mount, rootfs, mountLabel string) error {
...
112         case "mqueue":
113                 if err := os.MkdirAll(dest, 0755); err != nil {
114                         return err
115                 }
116                 if err := mountPropagate(m, rootfs, mountLabel); err != nil {
117                         // older kernels do not support labeling of /dev/mqueue
118                         if err := mountPropagate(m, rootfs, ""); err != nil {
119                                 return err
120                         }
121                 }
122                 return label.SetFileLabel(dest, mountLabel)
...
```
Stracing the docker daemon narrowed it down to the following:
```
...
9311  lsetxattr("/var/lib/docker/100000.100000/btrfs/subvolumes/bf3a1a7300fbb3bab5ac89f982cdf733e20a1525c4b5005beef93fe203ec6942-init/usr/lib/systemd/system/sysinit.target.wants/dev-mqueue.mount", "security.selinux", "system_u:object_r:svirt_sandbox_file_t:s0:c232,c472", 51, 0) = 0
9621  lsetxattr("/var/lib/docker/100000.100000/btrfs/subvolumes/bf3a1a7300fbb3bab5ac89f982cdf733e20a1525c4b5005beef93fe203ec6942/dev/mqueue", "security.selinux", "system_u:object_r:svirt_sandbox_file_t:s0:c232,c472", 51, 0) = -1 EPERM (Operation not permitted)
...
```
Narrow it down further by tracing the linux kernel:

we seem to fail at the following function at fs/inode.c:
```
bool inode_owner_or_capable(const struct inode *inode)
{
        struct user_namespace *ns;

        if (uid_eq(current_fsuid(), inode->i_uid))
                return true;

        ns = current_user_ns();
        if (ns_capable(ns, CAP_FOWNER) && kuid_has_mapping(ns, inode->i_uid))
                return true;
        return false;
}
```
and kuid_has_mapping returns FALSE that is because inode->i_uid = 0

userns is configured and compiled in the kernel:
```
# grep CONFIG_USER_NS /boot/config-4.1.12-32.el7uek.x86_64
CONFIG_USER_NS=y
```
Hoping that maybe someone could provide some pointers here, thanks in advance.

**Comment by thtanaka** [comment]
userns is enabled in the kernel
# grep CONFIG_USER_NS /boot/config-4.1.12-32.el7uek.x86_64
CONFIG_USER_NS=y

**Comment by runcom** [comment]
I can reproduce on a fresh rawhide installation

**Comment by thtanaka** [comment]
Thanks @runcom, I am not sure that this is really a selinux related policy issue (though I might be wrong), but here is my reason:
1. Do not see any related AVC denied list even from semodule -DB.
2. The operation not permitted (EPERM) is returned while we were doing the `return label.SetFileLabel(dest, mountLabel)` on the mounted `/dev/mqueue` at ` vendor/src/github.com/opencontainers/runc/libcontainer/rootfs_linux.go:122`, now looking at the kernel call stack on how we arrived at `inode_owner_or_capable()`:
```
[<ffffffff812240d4>] inode_owner_or_capable+0xd4/0xe0
[<ffffffff812badc1>] selinux_inode_setxattr+0x81/0x300
[<ffffffff812b3273>] security_inode_setxattr+0x33/0x80
[<ffffffff8122ebc7>] vfs_setxattr+0x77/0xc0
[<ffffffff8122ecad>] ? setxattr+0x9d/0x1c0
[<ffffffff8122ed3e>] setxattr+0x12e/0x1c0
[<ffffffff812184ef>] ? putname+0x6f/0x80
[<ffffffff8121981e>] ? user_path_at_empty+0x6e/0xc0
[<ffffffff8120a848>] ? __sb_start_write+0x58/0x110
[<ffffffff8122ee77>] path_setxattr+0xa7/0xe0
[<ffffffff8122f081>] SyS_lsetxattr+0x11/0x20
[<ffffffff8170cfee>] system_call_fastpath+0x12/0x71
```
The part inside the `inode_owner_or_capable()` function that returns `FALSE` is `kuid_has_mapping(ns, inode->i_uid)`, that is because the `inode->i_uid` is 0. This `inode->i_uid = current_fsuid()` is set during the process of mounting `mqueue`, and it is setting it to 0 at `ipc/mqueue.c`. IIUIC, now I am just wondering why during the mounting of `mqueue` the `current_fsuid()` is not our namespace uid, do we have to take care of that somehow ?

**Comment by rhatdan** [comment]
I wonder if /dev/mqueue can not handle user namespace?

**Comment by estesp** [comment]
Hmm..given the inode owner (0) doesn't have a mapping in the userns (which is correct), could this just be a permissions issue that when mounting /dev/mqueue we need to set ownership to the remapped root? This would be on the runc/libcontainer side of the house, but that can be tested pretty easily

**Comment by rhatdan** [comment]
Sure, although how are we handling other tmpfs mounts, they should have the same problem and be handled the same way.

**Comment by thtanaka** [comment]
Looking at runc/libcontainer, for tmpfs type, it accepts mounting with context/mountlabel, where as for the mqueue case (at least for this case, it falls back to mount without label and relatel it later - since cannot mount -t mqueue with context).

**Comment by rhatdan** [comment]
Right, but is there some way of handling of ownership of the mount point.  IE If I mount tmpfs /dev/shm inside of a container with UserNamespace, who fixes the permissions form 0:0 to DockerRoot:DockerRoot.

**Comment by thtanaka** [comment]
OK, digging it a bit further, now not sure if systemd could be in the play as well.
Here I run it on OL6 (sysvinit) system with same exact docker and linux kernel and here is the kernel call stack:
```
 [<ffffffff81220e5a>] inode_owner_or_capable+0xaa/0x120
 [<ffffffff812b7b13>] selinux_inode_setxattr+0xb3/0x310
 [<ffffffff81210e31>] ? complete_walk+0x51/0xe0
 [<ffffffff812b0a63>] security_inode_setxattr+0x43/0x90
 [<ffffffff8122d12a>] vfs_setxattr+0x9a/0x120
 [<ffffffff8122d28e>] setxattr+0xde/0x220
 [<ffffffff812119df>] ? putname+0x6f/0x80
 [<ffffffff81215973>] ? user_path_at_empty+0x63/0xa0
 [<ffffffff81208d49>] ? __sb_start_write+0x69/0x100
 [<ffffffff81227423>] ? mntput+0x23/0x40
 [<ffffffff8122d53f>] path_setxattr+0x8f/0xb0
 [<ffffffff81204301>] ? filp_close+0x61/0x90
 [<ffffffff8122d571>] SyS_lsetxattr+0x11/0x20
 [<ffffffff816fa26e>] system_call_fastpath+0x12/0x71
```
Now the important difference here vs the problematic one OL7 (systemd):
1. `inode_owner_or_capable` returns `TRUE` and as expected the `inode->i_uid` is equal to our namespace uid.
2. Notice also here there is a `mntput` in the call stack, IIUIC seems like `mntput` is trying to mounting it and putting it in our namespace while we do not see it in the OL7 (systemd base).

Now how could this be?

**Comment by thtanaka** [comment]
It seems that we cannot also `chown` after mounting /dev/mqueue, the reason is we will also be getting `-EPERM`, since inside `inode_change_ok()` we will again be checking the `inode->i_uid` i.e `uid_eq(current_fsuid(), inode->i_uid)`, the call stack for this:
``` 
 inode_change_ok+0x1a1/0x200
 simple_setattr+0x1b/0x60
 notify_change+0x3ad/0x480
 chown_common.isra.12+0x159/0x270
 SyS_fchownat+0xde/0x130
 ? syscall_trace_leave+0xc6/0x120
 system_call_fastpath+0x12/0x71
```
Now as raised by @rhatdan earlier with regards to whether /dev/mqueue can handle userns, so I traced the mounting of tmpfs at file `mm/shmem.c` to see the value of `inode->i_uid` which is set by `current_fsuid()`, it returns our remapped id (i.e 100000), however that is not the case for /dev/mqueue, as it returns 0, of course both of this mounting is performed by the same process. Somehow inside the kernel, `current_fsuid()` is changed to our remapped id for tmpfs but not for /dev/mqueue. I am not sure however if this experiment is suffice to show that /dev/mqueue doesn't support userns.

**Comment by liubogithub** [comment]
It's a kernel bug.
During kernel_init(), init_mqueue_fs() will mount a mqueue filesystem with the default namespace 'init_ipc_ns', and this mount is with MS_KERNMOUNT.  Later when docker wants to mount another mqueue, it's using 'current->nsproxy->ipc_ns' as the namespace argument, but this also refers to the default one 'init_ipc_ns', thus sget() just gets the same superblock that's mounted with MS_KERNMOUNT and it's without any selinux label stuff, but docker wants to mount mqueue with its own mount label, so we get "SELinux: mount invalid.  Same superblock...".

This also explains what @thtanaka has found about inode->i_uid.

So docker really should creates a different nsproxy->ipc_ns when trying to mount mqueue.

**Comment by runcom** [comment]
seems like this has been fixed in the current runc vendored with docker, closing now

**Comment by naphthalene** [comment]
Apologies if this is the wrong place to ask, but I am trying to use kubernetes on AWS (via CloudFormation), which uses CoreOS. Currently even the latest alpha release (https://coreos.com/releases/) is running Docker 1.10.3. This issue happens to me when I try to run a service via a ReplicationController and a private docker repository (quay.io).

```
May 03 22:21:50 <scrubbed> kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
May 03 22:21:50 <scrubbed> kubelet-wrapper[1234]: I0503 22:21:50.629272    1234 provider.go:91] Refreshing cache for provider: *credentialprovider.defaultDockerConfigProvider
May 03 22:21:50 <scrubbed> kubelet-wrapper[1234]: E0503 22:21:50.945204    1234 pod_workers.go:138] Error syncing pod 6e664d92-117d-11e6-86cd-12595a8629bd, skipping: failed to "StartContainer" for "event-service" with ErrImagePull: "image pull failed for <scrubbed>, this may be because there are no credentials on this request.  details: (Error: Status 403 trying to pull repository <scrubbed>: \"{\\\"error\\\": \\\"Permission Denied\\\"}\")"
May 03 22:21:51 <scrubbed> kernel: IPv6: eth0: IPv6 duplicate address fe80::42:aff:fe02:1208 detected!
May 03 22:21:51 <scrubbed> kubelet-wrapper[1234]: E0503 22:21:51.609254    1234 pod_workers.go:138] Error syncing pod 6e664d92-117d-11e6-86cd-12595a8629bd, skipping: failed to "StartContainer" for "event-service" with ImagePullBackOff: "Back-off pulling image \"<scrubbed>\""
```

What are my options here? Should I disable `--selinux-enabled` flag? Is there any way to upgrade to Docker 1.11.0 on CoreOS?

**Comment by akerl** [comment]
@runcom I'm still seeing this on 1.11.2. Based on the referenced commit/issue, they weren't merged into runc upstream. Is Docker patching this into runc manually?

**Comment by mrunalp** [comment]
This should be re-opened as the issue still exists. I have created a PR to fix it at https://github.com/opencontainers/runc/pull/959. The patch is similar to what @thtanaka had proposed earlier. Thanks!

**Comment by joaquin386** [comment]
On 17.03.1-ce I am still getting that error.
Issue with enabling selinux-enabled and userns-remap at the same time.

**Comment by AaronDMarasco-VSI** [comment]
I am seeing this on CentOS 7, 1.12.6. I cannot just tell my users to not use selinux.

**Comment by drnybble** [comment]
Seeing this on Centos 7 with 17.0.3.0-ce with selinux-enabled and userns-remap, any updates on whether this should be fixed??

**Comment by thaJeztah** [comment]
This looks to depend on a fix in the runtime (Runc), but the fix has not been merged upstream https://github.com/opencontainers/runc/pull/959

**Comment by jodumont** [comment]
So if I may resume and see if I understood correctly

For now, as temporary and easiest reversible solution is to not use `--selinux-enabled` until this [pull](https://github.com/opencontainers/runc/pull/1562) is approve ?

**Comment by The-Loeki** [comment]
`userns-remap` sets up it's own subdir within /var/lib/docker (forcing you to manually clean the non-remapped one), and forces changes to ownership & file rights which will be broken and likely most containers needing 'em until you do.

SElinux is always an enforce/permissive/disable toggle away; in permissive mode you can easily fix any issues that pop up and other than that the config is pretty much standalone, with decent ops to relabel the whole shebang as the config says it should be labeled. 

So my guess would be 1. ;)
Bear in mind however SElinux is not so simple if more serious issues than file labeling arise.

**Comment by jodumont** [comment]
As digging further on that topic/situation
and maybe to help others have the same questions of mine

I would say it's safer to move from a non userns-remap to a userns-remap than from a non SELinux to a SELinux for this reason:

If you run with SELinux disabled, all files created on your system will have no context and no label
than when you will enforce SELinux you will have to at least a restorecon and start to work with SELinux

If you active userns-remap later, you will "only" have to play with the chown command and what goes inside /etc/sub[u|g]id
