### ISSUE TITLE
Docker managed windows container takes hostname of host instead of container id

### ISSUE THREAD

**Issue by mathiasconradt** [docker/docker#21762]
**Environment:**

- Windows Server 2016 TP4
- Docker version 1.10.0-dev, build 18c9fe0 (details at the bottom)

There is an a bit [related issue](https://github.com/docker/docker/issues/18539) here (container being able to find itself via hostname), but it's with Linux containers and regarding x-network switch, so it's not the same.

**Expected behavior:**

- I run a windows container and the hostname of the container is its docker id.
- The hostname shown with `docker inspect` is identical to the hostname output when I run `hostname `command inside the container.

**Actual behavior:**

- The hostname of the container is the hostname of the container host.
- Hostname via `docker inspect` and hostname via `hostname` command differs.

**How to reproduce:**

Create a new container, i.e. from WindowsServerCore.
Check it's container id:

```
PS C:\> docker ps -a
CONTAINER ID        IMAGE               COMMAND                   CREATED             STATUS                    PORTS               NAMES
6d2d071453c5        d9d15fbca6d7        "cmd /S /C 'C:\\sorba-"   6 days ago          Up 3 days                                     derrin
```

Inspect the container, check the hostname shown there:

```
PS C:\> docker inspect 6d2d071453c5

    "Config": {
        "Hostname": "6d2d071453c5",
        "Domainname": "",
        "User": "",

```

Attach to the container, and type "hostname" to check its hostname:

```
PS C:\> docker attach 6d2d071453c5
> hostname
test2016
```

Try to ping the container id:

```
PS C:> ping 6d2d071453c5
Ping request could not find host 6d2d071453c51. Please check the name and try again.
```

**Notes:**

This behaviour is relevant for example when trying to run the Visual Studio remote debugger inside the container. The remote debugger seems to take the hostname from the docker config instead of what the hostname command says. ([I described](http://stackoverflow.com/questions/36420337/running-visual-studio-remote-debugger-in-windows-container-docker-managed) the issue trying to get the remote debugger to run inside a container on StackOverflow.)

-------------------------------------------
```
PS C:\> docker version
Client:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   18c9fe0
 Built:        Mon Nov 23 22:32:50 UTC 2015
 OS/Arch:      windows/amd64

Server:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   18c9fe0
 Built:        Mon Nov 23 22:32:50 UTC 2015
 OS/Arch:      windows/amd64
```

```
PS C:\> docker info
Containers: 3
Images: 35
Server Version: 1.10.0-dev
Storage Driver: windowsfilter
 Windows:
Execution Driver:
 Name: Windows 1854
 Build: 1.10.0-dev 18c9fe0
 Default Isolation: process
Logging Driver: json-file
Plugins:
 Volume: local
 Network:
Kernel Version: 10.0 10586 (10586.103.amd64fre.th2_release.160126-1819)
Operating System: Windows Server 2016 Technical Preview 4
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 8 GiB
Name: test2016
ID: OZRB:MQXU:63JX:OFGH:QEZK:ZEDS:CVU3:VTHR:7NDI:ATVK:O3XO:6P4S
Debug mode (server): true
 File Descriptors: -1
 Goroutines: 31
 System Time: 2016-04-05T11:31:17.7306926+02:00
 EventsListeners: 0
 Init SHA1:
 Init Path: C:\Windows\System32\docker.exe
 Docker Root Dir: C:\ProgramData\docker
Username: mathiasconradt
Registry: https://registry-win-tp3.docker.io/v1/
```

**Comment by jstarks** [comment]
This is a bug in Windows, not in Docker. It may be fixed in TP5, but I have not verified that. It will definitely be fixed for RTM.

@jhowardmsft do you know if this has been fixed yet?

**Comment by mathiasconradt** [comment]
Thanks for the info. Any idea when TP5 will be released? Cannot find any info online.

**Comment by jhowardmsft** [comment]
It isn't fixed in TP5. @mathiasconradt Soon. I'm not sure I am allowed to provide a date publicly though.

```
$ docker run -i --rm -h freddy windowsservercore cmd
Microsoft Windows [Version 10.0.14300]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Windows\system32>hostname
hostname
WIN-DE6U4068NAF
```

**Comment by thaJeztah** [comment]
@jhowardmsft do you think we should keep this issue open for tracking, or close, because it's not something we can fix inside this repository?

**Comment by jhowardmsft** [comment]
@thaJeztah I wouldn't track Windows bugs here that can't be fixed in the docker codebase.

**Comment by thaJeztah** [comment]
@mathiasconradt following the discussion above, I'll close this here; feel free to comment though after I've closed

**Comment by StefanScherer** [comment]
Still the same in TP5 and windowsservercore 10.0.14300.1000

```
C:\code>hostname
WIN-DE6U4068NAF

C:\code>set comp
COMPUTERNAME=CHECKIN
```

Will this be fixed with a new base os image?

**Comment by mathiasconradt** [comment]
The initial problem that I experienced, which is the title of this ticket ("_Docker managed windows container takes hostname of host instead of container id_") is resolved in TP5. When I type "hostname" in both container and host, I get different names, which was not the case in TP4.

The second point, that the container hostname in the `docker inspect` differs, is still the same and not fixed though. The `docker inspect` still shows the container id as the container hostname, i.e. "_34a09b9d45bb_", while the actual container hostname is "_WIN-DE6U4068NAF_"

**Comment by StefanScherer** [comment]
Thanks for opening the issue, that was the only hit googling for that hostname.

I have problems running a Consul agent inside a container as it uses this fixed hostname registering services. Trying to fix it, found a first place in the containers registry.

```
C:\code>reg query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Group Policy\DataStore\Machine\0"

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Group Policy\DataStore\Machine\0
    szName    REG_SZ    WIN-DE6U4068NAF
    szTargetName    REG_SZ    WIN-DE6U4068NAF
```

**Comment by StefanScherer** [comment]
Works with official released Docker images + Win2016 Eval.

**Comment by str3tch** [comment]
What do you mean by "official released docker images", and which WS2016?
TP5?

**Comment by StefanScherer** [comment]
@str3tch No, TP5 is so "last year" :-) Microsoft has announced Windows 2016 at Ignite this week. There is an evaluation ISO available. So you should use this for further work with Windows Containers. Or just use Windows 10 Pro with the Docker 4 Windows Beta. You can use nanoserver + windowsservercore Docker images directly on Windows 10.

Just verified it with a Win2016 VM from my Mac:

```
$ docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   601004e
 Built:        Wed Sep 28 12:46:56 2016
 OS/Arch:      windows/amd64

$ docker info
Containers: 39
 Running: 0
 Paused: 0
 Stopped: 39
Images: 241
Server Version: 1.13.0-dev
Storage Driver: windowsfilter
 Windows: 
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Security Options:
Kernel Version: 10.0 14393 (14393.206.amd64fre.rs1_release.160915-0644)
Operating System: Windows Server 2016 Standard Evaluation
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 4 GiB
Name: vagrant-2016
ID: ZXHY:EMGJ:ETUQ:ZUK4:SN3F:GUSN:SFIX:6S7P:E4Q6:X2IC:NXHX:YZNC
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Username: stefanschererseal
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

and then

```
$ docker run -i --rm -h freddy microsoft/windowsservercore cmd /c "hostname & set comp"
freddy
COMPUTERNAME=FREDDY
```

**Comment by str3tch** [comment]
Oh great! I'll go get me an eval edition :)

**Comment by mathiasconradt** [comment]
https://www.microsoft.com/de-de/evalcenter/evaluate-windows-server-2016

**Comment by StefanScherer** [comment]
or without the `/de-de` for all other countries 🌎
