### ISSUE TITLE
mediaType for Config of V2.2 Manifest is text/html

### ISSUE THREAD

**Issue by lizhuqi** [docker/docker#22378]
**Output of `docker version`:**

```
(paste your output here)
```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64

**Output of `docker info`:**

```
(paste your output here)
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 30
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /usr/local/google/docker/aufs
 Backing Filesystem: extfs
 Dirs: 49
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-85-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 31.32 GiB
Name: lizhuqi-workstation.kir.corp.google.com
ID: KMD4:OSAH:YVCB:GN6G:NA32:RRSN:LAWB:77KN:PDTG:BW6T:K6E5:ZLI7
Username: lizhuqi
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Try to push an image to docker hub
2. Exam the manifest file

**Describe the results you received:**
 The media type for config of the manifest file is text/html 

**Describe the results you expected:**
 The media type for config of the manifest file is application/vnd.docker.container.image.v1+json

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
I think this should be fixed in docker 1.11.1, through this PR: https://github.com/docker/docker/pull/21949

can you try if you're still able to reproduce this on docker 1.11.1?

**Comment by aaronlehmann** [comment]
@lizhuqi: Can you clarify what you are seeing and how you are inspecting the manifest? Which field shows text/html?

@thaJeztah: I don't think this is related to #21949. #21949 had something accidentally hardcoded to `application/octet-stream`.

**Comment by lizhuqi** [comment]
Hi Aaron and Sebastiaan,

The Config media type is showing text/html. I am working in google
container registry team. The way I get this file is I use docker client
1.10.3 to push image to our registry and catch the manifest json sent to us
in our registry code.

Below is the manifest json file content:

{
  "schemaVersion": 2,
  "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
  "config": {
     "mediaType": "text/html",
     "size": 1395,
     "digest": "sha256:c648cd6a73969d01003f84dcb558aa19f153fdbb63f6e7bc096cf204c1d46280"
  },
  "layers": [
     {
        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
        "size": 51354018,
        "digest":
"sha256:81cc5f26a6a083c024fb4138326e4d00f9a73f60c0e2a4399e1f7617ebe8c6c9"
     },
     {
        "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
        "size": 32,
        "digest":
"sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
     }
  ]}


By the way, when I tried to use the following curl command to get the v2.2
manifest from docker hub registry, it still returns v2.1 manifest. Do I
need to set something special in my command? From the document I only need
to set Accept field in header.
Here is the command:

#!/bin/bash -e
export NAME=lizhuqi/debian
export BEARER=$(curl -u lizhuqi:Test1101 "
https://auth.docker.io/token?scope=repository:$NAME:pull&service=registry.docker.io"
| cut -d'"' -f 4)
curl -H "Authorization: Bearer $BEARER" \
     -H "Accept: application/vnd.docker.image.manifest.v2+json" \

https://registry-1.docker.io/v2/$NAME/manifests/sha256:3eb57a4024e69d04ace49be70aa9d13610cfe611a0191c7edc26f5a2b675e7b1

Thanks,
Lizhu

**Comment by aaronlehmann** [comment]
@lizhuqi: Thanks for the clarification. I think @thaJeztah is actually correct that this was fixed by #21949. I misremembered that issue and thought it only inserted `application/octet-stream` into the manifest, but actually it would use whatever the HTTP server returned as the `Content-Type`. Can you please try Docker 1.11.1?

**Comment by aaronlehmann** [comment]
> By the way, when I tried to use the following curl command to get the v2.2
manifest from docker hub registry, it still returns v2.1 manifest. Do I
need to set something special in my command? From the document I only need
to set Accept field in header.

I believe Docker Hub is configured not to return new-style manifests right now. I think this will be changing soon.

**Comment by lizhuqi** [comment]
Hi Aaron,

I tried again with Docker 1.11.1, however the issue still repro in this
version of Docker.

The manifest I get still has "text/html" mediaType in Config field.

Thanks,
Lizhu

**Comment by aaronlehmann** [comment]
@lizhuqi: Just want to confirm that you're pushing the manifest with Docker 1.11.1, not just pulling?

**Comment by caglar10ur** [comment]
@lizhuqi I hope you know that you leaked your hub username/password (check your curl example)

@aaronlehmann any idea when hub will start serving v2.2 manifests?

**Comment by aaronlehmann** [comment]
@caglar10ur: I believe the target date is around the beginning of June, but I can't confirm that until it's officially announced.

**Comment by lizhuqi** [comment]
Hi Aaron,

Yeah, I am pushing the manifest with Docker 1.11.1, before I push I double
checked that the docker version I am running is 1.11.1. All other fields of
the v2.2 manifest I catch look right to me except the mediaType field in
Config. oh, thanks for reminding me. I will be more careful when I share my
command next time.

Lizhu

**Comment by aaronlehmann** [comment]
I'm not able to reproduce this with Docker 1.11.1 and Registry 2.4.0. Here is what I see in the manifest after pushing:

```
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 1370,
      "digest": "sha256:47bcc53f74dc94b1920f0b34f6036096526296767650f223433fe65c35f149eb"
   },
```

I noticed your script to fetch the manifest has a SHA256 digest in the URL. Are you updating this with the new digest from `docker push` after pushing with 1.11.1?

**Comment by lizhuqi** [comment]
Hi Aaron,

The public docker hub registry doesn't support v2.2 Manifest yet, so when I
use the curl command to get the manifest, it returns v2.1 manifest. Can you
add me to the dogfooding list of the registry 2.4.0?

My current docker client version is 1.11.1, build 5604cbe.

By the way, the image I pushed was originally created by docker 1.8.3. Does
it matter?

Here is the v2.1 version of manifest:

{
  "schemaVersion": 1,
  "name": "weizheng-2015-hackathon/alpine",
  "tag": "latest",
  "architecture": "amd64",
  "fsLayers": [
     {
        "blobSum":
"sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
     },
     {
        "blobSum":
"sha256:81cc5f26a6a083c024fb4138326e4d00f9a73f60c0e2a4399e1f7617ebe8c6c9"
     }
  ],
  "history": [
     {
        "v1Compatibility":
"{\"architecture\":\"amd64\",\"config\":{\"Hostname\":\"30db80bfe262\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":null,\"Cmd\":[\"/bin/bash\"],\"Image\":\"cb6fb082434ea9d7f25798e96abc06cb176cbe910970ec86874555e7c9fbc04a\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":null},\"container\":\"1a9173a681853efd414d3ffc036871ac5a6c46e2aefbe839d186cce595d48a4d\",\"container_config\":{\"Hostname\":\"30db80bfe262\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":null,\"Cmd\":[\"/bin/sh\",\"-c\",\"#(nop)
CMD [\\\"/bin/bash\\\"]\"],\"Image\":\"cb6fb082434ea9d7f25798e96abc06cb176cbe910970ec86874555e7c9fbc04a\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":null},\"created\":\"2016-01-07T01:07:11.982173215Z\",\"docker_version\":\"1.8.3\",\"id\":\"f6032ff62cea1b30f92305d43a83c27af8b3926142acbec2b30c7a53d7e21969\",\"os\":\"linux\",\"parent\":\"0b9110ffe91d0ace44e317473a6a5442566f35f096463fbe25dffa6a26231536\"}"
     },
     {
        "v1Compatibility":
"{\"id\":\"0b9110ffe91d0ace44e317473a6a5442566f35f096463fbe25dffa6a26231536\",\"created\":\"2016-01-07T01:07:09.137000568Z\",\"container_config\":{\"Cmd\":[\"/bin/sh
-c #(nop) ADD file:0098703cdfd5b5eda3aececc4d4600b0fb4b753e19c832c73df4f9d5fdcf3598
in /\"]}}"
     }
  ],
  "signatures": [
     {
        "header": {
           "jwk": {
              "crv": "P-256",
              "kid":
"KMD4:OSAH:YVCB:GN6G:NA32:RRSN:LAWB:77KN:PDTG:BW6T:K6E5:ZLI7",
              "kty": "EC",
              "x": "uCrnMBgbxLEdUwFtgsu3q9JOsK62OGmJnmekrkDKolk",
              "y": "vo-sDO4729K1Bvu67Lu7Leq0FGW0YT-mwgnitjqM6QQ"
           },
           "alg": "ES256"
        },
        "signature":
"Zzw0xvyRftKcKgsKVTcKLrt3oqvUU6iLnLAFlhZEIPGk8AYWVE3Lnaq1-aRYvSd1FwKSa3hGANlUkstagjpiqw",
        "protected":
"eyJmb3JtYXRMZW5ndGgiOjE5NTUsImZvcm1hdFRhaWwiOiJDbjAiLCJ0aW1lIjoiMjAxNi0wNC0yMFQxODoxNjo0MloifQ"
     }
  ]}

Not sure why we will get the different mediaType, Our code just get the
manifest and then try to parse it. We don't modify anything in the middle.

**Comment by lizhuqi** [comment]
One more question about v2.2 manifest content, I noticed that the order of
layers is opposite of the layer order in v2.1 manifest. Is this a bug or it
is by design? Manifest v2.2 has base layer to be the first in the array and
then diff, while the v2.1 manifest has base layer to be the last element in
the fsLayers array.

**Comment by aaronlehmann** [comment]
Hi @lizhuqi,

> Can you add me to the dogfooding list of the registry 2.4.0?

Docker Registry 2.4.0 is already released. It's software you can use to run your own registry. You can get the source at https://github.com/docker/distribution, or if you prefer a prebuilt Docker container, `docker pull registry:2`.

> One more question about v2.2 manifest content, I noticed that the order of
layers is opposite of the layer order in v2.1 manifest. Is this a bug or it
is by design?

Yes, this is by design. We thought it was strange that the old manifest format had the base layer at the end, so we changed the order to start with the base layer.

**Comment by lizhuqi** [comment]
Hi Aaron,

I download and run docker registry 2. The bug doesn't repro with the Docker
registry 2. I used the same docker image to play around. Docker registry 2
is returning the right mediaType for Config.

I take a quick look at some src code:

Line 57 at
https://github.com/docker/distribution/blob/467fc068d88aa6610691b7f1a677271a3fac4aac/manifest/schema2/builder.go
override
the mediaType for Config. May this be the reason why we get the correct
mediaType for Config returned by Registry?

Thanks,
Lizhu

**Comment by aaronlehmann** [comment]
That source code is vendored into Docker itself, so it shouldn't make a difference which registry implementation Docker is talking to.

**Comment by lizhuqi** [comment]
oh, then I have no clue why the data sent to and caught by our registry
code is wrong.

**Comment by lizhuqi** [comment]
Hi Aaron,

This issue no longer repro.

Here is the schema 2 manifest I get:
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 1801,
      "digest": "sha256:ec496b4bc6e307efea8dd6e4038379e973b558ac60a0c58216a1691976c96ef6"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 32,
         "digest": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 38413683,
         "digest": "sha256:dc50bc165b2f392f3240004e3f41e99e177cf505738f3fec905e5c78b66f821c"
      }
   ]
}

The media type for config is the right one, so we can close this issue now. I checked the docker version, my current version is still 1.11.1 with build 5604cbe. I didn't update the docker version. No idea what changed and fixed this issue. Just hope it is gone forever.  

Thanks!
Lizhu
