### ISSUE TITLE
Service contraints not being honoured in a swarm

### ISSUE THREAD

**Issue by hipposareevil** [docker/docker#24192]
**Output of `docker version`:**
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:45:29 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:45:29 2016
 OS/Arch:      linux/amd64

**Output of `docker info`:**
Containers: 4
 Running: 3
 Paused: 0
 Stopped: 1
Images: 7
Server Version: 1.12.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 47
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: active
 NodeID: 8ptf9fd6phpss2qy15a5c6frm
 IsManager: Yes
 Managers: 1
 Nodes: 3
 CACertHash: sha256:255d696a217a06801576ddf2a19f2b38487d007c6b470e545bf659e170a969ad
Runtimes: default
Default Runtime: default
Security Options: apparmor seccomp
Kernel Version: 4.4.0-28-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 251.9 GiB
Name: xxxx
ID: ....
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Installed docker on fresh Ubuntu-16 baremetal boxes.

**Steps to reproduce the issue:**
1. On node 1 - create a swarm: swarm init
2. On node 2 - update /etc/systemd/system/docker.service file with label:
ExecStart=/usr/local/bin/dockerd -H fd:// --label foo="bar"
3. On node 2 - Restart daemon
4. On node 2 - verify label has taken: 
$ docker -D info
....
Labels:
 foo=bar
....
5. On node 2- join swarm: 
$ d swarm join XXX:2377
6. On node 1- create service with constraint:
$ docker service create --constraint foo="bar" --name testconstraint --replicas 5 -p 8889:80 httpd:2.4

**Describe the results you received:**
7. On node 1- verify new service is running on node 1:
$ docker ps
CONTAINER ID        IMAGE                  COMMAND              CREATED              STATUS              PORTS                    NAMES
7e52cca2ec86        httpd:2.4              "httpd-foreground"   About a minute ago   Up 58 seconds       80/tcp                   testconstraint.2.1t257nejusprq9toos441a1ah
0f0d75d2057d        httpd:2.4              "httpd-foreground"   About a minute ago   Up 57 seconds       80/tcp                   testconstraint.4.2jujh8pg5pl2t3cgb0109kl33

**Describe the results you expected:**

I was expecting the service to only run on node 2, where the label was applied to the daemon.

**Additional information you deem important (e.g. issue happens only occasionally):**

I've tried this with variations of the label like:
--constraint foo=bar, --constraint foo==bar
with no luck. Happens consistently.

Am I creating the label in the engine incorrectly?

thanks

**Comment by dperny** [comment]
There's some work being done on this right now in swarmkit. I believe docker/swarmkit#893 is one PR with some fixes to constraints in it. There may be others.

**Comment by eskaaren** [comment]
I can verify a similar issue with docker 1.12 rc3:

docker service create --constraint node=worker1 --replicas 5 --name hello alpine ping docker.com

Results in empty node value when running docker service tasks hello.

Tried with name, node, id, hostname with same result..
also node.hostname etc.

Don't know if docker/swarmkit#893 was included in rc3?

**Comment by aaronlehmann** [comment]
cc @dongluochen

**Comment by aaronlehmann** [comment]
@hipposareevil: Constraints changed from -rc2 to -rc3, so I would upgrade to -rc3 and try this again.

I believe the syntax to match an engine label is `engine.labels.foo == bar`.

We probably need to add documentation around this. It may also make sense to add client-side constraint validation for `service create` and `service update`.

**Comment by aaronlehmann** [comment]
https://github.com/docker/swarmkit/pull/1114 adds constraint validation at the API level, which may help make this less confusing.

**Comment by hipposareevil** [comment]
@aaronlehmann   I upgraded to -rc3 with same results:
$ d --version
Docker version 1.12.0-rc3, build 91e29e8

I applied the following label to my 2nd node:
$ grep label /etc/systemd/system/docker.service
ExecStart=/usr/local/bin/dockerd -H fd:// --label foo==bar

Created new service:
$ docker service create --constraint foo=bar --name testconstraint --replicas 5 -p 8889:80 httpd:2.4
(tried with 'foo==bar' and 'foo="bar"' as well)
The service is then brought up on both nodes.

**Comment by aaronlehmann** [comment]
The constraint needs to be formatted like `engine.labels.foo = bar` (see https://github.com/docker/docker/issues/24192#issuecomment-230533775).

I think we are not covering this well in our docs - ping @sfsmithcha

**Comment by sfsmithcha** [comment]
@aaronlehmann this isn't covered yet in docs, which are WIP, I'll need to cover this in service creation docs.

**Comment by hipposareevil** [comment]
@aaronlehmann 
Apologies if I'm missing the gist here, but I've tried the various combos and it still fails:

1: with space between the "="
$ docker service create --constraint engine.labels.foo = bar --name testconstraint ....
Error response from daemon: rpc error: code = 3 desc = ContainerSpec: "=" is not a valid repository/tag

2:  with "==", fails silently
$ docker service create --constraint engine.labels.foo==bar --name testconstraint ....

3: service starts, but runs on all nodes
$ docker service create --constraint engine.labels.foo=bar --name testconstraint .....

I've also updated the docker.service file with both "foo=bar" and "foo==bar" with same result.

**Comment by dongluochen** [comment]
@hipposareevil Constraints on labels are not working on RC3 (there was some confusion on how to define labels). We have reached agreement on syntax as defined in [docker/swarmkit](https://github.com/docker/swarmkit/blob/master/README.md), see **constraint** section. It supports `==` and `!=` comparisons. This change has not merged into docker/docker yet and we are working on that.

**Comment by hipposareevil** [comment]
@dongluochen Thanks for the update.  I'll wait til it's merged and give it a whirl then.

**Comment by aaronlehmann** [comment]
Sorry for the misinformation on this. I thought this had made it into -rc3, but was wrong about this.

**Comment by tiborvass** [comment]
Fixed by #23312 

@aaronlehmann please confirm that this issue was fixed in https://github.com/docker/swarmkit/pull/1114

**Comment by aaronlehmann** [comment]
@tiborvass: I would point to https://github.com/docker/swarmkit/pull/893

**Comment by dongluochen** [comment]
@tiborvass #23312 doesn't fix this issue. We need to vendor [docker/swarmkit#893](https://github.com/docker/swarmkit/pull/893) and [docker/swarmkit#1114](https://github.com/docker/swarmkit/pull/1114).

**Comment by aaronlehmann** [comment]
@dongluochen: It looks like both of these have been vendored now.

I wish we had vendored a current copy of swarmkit instead of a slightly outdated one, because it would make reasoning about this stuff a lot easier.

**Comment by tiborvass** [comment]
Thanks, yes, docker/swarmkit#893 has been vendored with #23312

**Comment by hipposareevil** [comment]
Note I see this fixed in master: Docker version 1.12.0-dev, build 10d5d08

**Comment by joonas-fi** [comment]
Sidenote: this seems to be a worrying trend in the Docker project now (my other issue with docs: https://github.com/docker/docker/issues/24277#issuecomment-244533638) - shipping stuff with missing, or even **worse: incorrect** documentation. `docker service create --constraint node==nodename` does not work even though it's documented here: https://docs.docker.com/swarm/scheduler/filter/#/how-to-write-filter-expressions (example: `node==node1` "matches node node1")

**Comment by sfsmithcha** [comment]
@joonas-fi , the doc you refer to on filters refers to "Docker Swarm." It is called out at the top of the page. The information is correct within the context of Docker Swarm. For Swarm Mode, the documentation is included with the Docker Engine docs as follows:

The 1.12 Docker Engine command line reference documents how to do constraints for Docker Engine swarm mode:
https://docs.docker.com/engine/reference/commandline/service_create/#/specify-service-constraints

It's also mentioned here: https://docs.docker.com/engine/swarm/services/#/control-service-scale-and-placement

Sorry for the confusion.
