### ISSUE TITLE
macOS Sierra - Compatibility - Docker for Mac

### ISSUE THREAD

**Issue by RowanKaag** [docker/docker#24675]
**Output of `docker version`:**

```
'none'.  Menu bar 👉 Info pane shows:
Version 1.12.0-rc4-beta19 (build: 10258)
```

**Output of `docker info`:**

```
'none'. Menu bar 👉 Diagnose & feedback shows:

Docker for Mac: version: win-v1.12.0-beta19
OS X: version 10.12 (build: 16A239j)
logs: /tmp/20160715-102808.tar.gz
failure: com.docker.osxfs is not running
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     virtualization
[OK]     menubar
[OK]     system
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[ERROR]  moby
         /Users/rowankaag/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]     driver.amd64-linux
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker for Mac. Tried factory reset and re-install. Problems since previous update (beta 18)

**Steps to reproduce the issue:**
1. Install macOS Sierra
2. Install Docker for Mac
3. Start Docker
4. Experience freezing/hanging/everlasting-starting of Docker

**Describe the results you received:**
None, Docker won't get past starting. Sometimes it does start and running 'docker ps' does work and shows no containers running. Then when running another docker command (I tried docker rm -f nginx) it freezes the last command.

**Describe the results you expected:**
Somewhat functioning Docker, expecting minor issues in global area's like networking. The container framework doesn't seem to function at all.

**Additional information you deem important (e.g. issue happens only occasionally):**
As far as I can remember, Docker was working until Docker for Mac beta 17.

Seems familiar to:
https://forums.docker.com/t/docker-is-stuck-starting-no-log-entries-explaining/14347
https://forums.docker.com/t/com-docker-osxfs-is-not-running/15757

After reading about factory reset killing containers, this might explain the hanging of running the container as it didn't exist? I can't perform a factory reset now with the new beta as others suggested in the above links. When attempting to go to Menu Bar 👉 Docker 👉 Preferences, I'm faced with:

"Error.
Failed to retrieve settings values.
frontend process failed"

**Comment by justincormack** [comment]
Hi, we are working on this. The first beta of Sierra worked, but the more recent one does not. cc @avsm

**Comment by justincormack** [comment]
See also https://github.com/docker/vpnkit/issues/79

**Comment by RowanKaag** [comment]
Thankyou! I have some more logs underneath this post if this might come in handy.

```
~/Library/Group~/Library/Group\ Containers/group.com.docker/bin/docker-diagnose
OS X: version 10.12 (build: 16A239j)
Docker.app: version: win-v1.12.0-beta19
Running diagnostic tests:
Error docker ps: timeout after 10.00s
[ERROR]   docker-cli       docker ps failed: Failure("docker ps: timeout after 10.00s")
Error docker ps: timeout after 10.00s
[ERROR]   Moby booted      /Users/rowankaag/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/console-ring does not exist
[OK]      driver.amd64-linux
[OK]      vmnetd
[ERROR]   osxfs            com.docker.osxfs is not running
[OK]      db
[OK]      slirp
[OK]      menubar
[OK]      environment
[OK]      Docker
[OK]      VT-x
Most specific failure is: com.docker.osxfs is not running
Docker logs are being collected into /tmp/20160715-164244.tar.gz
Would you like to upload log files? [Y/n]: y

Your unique id is: FF1F0C0E-7B3D-4281-966A-1613EFEE27B4
Please quote this in all correspondence.
```

**Comment by avsm** [comment]
Thanks, I can confirm some breakage (possibly not vpnkit related) on 10.12, but still tracking it down. /cc @djs55

**Comment by avsm** [comment]
Looks like it's the Go proxy from the Docker CLI -> vsock layer

```
$ docker -H unix:///Users/avsm/Library/Containers/com.docker.docker/Data/\*00000003.00000948 run -it alpine ls
```

works but the direct
```
$ docker run -it alpine
```

fails.  So at least vsock is working fine and we're down to one daemon now.  But nothing is killing slirp yet, so not sure why the proxy works for some users and not others (possibly the beta version of OSX that we are on)

**Comment by RowanKaag** [comment]
Nevermind my post, most likely the cause of a factory reset. I did not restart my mac afterwards. Restarted mac now and everything seems to function as expected on beta 2.

**Comment by mattrobenolt** [comment]
Just to add a datapoint:

Running directly to the vsock layer hangs for me too when doing a `pull`.

I did:

```
$ docker -H unix:///Users/matt/Library/Containers/com.docker.docker/Data/\*00000003.00000948 pull postgres:9.5
```

Though, this doesn't cause the entire world to explode like if I were to simply do `docker pull postgres:9.5`. I was able to `^C` out, then rinse and repeat. I'm able to successfully continue without a 100% broken setup by doing this.

I've uploaded logs to `20A3922C-B0CB-4AB5-A281-85A8C7D54032` in case this behavior is any different.

```
OS X: version 10.12 (build: 16A238m)
Docker.app: version: win-v1.12.0-beta19
Running diagnostic tests:
Error docker ps: timeout after 10.00s
[ERROR]   docker-cli       docker ps failed: Failure("docker ps: timeout after 10.00s")
[OK]      Moby booted
Error docker ps: timeout after 10.00s
[OK]      driver.amd64-linux
[OK]      vmnetd
[OK]      osxfs
[OK]      db
[OK]      slirp
[OK]      menubar
[OK]      environment
[OK]      Docker
[OK]      VT-x
Most specific failure is: docker ps failed: Failure("docker ps: timeout after 10.00s")
Docker logs are being collected into /tmp/20160716-095413.tar.gz
Would you like to upload log files? [Y/n]: Y

Your unique id is: 20A3922C-B0CB-4AB5-A281-85A8C7D54032
Please quote this in all correspondence.
```

**Comment by nil1511** [comment]
This might be useful 
https://forums.docker.com/t/docker-beta-for-mac-does-not-work-and-hangs-frequently-on-macos-10-12/18109

After disabling ntp. Its working for me.
`sudo launchctl unload /System/Library/LaunchDaemons/org.ntp.ntpd.plist`
or
`sudo launchctl stop /System/Library/LaunchDaemons/org.ntp.ntpd.plist`

**Comment by justincormack** [comment]
There is an issue with the time syscall in Go before 1.6.3 on Sierra which
may be related. We are still working on this issue but yesterday's beta may
be slightly improved as I think it was built with this version of Go. That
could well affect NTP.

**Comment by RowanKaag** [comment]
Everything appears to be running fine for my use cases (simple port forwarding and volume & `docker build`). macOS Sierra beta 3 & docker beta 20.

```
Docker for Mac: version: mac-v1.12.0-beta20
OS X: version 10.12 (build: 16A254g)
logs: /tmp/20160720-103550.tar.gz
[OK]     docker-cli
[OK]     app
[OK]     moby-syslog
[OK]     virtualization
[OK]     menubar
[OK]     system
[OK]     osxfs
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by justincormack** [comment]
Great news! I will close this then. Feel free to reopen if it breaks on any Sierra updates, but we have a test machine now (we have some build issues, due to Swift changes, but that is an internal issue).

**Comment by milaniliev** [comment]
I have a (slightly different) Sierra issue. After upgrading to Sierra Public Beta 1 (roughly the same as Dev Beta 2, I think), Docker's "sending build context to daemon" on Docker Build hangs at a random spot 10 - 300MB in on every `docker build` I attempt.

Just upgraded to Sierra Public Beta 2 (Dev Beta 3) and Docker for Mac 1.12-rc4. The issue persisted; had to follow the advice above and do `sudo launchctl unload /System/Library/LaunchDaemons/org.ntp.ntpd.plist` (just `sudo launchctl stop org.ntp.ntpd` did not fix it, for some reason).

`docker version`:

```
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by justincormack** [comment]
Sorry, is this the latest beta 20, we released two betas with rc4.

**Comment by milaniliev** [comment]
How do I tell? I downloaded it today, if that helps.

**Comment by jianbin-wei** [comment]
I also have some hang issue also on the same docker version as @milaniliev and sierra public beta 2.  I did unload the ntpd and it works fine now.  

So the issue is not fixed yet.

**Comment by sodabrew** [comment]
Confirming the issue is not resolved with Sierra Public Beta 2 and Docker for Mac:
```
Version 1.12.0-rc4-beta20 (build: 10404)
32ce3bdb164320603f1c2d1fb2ba32a43477ef3d
```

The ntpd workaround is still required:
```
sudo launchctl unload /System/Library/LaunchDaemons/org.ntp.ntpd.plist
```

**Comment by claygriffiths** [comment]
It's required for Sierra beta 3 as well.

**Comment by justincormack** [comment]
It is possible some components are not yet built with the new Go, so it is the same issue, it sounds related.

**Comment by dbpolito** [comment]
````
sudo launchctl unload /System/Library/LaunchDaemons/org.ntp.ntpd.plist
````

also fixed for me

**Comment by RnbWd** [comment]
on Sierra Beta 3  using 

````
sudo launchctl unload /System/Library/LaunchDaemons/org.ntp.ntpd.plist
````

 docker is working better than it had in any previous release. Why would turning off the `ntpd` daemon fix everything?  I was very puzzled by this My first hypothesis (which turns out to be correct) is that the hypervisor image isn't able to communicate with the system clock. But what's more interesting IMO - is that a method `OSSpinLock` is deprecated in Sierra, and it won't allow you to compile anything using that method. Looking deeper - I submitted a [pull request](https://github.com/docker/hyperkit/pull/48) so people can test on Sierra with the replacement method, and I think that SpinLock should be investigated as a potential bottleneck for the entire runtime.

**Comment by conradev** [comment]
Unloading `ntpd` does not fix the issue for me on Sierra Beta 3.

**Comment by KenanSulayman** [comment]
@conradev it does fix it, but only after a factory reset.

**Comment by glynjackson** [comment]
Hi @RnbWd thank you for the fix. I can also confirm that unload of ntpd resolved the same issue for me.

**Comment by mattrobenolt** [comment]
Seems to be completely resolved since 1.12 without needing to unload ntpd. :+1:

**Comment by RowanKaag** [comment]
I can confirm that `Docker version 1.12.0, build 8eab29e`, `stable` channel on `macOS Sierra - Developer Preview 3` is working perfectly. Didn't have trouble with `docker beta 20`, `beta` channel on `macOS Sierra - Developer Preview 3` either.

**Comment by thaJeztah** [comment]
Thanks all! I'll go ahead and close this as it appears to be fixed in 1.12.0

**Comment by jianbin-wei** [comment]
Can we get some idea what is the issue and fix or some reference to find related information?

**Comment by johnjamesjacoby** [comment]
No change in macOS Sierra Beta 4 (16A270f). Unloading `ntpd` is still required.

**Comment by RowanKaag** [comment]
@johnjamesjacoby have you tried factory reset in the GUI?

**Comment by johnjamesjacoby** [comment]
@RowanKaag I have no idea anymore; it crashes immediately on start-up on beta 4 for me now, so probably something else is broken somewhere.

See: https://github.com/docker/for-mac/issues/102

**Comment by johnjamesjacoby** [comment]
> @johnjamesjacoby have you tried factory reset in the GUI?

Yes, a few times. Also tried Uninstalling and reinstalling a few times, too.

**Comment by glynjackson** [comment]
Docker on Mac os beta 4 crashes on startup since updating I've commented here: https://forums.docker.com/t/fatal-error-while-using-docker-v-1-11-2-beta15/15267/7

**Comment by johnjamesjacoby** [comment]
Thanks @glynjackson for linking that here.

**Comment by essobi** [comment]
sudo launchctl unload /System/Library/LaunchDaemons/org.ntp.ntpd.plist <---

Upon investigating that I see the following Chrony conf on moby..
> cat /etc/chrony/chrony.conf 
server 192.168.65.1 trust iburst minpoll 2
makestep 0.5 -1
keyfile /etc/chrony/chrony.keys
driftfile /var/lib/chrony/chrony.drift
cmdport 0
moby:~# ls -ld /etc/chrony/chrony.keys
ls: /etc/chrony/chrony.keys: No such file or directory
moby:~# ls -la /etc/chrony/
total 4
drwxr-xr-x    2 root     root            60 Aug  5 02:08 .
drwxr-xr-x   32 root     root          1360 Jul 28 21:33 ..
-rw-r--r--    1 root     root           140 Aug  5 02:42 chrony.conf
moby:~# 

There's no keyfile... What's chrony's behaviour where there's no key file and no commandkey directive exists?  I don't see that behaviour documented anywhere I've looked (in the last 15 minutes..)

https://docs.fedoraproject.org/en-US/Fedora/18/html/System_Administrators_Guide/sect-Security_with_chronyc.html

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System_Administrators_Guide/sect-Understanding_chrony_and-its_configuration.html

https://chrony.tuxfamily.org/manual.html#keyfile-directive

It's definitely running..

1459 chrony     0:00 /usr/sbin/chronyd -f /etc/chrony/chrony.conf
1459    /usr/sbin/chronyd       socket:[18114]
1459    /usr/sbin/chronyd       socket:[18117]
1459    /usr/sbin/chronyd       /dev/urandom


Currently booted on latest 10.12 and latest docker beta with stock install, macOS ntp disabled, osx Docker startup at login disabled, manually opening once I'm logged it. 


 Catches the same initial crash at startup or login mentioned by @glynjackson 


Also took a hard power-off event and booted up to a corrupted .qcow image at one point.  Had to rm the qcow to enable starting again, once diagnosed that it was corrupt with 

/Applications/Docker.app/Contents/Resources/bin/docker-diagnose 

Additionally, if no one has figured out how to get to the moby/dom1/Xhyve booted machine... 

sudo screen ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty 

seems to do fine...

**Comment by justincormack** [comment]
It seems Sierra beta 4 requires Go 1.7 which is out next week.

**Comment by mattrobenolt** [comment]
I assume related to https://github.com/golang/go/issues/16570 ? Hopefully Go team will backport into another 1.6.4 release. Assuming Docker doesn't want to compile against 1.7 the day it's released. :)

**Comment by codeofsumit** [comment]
I'm on Sierra Public Beta 5 and Docker Version 1.12.1-rc1-beta23 and I have lots of errors.
It errors when trying to factory reset. It errors a couple of times on startup (gotta restart every time). And when it doesn't error out, it's "starting docker" indefinitely.

Sadly this did not help:
`sudo launchctl unload /System/Library/LaunchDaemons/org.ntp.ntpd.plist`

**Comment by jianbin-wei** [comment]
@codeofsumit, maybe try those described at https://github.com/docker/for-mac/issues/64?

**Comment by codeofsumit** [comment]
thanks I'll comment in that issue.

**Comment by clatko** [comment]
Sierra dev beta 7 (16A304a) works fine with Docker version 1.12.1-rc1-beta23. I tried none of the proposed solutions above - it just works.

**Comment by johnjamesjacoby** [comment]
> Sierra dev beta 7 (16A304a) works fine with Docker version 1.12.1-rc1-beta23 

I'm about to test this now. It definitely is not better with 1.12.0.

<img width="613" alt="screen shot 2016-08-24 at 00 53 01" src="https://cloud.githubusercontent.com/assets/88951/17919834/df620810-6995-11e6-94e5-9bda3ff00cdd.png">

**Comment by johnjamesjacoby** [comment]
After installing 1.12.1-rc1-beta24, Docker immediately crashed on start-up, but hasn't since.

> Version 1.12.1-beta24 (build: 11508)

**Comment by justincormack** [comment]
Which Sierra beta version was that?

**Comment by johnjamesjacoby** [comment]
See above:

> Sierra dev beta 7 (16A304a)

**Comment by lougreenwood** [comment]
No improvement for me, Sierra dev beta 7 (16A304a) and latest Docker beta: Version 1.12.1-beta24 (build: 11525)

* Docker doesn't start
* Various crashes as previously described here
* Factory restore fails

**Comment by essobi** [comment]
I'm on both of the latest alphas of each and still experience random crashes in the cli of docker/machine/compose.. worked around most of the Xhyve issues I had. 

--SOB

**Comment by fewspider** [comment]
docker ps not work. 16A304a. cry QAQ

**Comment by lougreenwood** [comment]
Looks like it may be working on latest Sierra build, I'm hesitant to say it's fixed for me as my experience is that it could break with a  restart, but so far, it seems ok - I'm building an image as I type this. :)

Mac OS Sierra developer beta 8 (16A313a)

Docker Version 1.12.1-beta24 (build: 11525)

Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      linux/amd64
 Experimental: true

**Comment by viral-1** [comment]
I am running Sierra version 10.12 and Docker 1.12.0  

Docker says it is running... but at the command prompt... the following commands just hang:
docker images
docker ps
docker run 
docker start

Out of frustration... I have installed virtual box and run Linux to get docker working correctly on my Mac.

**Comment by saeioul** [comment]
I'm having similar issues. Sometimes docker crashes as @johnjamesjacoby shared. Sometimes docker will not restart and clearing the docker elements in library won't solve it. Reinstalling does.

I understand os sierra is still beta software, but please investigate further guys.

**Comment by lougreenwood** [comment]
@viral-1 & @saeioul - Have either of you updated to the latest developer build of Sierra (beta 8 - 16A313a) - Docker for Mac beta is running fine on Sierra for me now.

**Comment by MartinAlex12** [comment]
guys, even if your mac fits minimum system requirements for macOS Sierra, you should prepare your Mac for an update. Here is a useful guide how to prepare - https://nektony.com/blog/prepare-for-macos-sierra-update

**Comment by wedgeV** [comment]
I'm on beta 8 with docker 1.12.1-beta25 (11807), `docker build` still doesn't work for me. Just sits there hanging forever.

**Comment by h3smith** [comment]
I upgraded to macOS Sierra GM last night and getting "vmstatementevent" crash regularly.

**Comment by Tuxity** [comment]
Same as @h3smith ! It crash without doing anything.

![screen shot 2016-09-09 at 9 16 27 am](https://cloud.githubusercontent.com/assets/31608/18390113/8cce15a4-766e-11e6-972f-13308d3259cc.png)
![screen shot 2016-09-09 at 9 20 18 am](https://cloud.githubusercontent.com/assets/31608/18390150/aba4b6a4-766e-11e6-8cf8-4f7061751e95.png)

**Comment by jaspertandy** [comment]
GM is quite crashy for me with 1.12.0-a 11213 but clearing with `ps aux | grep docker | awk '{print $2}' | xargs kill` and restarting from the binary fixes it for me. I'm not getting any error messages when it crashes though.

**Comment by h3smith** [comment]
@Tuxity same here. It is completely unusable - not even a suitable log given to diagnose. 

I've uninstalled, reinstalled, and still have issues.

**Comment by lougreenwood** [comment]
No problem for me 10.12 GM:

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by Tuxity** [comment]
When I can launch Docker and when I click on `Diagnose & Feedback` after a fresh start (killing all remaining process), it give me that:

```
Docker for Mac: version: mac-v1.12.0.1
OS X: version 10.12 (build: 16A319)
logs: /tmp/EB1B4025-FE6B-4586-8DA9-869D0542661C/20160909-093136.tar.gz
failure: com.docker.osxfs is not running
[ERROR]  docker-cli
         docker ps failed
[OK]     app
[OK]     moby-syslog
[OK]     disk
[OK]     virtualization
[OK]     system
[OK]     menubar
[ERROR]  osxfs
         com.docker.osxfs is not running
[OK]     db
[OK]     slirp
[OK]     moby-console
[OK]     logs
[OK]     vmnetd
[OK]     env
[OK]     moby
[OK]     driver.amd64-linux
```

**Comment by arr-ee** [comment]
Same diag output as for Tuxity, diag id 47A87AC7-6CBE-4FD4-9D18-5F82386BD54B

**Comment by l0rda** [comment]
@Tuxity same for me with latest docker on Sierra GM.

**Comment by Tuxity** [comment]
@arr-ee @l0rda uninstall everything and use the latest beta instead of release one. I did that and now everything is okay 👌

**Comment by kennygunie** [comment]
My problem docker (1.12.0-a build: 11213) with sierra (10.12 GM) is fixed with this:

1. Stop docker

2. Backup containers: Rename `~/Library/Containers/com.docker.docker/Data` to `~/Library/Containers/com.docker.docker/Data.bak`

3. Launch docker => docker launch problem fixed

4. Stop Docker

5. Copy `~/Library/Containers/com.docker.docker/Data.bak/database` to `~/Library/Containers/com.docker.docker/Data/database`

6. Relaunch Docker

**Comment by justincormack** [comment]
There will be a new beta in a few days that we hope should fix all the
Sierra issues.

**Comment by sivabudh** [comment]
Sierra Island officially out now. Is Sierra safe with the latest Docker beta now?

**Comment by thaJeztah** [comment]
@sivabudh afaik, all _known_ issues were addressed (But of course, Sierra itself is still fresh)

**Comment by joshuatalb** [comment]
I updated to MacOS Sierra this morning, and all seems well minus one minor setback. The Docker daemon didn't start on system boot, but double-clicking the Docker.app in the Applications folder seems to kick it back into life. No issues other than that (hopefully!)

**Comment by justincormack** [comment]
Yes the autostart didn't work for me either, guessing it needs to re
register after OS upgrade.

**Comment by sivabudh** [comment]
Just want to add that we upgraded some of our Macs and haven't run into any blocking issues so far. So we are happy!

**Comment by tectoro** [comment]
@kennygunie Thanks for the tip. I just updated to Sierra and docker was stuck in starting. I did a fresh install but no luck. Installed go 1.7. No change. Finally, followed your tip and docker is up now.

**Comment by pa-de-solminihac** [comment]
I chose to *uninstall docker* (following instructions found here: https://therealmarv.com/how-to-fully-uninstall-the-offical-docker-os-x-installation/)

Then I installed docker-beta from homebrew:
```
brew tap caskroom/versions
brew cask install docker-beta
```
It's ok now.

**Comment by ashishagarwal15** [comment]
This combination worked for me - Sierra OS 10.12.1 and Docker version 1.12.6

**Comment by thaJeztah** [comment]
**Docker for Mac now fully supports macOS Sierra**. Follow the installation instructions from the documentation https://docs.docker.com/docker-for-mac/ to get it installed.

Since this issue is resolved, and this is specific to Docker for Mac (not the "docker engine"), I'm going to lock this issue to prevent it collecting new issues that go unnoticed by the Docker for Mac team.

If you still have issues running Docker for Mac on Sierra, please open an issue in the Docker for Mac issue tracker; https://github.com/docker/for-mac/ so that the Docker for Mac team can look into that.
