### ISSUE TITLE
lxcfs mounted cgroup mgr causes `docker run` failure with user-namespace enabled daemon

### ISSUE THREAD

**Issue by estesp** [docker/docker#24834]
There have been several reports of "container command not found" errors when attempting to run containers on a user-namespaces enabled Docker daemon.

Given the lack of clarity in the error message, there could be multiple issues hidden by this generic error, but I was able to reproduce this myself in a newly installed Ubuntu 16.04 VM that happened to install the lxc components by default (which I don't have installed on a physical 16.04 system).

In this particular case, the existence of the cgroup mounts for lxcfs in `/proc/self/mountinfo` is causing the issue, as the codepath in libcontainer for `GetAllPids()` will use a parsed version of this information to find cgroup root paths, and in the case where it finds the 'lxcfs' variant, will try an `os.Stat` of this root path, and get an `EPERM` given the process is inside a user namespace at this point, and has no read access to that path.  Specifically the [code here in **libcontainer/cgroups/fs/apply_raw.go** performs the syscall](https://github.com/opencontainers/runc/blob/master/libcontainer/cgroups/fs/apply_raw.go#L85-L92) which gets permissions failures.

I'm not sure why I don't get this failure when using `runc` by itself (on the same system) so I'm opening the issue in docker repo first until we resolve why.

I can get the error to disappear by stopping the lxcfs service and unmounting the cgroup mounts under `/run/lxcfs`. I did find when searching that @hallyn said there is a correct path rooted under `/var/lib` for the cgroup hierarchy instead of trying to look at `/run/lxcfs`, but in general I guess I'm curious if we (Docker engine) should be trying to use the non-lxcfs cgroup mounts that already exist and ignore the lxcfs? At this point I'm at the end of my cgroup knowledge, so I'll let others tell me :)

**Comment by hallyn** [comment]
This is also causing an issue for libvirt.  As I've mentioned in
https://github.com/lxc/lxcfs/issues/123 lxcfs could start doing the
cgmanager trick of running in a custom rootfs in a ms_private
namespace to hide those mounts, but that does complicate things.

**Comment by brauner** [comment]
Should be fixed by https://github.com/lxc/lxcfs/pull/124.

**Comment by estesp** [comment]
I'm going to close this as there aren't any code changes in Docker necessary if lxc has solved the issue. Of course, until distros get an updated lxc this issue might appear from time to time, but hopefully this issue can be informational to those still hitting the problem until the lxc fix is fully propagated to users.

**Comment by estesp** [comment]
For posterity and those who may come across this in the future, here's some information on handling the clash until LXC updates are available in your distro or the next release: https://gist.github.com/estesp/e37b06e51384fa0ad6067af42a693925

**Comment by brauner** [comment]
Removal of `lxcfs` and other tools is not required.

We have released `lxcfs 2.0.3`. It's available for `Ubuntu 16.04`. For other `Ubuntu` releases the `PPA` https://launchpad.net/~ubuntu-lxc/+archive/ubuntu/lxcfs-stable can be used. For other distros the new source is available at https://launchpad.net/ubuntu/+source/lxcfs/2.0.3-0ubuntu2.

**Comment by estesp** [comment]
Thanks @brauner ; had no idea there would be a new release so soon. It is still not in the 16.04 officially released repos yet (just checked), but as soon as it is, I will update my gist pointing to the update and mention that for other distros/platforms, look for the 2.0.3 release update or get it from the URLs you provided.

**Comment by CRTX** [comment]
Somewhat related but I can't seem to use this feature when it involves another mounted drive.

Using the PPA with lxcfs 2.0.3 and docker service `ExecStart=/usr/bin/dockerd -H fd:// --userns-remap=Default` works under the default `/var/lib/docker directory`. However my SSD doesn't have that much space so I tried using the `--graph` parameter for docker to store the files in another drive.

Using the following:
`ExecStart=/usr/bin/dockerd -H fd:// --userns-remap=Default --graph /media/user/somedrive/docker`

Gives me the following error when I do a `docker run --rm hello-world` command.
`docker: Error response from daemon: oci runtime error: rootfs_linux.go:42: preparing rootfs caused "permission denied".`

docker folder is owned by `root`, is this permission related or another bug?

**Comment by estesp** [comment]
@CRTX : that is a permission bug because of more limited permissions/access to an existing directory in the provided path to `--graph`. Would you mind opening a new issue for that? The question will be do we want to (and will users accept) the Docker daemon changing permissions on an existing path for (root dir) access to work via a user namespaced process?
