### ISSUE TITLE
nil event timestamp errors being logged in libcontainerd

### ISSUE THREAD

**Issue by jhorwit2** [docker/docker#24909]
**Output of `docker version`:**

```
Client:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.2
 Git commit:   2debfe8-unsupported
 Built:        Thu Jul 21 19:54:55 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.25
 Go version:   go1.6.2
 Git commit:   2debfe8-unsupported
 Built:        Thu Jul 21 19:54:55 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 13
 Running: 0
 Paused: 0
 Stopped: 13
Images: 6
Server Version: 1.12.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 29
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay bridge null
Swarm: active
 NodeID: 6jep2hmzfkodrqojsqqga7py1
 Is Manager: true
 Managers: 1
 Nodes: 1
 CA Certificate Hash: sha256:d666411f2f7ab4d85e489a212acc3daeaaf825ab0319bbee031125b5f29cba89
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Debian GNU/Linux 8 (jessie) (containerized)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.82 GiB
Name: 8c38cdbeba5d
ID: M5T3:3AGJ:TIMX:HUPP:JFFB:4FOT:YZQH:MDSX:QN73:RXCM:W35G:7ZEP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 27
 Goroutines: 123
 System Time: 2016-07-21T20:47:04.0382289Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Run image w/o health check (idk if related but pops up with this)
```
echo 'FROM busybox
HEALTHCHECK NONE
CMD top' | docker build -t test_none -
```
2. Look at daemon logs

**Describe the results you received:**

`ERRO[0077] libcontainerd: failed to convert event timestamp: "timestamp: nil Timestamp"`constantly popping up. 

**Describe the results you expected:**

No errors converting timestamps

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
ping @mlaventure @tiborvass I think you were discussing this earlier

**Comment by mlaventure** [comment]
could you share the output of `docker-containerd --version` ?

**Comment by jhorwit2** [comment]
@mlaventure seems fixed in master now. Going to close this out.

**Comment by depay** [comment]
@thaJeztah @mlaventure @tiborvass this problem still exists on my host..

```
# docker info
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 1
Server Version: 1.12.0
Storage Driver: devicemapper
 Pool Name: docker-8:3-2148190310-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 396.6 MB
 Data Space Total: 107.4 GB
 Data Space Available: 107 GB
 Metadata Space Used: 1.278 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /data/docker_1_11_2/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /data/docker_1_11_2/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay host null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.13.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 31.25 GiB
Name: 10.15.184.152
ID: STPN:AASD:QGNP:VKYA:NKH2:D4FT:RBDP:JQ7J:J7IJ:5ZGE:AXCD:BTSA
Docker Root Dir: /data/docker_1_11_2
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```
using docker 1.12.0 with the latest master of containerd(1b3a81545ca79456086dc2aa424357be98b962ee) and runc(7221e387826c9918fa9fd6e7975baf4d30c8fa54).

`docker run` works, but `level=error msg="libcontainerd: failed to convert event timestamp: \"timestamp: nil Timestamp\""` appears in docker log.

**Comment by mlaventure** [comment]
@depay could you share the logs?

**Comment by depay** [comment]
@mlaventure , i've changed to the specific runc & containerd, then the warning disappeared. thanks !

**Comment by mlaventure** [comment]
@depay glad to hear, thanks for letting us know
