### ISSUE TITLE
docker: Error response from daemon: oci runtime error: apparmor failed to apply profile: no such file or directory.

### ISSUE THREAD

**Issue by tomlankhorst** [docker/docker#25488]
Trying to use Docker inside an LXC container. 
Host OS: Ubuntu 16.04
Guest OS: Ubuntu 16.04 (LXC)

I'm using Vagrant to manage the creation of the machine (box: https://vagrantcloud.com/techtown/boxes/ubuntu-16.04-lxc)

**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 10
 Running: 0
 Paused: 0
 Stopped: 10
Images: 2
Server Version: 1.12.0
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name: vagrant-base-xenial-amd64
ID: SUDX:2KO3:3MTH:U4JW:GVCO:LIFS:33KF:3XUI:SFLI:JWXN:HDBZ:GOA4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on Vagrant Ubuntu 16.04 LXC container (techtown/ubuntu-16.04-lxc)

**Steps to reproduce the issue:**
1. `docker run hello-world`

**Describe the results you received:**
`docker: Error response from daemon: oci runtime error: apparmor failed to apply profile: no such file or directory.`

**Describe the results you expected:**
`Hello World`

**Additional information you deem important (e.g. issue happens only occasionally):**
AppArmor service status:

```
● apparmor.service - LSB: AppArmor initialization
   Loaded: loaded (/etc/init.d/apparmor; bad; vendor preset: enabled)
   Active: active (exited) since Mon 2016-08-08 12:16:59 UTC; 9min ago
     Docs: man:systemd-sysv-generator(8)
```

AppArmor verbose status:

```
apparmor module is loaded.
5 profiles are loaded.
5 profiles are in enforce mode.
   /usr/bin/lxc-start
   lxc-container-default
   lxc-container-default-cgns
   lxc-container-default-with-mounting
   lxc-container-default-with-nesting
0 profiles are in complain mode.
0 processes have profiles defined.
0 processes are in enforce mode.
0 processes are in complain mode.
0 processes are unconfined but have a profile defined.
```

**Comment by thaJeztah** [comment]
Are you running docker directly on the host, or inside an LXC container? (Sorry, got a bit confused by your description)

**Comment by tomlankhorst** [comment]
Docker is running inside the LXC container. I will summarise the situation in the opening post.

**Comment by podarok** [comment]
`sudo service docker restart`

helped us

**Comment by gpampara** [comment]
Having the exact same issue

**Comment by gpampara** [comment]
Just an update that I managed to get the hello-world container to actually run. I needed to specify the apparmor profile explicitly.

@tomlankhorst could you try this command to see if it works for you?

    docker run --security-opt apparmor=lxc-container-default hello-world

All I can assume, based on the docs that I've been reading, is that the default profile that the client is looking for is `docker-default`, which then results in the `no such file or directory` message.

If this is then a valid "fix" is there a way to specify what the default apparmor profile should then be for docker?

**Comment by tomlankhorst** [comment]
Will try in a couple of days. I'm on holiday currently so not able to...

**Comment by benderalex** [comment]
docker run --security-opt apparmor=lxc-container-default hello-world
some problem - 
docker: Error response from daemon: oci runtime error: apparmor failed to apply profile: no such file or directory.

**Comment by ragingnerd** [comment]
```sudo apt-get install apparmor ``` followed by ```sudo service docker restart``` helped me

**Comment by no7dw** [comment]
agree with @ragingnerd . it helps. thx

**Comment by kxcf** [comment]
Similar to @ragingnerd , I solve this by following commands:
```shell
sudo rm -rf /etc/apparmor*
sudo apt install apparmor --reinstall
sudo service apparmor restart
sudo service docker restart
```

**Comment by kaorukobo** [comment]
Thanks, @kxcf. On my environment (inside not LXC but KVM), just `sudo service apparmor restart` helped me. (Docker 1.12.3)

**Comment by thaJeztah** [comment]
Looks like this issue is resolved for everyone here, so I'll go ahead and close

**Comment by bradcondo** [comment]
I just had the same issue arise on 17.03.0-ce, build 3a232c8, and reinstalling/restarting apparmor did not solve it. The container was a swarm service task, so what ended up solving it for me was killing the container and having a new task created on the same host. I was getting the error when attempting to docker exec into the running container.

**Comment by bartmeuris** [comment]
Same as @bradcondo here. `docker exec -ti <container> /bin/bash` with 17.03.0-ce build 60ccb22 on Ubuntu 16.04.2 (4.4.0-64-generic #85-Ubuntu kernel) results in:

```
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "apparmor failed to apply profile: no such file or directory"
```
This is what appears in `syslog`:

```
Mar 22 17:33:54 servername kernel: [1311510.080456] audit: type=1400 audit(1490200434.801:62): apparmor="DENIED" operation="change_onexec" info="label not found" error=-2 profile="unconfined" name="docker-default" pid=25840 comm="runc:[2:INIT]"
Mar 22 17:33:54 servername dockerd[4558]: time="2017-03-22T17:33:54.828388511+01:00" level=error msg="Error running exec in container: rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused \"apparmor failed to apply profile: no such file or directory\"\n"
Mar 22 17:33:54 servername dockerd[4558]: time="2017-03-22T17:33:54.828790691+01:00" level=error msg="Handler for POST /v1.26/exec/e19f8ffda1792d4c1c70f7b056f04d30bbbb89b6a2dfec54ce9c5a24483ac33d/resize returned error: rpc error: code = 2 desc = containerd: process not found for container"
```

This appears in `kern.log`:

```
Mar 22 17:33:54 servername kernel: [1311510.080456] audit: type=1400 audit(1490200434.801:62): apparmor="DENIED" operation="change_onexec" info="label not found" error=-2 profile="unconfined" name="docker-default" pid=25840 comm="runc:[2:INIT]"
```

Reinstalling and restarting apparmor didn't work. This has worked before, it just stopped working. Restarting `docker` itself on this machine is not possible at the moment.

**Comment by thaJeztah** [comment]
@bradcondo @bartmeuris there was a second issue with reloading the profiles, when using `docker exec`; this issue is resolved through https://github.com/docker/docker/pull/31773, and will be in the upcoming docker 17.03.1 patch release (which should go out hopefully later this week)

**Comment by kz12123** [comment]
Steps above didnt work after the latest docker update on my lxc-->docker setup. Following fixed it:

sudo apt-get purge apparmor
sudo apt-get purge apparmor-profiles
sudo apt-get purge apparmor-utils

sudo apt-get install apparmor-utils
sudo apt install apparmor-profiles apparmor-profiles-extra vim-addon-manager

reboot
