### ISSUE TITLE
Execute syscall.NETLINK_XFRM from inside a container

### ISSUE THREAD

**Issue by jberggg** [docker/docker#27188]
Hi

I'm searching for a way how to execute syscall.NETLINK_XFRM from inside a container.

I tried to start the container with --privileged mode, without luck. I tried to run the container with `--security-opt seccomp=unconfined` as described in the [docs](https://docs.docker.com/engine/security/seccomp/) and also tried to extend the default docker profile by adding`"netlink_xfrm"` to the by default allowed syscall list (line 360 in the default.json), without success.

Can you tell me how I can make this syscall work? Is the seccomp profile the right way how to tackle that and if so, where and how should I specify the rule for this syscall?

Thank you for your help!

**Comment by justincormack** [comment]
Hi, NETLINK_XFRM is not a syscall, it is a constant used in the `netlink` interface. Netlink is a special type of socket that communicates with the kernel. Unfortunately it is not well documented and there are not many libraries that support it. You do not need any special capabilities to read from netlink sockets, but you may need `ca_net_admin` to make changes.

**Comment by AlessandroEmm** [comment]
We should maybe say what we want to achieve: We are using Docker in Docker for CI scenario, where the internal docker host/daemon sets up encrypted networks. While we can successfully create encrypted networks on the outer docker, we cannot on the internal. Obviously something is prohibited or missing (mount). Can you give us any hints what that could be @justincormack ?

Thanks a lot.

**Comment by justincormack** [comment]
Can you say how you create the networks exactly?

**Comment by jberggg** [comment]
I'm sorry, we were not precise enough. We can create the networks, overlay networks when swarm is initialised  (scope swarm), but we cannot join a container to the network. When running docker inspect against this container it shows the error message:

`"Error": "cannot join secure network: required modules to install IPSEC rules are missing on host"`

which seems to be "caused" by:

```
if n.secure && !nlh.SupportsNetlinkFamily(syscall.NETLINK_XFRM) {
		return fmt.Errorf("cannot join secure network: required modules to install IPSEC rules are missing on host")
	}
```
https://github.com/docker/docker/blob/b248de7e332b6e67b08a8981f68060e6ae629ccf/vendor/src/github.com/docker/libnetwork/drivers/overlay/joinleave.go

**Comment by AlessandroEmm** [comment]
Adding to that: we tried with --privileged + --cap-all + --net=host already so I guess thats about as liberal as we can be. :-)

**Comment by justincormack** [comment]
Can you be more explicit about exactly how you are doing this, it would
help.

**Comment by AlessandroEmm** [comment]
OK so first things first:

1. We start a docker container on the Linux Host (CentOS in our Case).
2. We start an independent docker daemon inside this container
3. We elect him as a leader of a newly built swarm cluster
4. We create a swarm level network with -o encrypted
5. We start a Container (Service) on the internal docker instance and bind it to the created network. 

Et voilà, we run into that error.

**Comment by aboch** [comment]
@AlessandroEmm 

Have you tried start a debian container instead ?
In there the required moduels are for sure present:

```
$ docker run --rm -it  --privileged debian 
root@b2b1a6b64ce1:/# ip xfrm state add src 192.168.100.156 dst 192.168.100.151 proto esp spi "0xf728c61e" reqid "0x718a1fa4" mode tunnel auth sha256 "0x1e7c9d60193d52c5f43eed83f60ddaa2a4afebf7097684c297fb0948dd8a9625" enc aes "0x0ad65db6033527e74fab91b75f65848b4122fcd0fa7121553d8c6eb0657be6ff"
root@b2b1a6b64ce1:/# 
root@b2b1a6b64ce1:/# ip xfrm state 
src 192.168.100.156 dst 192.168.100.151
	proto esp spi 0xf728c61e reqid 1904877476 mode tunnel
	replay-window 0 
	auth-trunc hmac(sha256) 0x1e7c9d60193d52c5f43eed83f60ddaa2a4afebf7097684c297fb0948dd8a9625 96
	enc cbc(aes) 0x0ad65db6033527e74fab91b75f65848b4122fcd0fa7121553d8c6eb0657be6ff
	sel src 0.0.0.0/0 dst 0.0.0.0/0 
root@b2b1a6b64ce1:/# 
```

When initializing the netlink handler, libnetwork checks if the required modules for xfrm are available on the system via modprobe. If not it does not initialize the xfrm netlink socket.
Many containers images either do not have the required `xfrm_algo` and `xfrm_user` moduels builtin, or enabled or they do but they do not have the infra needed for modprobe to verify their presence (See https://github.com/docker/libnetwork/issues/1439)

**Comment by AlessandroEmm** [comment]
@aboch 

I guess checking for the "syscall" XFRM should not be dependant on linux distribution in the container or should it? After all the parent OS/Kernel should have the modules loaded, if there were userland tools needed to detect XFRM-ability i'd be all ears. :-)

**Comment by justincormack** [comment]
The modules were missing from Docker for Mac. They should be in the next beta release, scheduled for tomorrow. It seems to work with @aboch 's test above, so I think this should be resolved.

**Comment by justincormack** [comment]
@AlessandroEmm  the beta has just been released - can you see if it fixes your issue?

**Comment by jberggg** [comment]
@justincormack We installed Docker for Mac Version 1.12.2-beta28 (12906). Unfortunately we still get the error `"Error": "cannot join secure network: required modules to install IPSEC rules are missing on host",`. 

Here are the details of the network we try to join:
```
[root@5b59f32c6875 /]# docker network inspect 5k9ztlas6lvg
[
    {
        "Name": "Shared",
        "Id": "5k9ztlas6lvgzj6pabxmoe69j",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.11.0.0/16",
                    "IPRange": "10.11.0.0/16",
                    "Gateway": "10.11.0.1"
                }
            ]
        },
        "Internal": false,
        "Containers": null,
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "257",
            "encrypted": ""
        },
        "Labels": {
        }
    }
]
```

I gave the suggestion of @aboch a try and let the dind engine run inside a debian container with privileges (on docker for mac beta, version stated above).  Then I initialised swarm and created an encrypted overlay network. when i connect a service to this overlay network, it throws the error mentioned before.
