### ISSUE TITLE
Inconsistent Dockerfile behavior between Windows Containers and Linux

### ISSUE THREAD

**Issue by MichaelSimons** [docker/docker#27545]
**Description**

It appears the Windows Containers behavior of the `COPY` command is slightly different than on Linux when the destination is `.`

**Steps to reproduce the issue:**
1. Get a working Windows Container environment.
2. Create a directory with some files with one of them named `project.json`
3. Add the following Dockerfile to the directory.  Note:  This is a simplified Dockerfile.  In the real usage there are commands in between the COPY commands that don't need to be re-run if the project.json doesn't change.

```
FROM microsoft/nanoserver

WORKDIR app
COPY project.json .
COPY . .
```

**Describe the results you received:**
Output of building is:

```
Sending build context to Docker daemon 6.144 kB
Step 1/4 : FROM microsoft/nanoserver
 ---> 105d76d0f40e
Step 2/4 : WORKDIR app
 ---> Using cache
 ---> 5c0466311dc7
Step 3/4 : COPY project.json .
 ---> Using cache
 ---> 0d4a942fa0c6
Step 4/4 : COPY . .
mkdir \\?\Volume{c0949f92-8c99-11e6-b9a3-adda2ced055a}\app: The system cannot find the path specified.
```

**Describe the results you expected:**
The same Dockerfile with the exception of `FROM debian:jessie` builds and produces the expected results (all files are copied into the app dir) in my Ubuntu environment.

**Additional information you deem important (e.g. issue happens only occasionally):**
There are two ways to get the Dockerfile to work on Windows Containers
1. Add `RUN mkdir c:\app` before the `WORKDIR` command
2. Change the two `COPY` destinations to `./` 

**Output of `docker version`:**

```
Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
Containers: 18
 Running: 1
 Paused: 0
 Stopped: 17
Images: 302
Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.206.amd64fre.rs1_release.160915-0644)
Operating System: Windows Server 2016 Standard Evaluation
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 1.159 GiB
Name: WIN-F6RFOUBH784
ID: R644:EESZ:OP6H:7Z62:UABL:VAFV:7TZC:BIR7:KXD7:ISDG:SP37:FXUY
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by friism** [comment]
cc @jhowardmsft

**Comment by thaJeztah** [comment]
ping @duglin @jhowardmsft PTAL

**Comment by jhowardmsft** [comment]
I think I know what's going on and believe it is probably by design on Windows. Relating to the differences between what we can and can't do depending on whether a Windows Server container or Hyper-V container. Will have to dig through notes, but I think the mkdir is the best solution. Perhaps @swernli (oof til next week) can recall the specifics better than me?

**Comment by duglin** [comment]
@jhowardmsft is the WORKDIR not creating the missing dir on Windows?
@MichaelSimons what does this show:
```
FROM microsoft/nanoserver

WORKDIR app
RUN dir c:\\
```

**Comment by MichaelSimons** [comment]
@duglin, The behavior I see is strange.

```
FROM microsoft/nanoserver:10.0.14393.321

WORKDIR app
RUN dir c:\\
```

Output - Notice how the dir layer was ignored.
```
docker build --no-cache -t test .
Sending build context to Docker daemon 2.048 kB
Step 1/2 : FROM microsoft/nanoserver:10.0.14393.321
 ---> e14bc0ecea12
Step 2/2 : WORKDIR app
 ---> Running in a7a90115d91f
 ---> eb6706f78ebc
Removing intermediate container a7a90115d91f
Successfully built eb6706f78ebc
```

This Dockerfile seems to indicate that WORKDIR created the folder.
'''
FROM microsoft/nanoserver:10.0.14393.321

WORKDIR app
RUN dir
RUN dir c:\\
'''

Output:
```
docker build --no-cache -t test .
Sending build context to Docker daemon 2.048 kB
Step 1/3 : FROM microsoft/nanoserver:10.0.14393.321
 ---> e14bc0ecea12
Step 2/3 : WORKDIR app
 ---> Running in 21c5a7bce5d5
 ---> 0264ab3ef3f3
Removing intermediate container 21c5a7bce5d5
Step 3/3 : RUN dir
 ---> Running in 52b8c9d24ae3
 Volume in drive C has no label.
 Volume Serial Number is 3E2D-5EC6

 Directory of C:\app

10/28/2016  07:46 AM    <DIR>          .
10/28/2016  07:46 AM    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  21,258,739,712 bytes free
 ---> 9bb0b71af135
Removing intermediate container 52b8c9d24ae3
Successfully built 9bb0b71af135
```

Lastly I tried this as well
```
FROM microsoft/nanoserver:10.0.14393.321

WORKDIR app
RUN dir
RUN dir c:\\
RUN dir ..
```

Output:
```
docker build --no-cache -t test .
Sending build context to Docker daemon 2.048 kB
Step 1/4 : FROM microsoft/nanoserver:10.0.14393.321
 ---> e14bc0ecea12
Step 2/4 : WORKDIR app
 ---> Running in 84c393c99a38
 ---> 7c08a04a0904
Removing intermediate container 84c393c99a38
Step 3/4 : RUN dir
 ---> Running in 073d084b8bdf
 Volume in drive C has no label.
 Volume Serial Number is 3E2D-5EC6

 Directory of C:\app

10/28/2016  07:47 AM    <DIR>          .
10/28/2016  07:47 AM    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  21,258,809,344 bytes free
 ---> 3c4cf4fc82ee
Removing intermediate container 073d084b8bdf
Step 4/4 : RUN dir c:\RUN dir ..
 ---> Running in 6c9452a933b1
 Volume in drive C has no label.
 Volume Serial Number is 3E2D-5EC6

 Directory of c:\


 Directory of C:\app

File Not Found
File Not Found

 Directory of C:\

10/28/2016  07:47 AM    <DIR>          app
10/09/2016  10:57 PM             1,894 License.txt
07/16/2016  05:20 AM    <DIR>          Program Files
07/16/2016  05:09 AM    <DIR>          Program Files (x86)
10/28/2016  07:47 AM    <DIR>          Users
10/28/2016  07:47 AM    <DIR>          Windows
               1 File(s)          1,894 bytes
               5 Dir(s)  21,295,906,816 bytes free
 ---> 83c98ddeca15
Removing intermediate container 6c9452a933b1
Successfully built 83c98ddeca15
```

**Comment by duglin** [comment]
ok that's good - so the dir is being created.
I'm sure @jhowardmsft already know what's going, but I'm curious... the error message from your original post included:
```
Step 4/4 : COPY . .
mkdir \\?\Volume{c0949f92-8c99-11e6-b9a3-adda2ced055a}\app: The system cannot find the path specified.
```
but if c:\\app is there, then is this error due to "c:" and `\\?\Volume{c0949f92-8c99-11e6-b9a3-adda2ced055a}` trying to be the same thing but something going wrong under the covers so they're not?

**Comment by jhowardmsft** [comment]
Is this client or server, and a Windows Server or Hyper-V container? Can you also post output of both docker info and version so I can repro locally.

**Comment by jhowardmsft** [comment]
Ah you have docker version. Can you also try with master (master.dockerproject.org)

**Comment by MichaelSimons** [comment]
I updated the docker version and get the same results as mentioned in the original description.

**docker version**
```
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   dd344aa
 Built:        Fri Oct 28 13:31:07 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   dd344aa
 Built:        Fri Oct 28 13:31:07 2016
 OS/Arch:      windows/amd64
 Experimental: false
```

**docker info**
```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 109
Server Version: 1.13.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.321.amd64fre.rs1_release_inmarket.161004-2338)
Operating System: Windows Server 2016 Standard Evaluation
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 733 MiB
Name: WIN-1SDS8U84JRM
ID: Y36W:OWXS:JQEV:JROL:TQ43:VQW6:IKEF:OHQD:TJMB:JMZC:SBUZ:PSBV
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by jhowardmsft** [comment]
OK, here's what I've worked out.

Note that there is a difference in behaviour between WORKDIR on Hyper-V containers and Windows Server Containers. I'll PR an update to the docs to highlight that - essentially on a Hyper-V containers, we can't mount the root filesystem on the host when starting a container, so the code in SetupWorkingDirectory() kicks in and will bail. This is unfortunately by design. But not the issue here as it's a Windows Server container.

Given this dockerfile
```
FROM nanoserver
WORKDIR c:\app
COPY project.json .
COPY . .
```

Neither WORKDIR or COPY commands start a container, at least on Windows. Think that is true for Linux too, but not certain. They are just configuration (WORKDIR) or filesystem operations (COPY). 

The code in SetupWorkingDirectory() where the working directory would be created is only invoked when, as I mentioned above, the container is started, and again only if a Windows Server container.

So given that, the third command above `COPY project.json .` is concatenating the working directory in the config with . as the target, `c:\app.` which cleans to c:\app, a file. Which you see if you dig through the windowsfilter files

```
S E:\go\src\github.com\docker\docker> dir C:\control\windowsfilter\ff92393b691dd605d3a4bd5d94073dac08363dab08b18c9ae8de
a94f93e9d9dc\Files\


    Directory: C:\control\windowsfilter\ff92393b691dd605d3a4bd5d94073dac08363dab08b18c9ae8dea94f93e9d9dc\Files


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d----l        10/5/2016   2:22 PM                Program Files
d----l        10/5/2016   2:14 PM                Program Files (x86)
d-r--l        10/5/2016   5:04 PM                Users
d----l        10/5/2016   2:22 PM                Windows
-a----       10/28/2016   9:04 AM             14 app
-a---l        10/5/2016   5:04 PM           1894 License.txt


PS E:\go\src\github.com\docker\docker>
```

So when the next command tries to execute (`COPY . .`), they are being treated as files in a directory, but the 'directory' is actually a file at this point. Hence the failure you see.

The solution (to make it compatible between both Hyper-V and Windows Server containers) is to do an explicit mkdir before the workdir. That makes it work for both scenarios.

I'm not sure if there is a bug though on Windows where the first COPY when a WORKDIR is set should be treating (even without the mkdir) the target as c:\app\project.json. It would fail I guess to copy if it did, as the c:\app directory doesn't exist, and on Hyper-V containers we couldn't create it anyway.

phew :sweat:

**Comment by jhowardmsft** [comment]
PS here's the working dockerfile which will behave consistently for both container types.

```
# escape=`

FROM nanoserver
RUN mkdir c:\app
WORKDIR c:\app
COPY project.json .
COPY . .
```

**Comment by jhowardmsft** [comment]
Fixed in https://github.com/docker/docker/pull/27884.

**Comment by ramzgt** [comment]
To quote Strong Sad of Homestar Runner ... "I'm sad that I'm crying" [about Docker for Windows]. Yeah, its still not making sense.
