### ISSUE TITLE
Installation fails on RedHat 7.3

### ISSUE THREAD

**Issue by pcgeek86** [docker/docker#28406]
@andrewhsu asked me to file this on the Docker Slack Community.

When I use `get.docker.com` to install Docker Engine on RedHat 7.3, I receive the following errors.

```
warning: /var/cache/yum/x86_64/7Server/docker-main-repo/packages/docker-engine-selinux-1.12.3-1.el7.centos.noarch.rpm: Header V4 RSA/SHA512 Signature, key ID 2c52609d: NOKEY
Public key for docker-engine-selinux-1.12.3-1.el7.centos.noarch.rpm is not installed
Importing GPG key 0x2C52609D:
 Userid     : "Docker Release Tool (releasedocker) <docker@docker.com>"
 Fingerprint: 5811 8e89 f3a9 1289 7c07 0adb f762 2157 2c52 609d
 From       : https://yum.dockerproject.org/gpg
Re-declaration of boolean virt_sandbox_use_fusefs
Failed to create node
Bad boolean declaration at /etc/selinux/targeted/tmp/modules/100/virt/cil:159
/usr/sbin/semodule:  Failed!
libsemanage.semanage_direct_install_info: Overriding docker module at lower priority 100 with module at priority 400.
restorecon:  lstat(/var/lib/docker) failed:  No such file or directory
warning: %post(docker-engine-selinux-1.12.3-1.el7.centos.noarch) scriptlet failed, exit status 255
Non-fatal POSTIN scriptlet failure in rpm package docker-engine-selinux-1.12.3-1.el7.centos.noarch

If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker ec2-user

Remember that you will have to log out and back in for this to take effect!
```

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by andrewhsu** [comment]
I'm able to reproduce the error on AWS with RHEL 7.3 instance. There are hints to what has changed in selinux here: https://bugzilla.redhat.com/show_bug.cgi?id=1388616

When I installed with RHEL 7.3 packages, stuff worked:
```
# rpm -qa|grep docker
docker-selinux-1.10.3-57.el7.x86_64
docker-rhel-push-plugin-1.10.3-57.el7.x86_64
docker-1.10.3-57.el7.x86_64
docker-common-1.10.3-57.el7.x86_64
```

The bugzilla ticket hints at `docker-selinux-1.10.3-46.el7.14.x86_64` having issues. Perhaps something changed in between? Needs investigation.

**Comment by leodotcloud** [comment]
This is very easily reproducible. The following logs are from a fresh GCE RHEL instance.

```
[root@ab-leo-test-rhel ~]# uname -a
Linux ab-leo-test-rhel 3.10.0-327.36.3.el7.x86_64 #1 SMP Thu Oct 20 04:56:07 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
[root@ab-leo-test-rhel ~]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.2 (Maipo)
[root@ab-leo-test-rhel ~]#


[root@ab-leo-test-rhel ~]#
[root@ab-leo-test-rhel ~]# curl -fsSL https://get.docker.com/ | sh
+ sh -c 'sleep 3; yum -y -q install docker-engine'
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
warning: /var/cache/yum/x86_64/7Server/docker-main-repo/packages/docker-engine-selinux-1.12.3-1.el7.centos.noarch.rpm: Header V4 RSA/SHA512 Signature, key ID 2c52609d: NOKEY
Public key for docker-engine-selinux-1.12.3-1.el7.centos.noarch.rpm is not installed
Importing GPG key 0x2C52609D:
 Userid     : "Docker Release Tool (releasedocker) <docker@docker.com>"
 Fingerprint: 5811 8e89 f3a9 1289 7c07 0adb f762 2157 2c52 609d
 From       : https://yum.dockerproject.org/gpg
warning: /etc/selinux/targeted/seusers created as /etc/selinux/targeted/seusers.rpmnew
‘/etc/selinux/targeted/modules/active/seusers’ -> ‘/etc/selinux/targeted/active/seusers.local’
/usr/libexec/selinux/selinux-policy-migrate-local-changes.sh: line 66: semanage: command not found
/usr/libexec/selinux/selinux-policy-migrate-local-changes.sh: line 66: semanage: command not found
Re-declaration of boolean virt_sandbox_use_fusefs
Failed to create node
Bad boolean declaration at /etc/selinux/targeted/tmp/modules/100/virt/cil:159
/usr/sbin/semodule:  Failed!
libsemanage.semanage_direct_install_info: Overriding docker module at lower priority 100 with module at priority 400.
restorecon:  lstat(/var/lib/docker) failed:  No such file or directory
warning: %post(docker-engine-selinux-1.12.3-1.el7.centos.noarch) scriptlet failed, exit status 255
Non-fatal POSTIN scriptlet failure in rpm package docker-engine-selinux-1.12.3-1.el7.centos.noarch
warning: /etc/selinux/targeted/modules/active/seusers.final saved as /etc/selinux/targeted/modules/active/seusers.final.rpmsave

If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker your-user

Remember that you will have to log out and back in for this to take effect!

[root@ab-leo-test-rhel ~]#
```

**Comment by runcom** [comment]
@rhatdan would you have a look at this?

**Comment by jprante** [comment]
I got the same error. After update to RHEL 7.3, docker 1.12.3-1 does not work anymore. 

```
# uname -a
Linux herakles 3.10.0-514.el7.x86_64 #1 SMP Wed Oct 19 11:24:13 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.3 (Maipo)
# yum install docker
[...]
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installieren     : docker-engine-selinux-1.12.3-1.el7.centos.noarch                                                                                                                1/2 
Re-declaration of boolean virt_sandbox_use_fusefs
Failed to create node
Bad boolean declaration at /etc/selinux/targeted/tmp/modules/100/virt/cil:159
/usr/sbin/semodule:  Failed!
libsemanage.semanage_direct_install_info: Overriding docker module at lower priority 100 with module at priority 400.
  Installieren     : docker-engine-1.12.3-1.el7.centos.x86_64                                                                                                                        2/2 
  Überprüfung läuft: docker-engine-1.12.3-1.el7.centos.x86_64                                                                                                                        1/2 
  Überprüfung läuft: docker-engine-selinux-1.12.3-1.el7.centos.noarch                                                                                                                2/2 

Installiert:
  docker-engine.x86_64 0:1.12.3-1.el7.centos                                                                                                                                             

Abhängigkeit installiert:
  docker-engine-selinux.noarch 0:1.12.3-1.el7.centos                                                                                                                                     

Komplett!
[root@herakles joerg]# systemctl start docker
Failed to start docker.service: Unit is not loaded properly: Invalid argument.
See system logs and 'systemctl status docker.service' for details.
# journalctl -u docker.service
-- No entries --
# systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: error (Reason: Invalid argument)
  Drop-In: /etc/systemd/system/docker.service.d
           └─docker.conf
   Active: inactive (dead)
     Docs: https://docs.docker.com
```

**Comment by rhatdan** [comment]
This is a bug in docker-engine-selinux.  We ship container-selinux.  docker needs to update to the upstream version.

**Comment by andrewhsu** [comment]
Digging into the `semodule` failure message during install, I see there is a difference in the spec file between `docker-selinux-1.10.3-46.el7.14.x86_64` and `docker-selinux-1.10.3-57.el7.x86_64`:

```diff
527c524
< %{_sbindir}/semodule -n -s %{selinuxtype} -i $MODULES
---
> %{_sbindir}/semodule -n --priority=200 -s %{selinuxtype} -i $MODULES > /dev/null
```

@rhatdan would this perhaps be the cause?

Also, I see an RPM for `container-selinux` for Fedora, but not one for RHEL7. I was going to put together a PR to sync up with upstream, but I don't see anything similar for the RHEL7 distro other than `docker-selinux`.

**Comment by andrewhsu** [comment]
@crosbymichael I may need some help from your experience with selinux on this issue

**Comment by rhatdan** [comment]
NO the selinux-policy package was updated in RHEL7.3, this means a boolean that we were carrying in container-selinux has been  moved to the selinux-policy package, so it needs to be removed from the container-selinux package.  Docker Inc is shipping an older version of this "docker-selinux" which still defines the boolean.

**Comment by damon-atkins** [comment]
FYI on CentOS selinux is reporting

type=AVC msg=audit(1479747374.929:1115): avc:  **denied**  { read write } for  pid=6161 comm="iptables" path=2F6465762F73686D2F666669536A654E6833202864656C6574656429 dev="tmpfs" ino=30503 scontext=system_u:system_r:iptables_t:s0 tcontext=system_u:object_r:firewalld_tmpfs_t:s0 tclass=file

Appears on boot and restart.

```
Linux box 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
CentOS Linux release 7.2.1511 (Core)
docker-engine-1.12.3-1.el7.centos.x86_64
python-docker-py-1.7.2-1.el7.noarch
docker-engine-selinux-1.12.3-1.el7.centos.noarch
```

```
Name        : docker-engine-selinux
Version     : 1.12.3
Release     : 1.el7.centos
Architecture: noarch
Install Date: Tue 22 Nov 2016 02:24:34 AM AEDT
Group       : Tools/Docker
Size        : 43725
License     : GPLv2
Signature   : RSA/SHA512, Thu 27 Oct 2016 09:59:05 AM AEDT, Key ID f76221572c52609d
Source RPM  : docker-engine-selinux-1.12.3-1.el7.centos.src.rpm
Build Date  : Thu 27 Oct 2016 08:47:09 AM AEDT
Build Host  : 719d8d68f3dc
Relocations : (not relocatable)
Packager    : Docker <support@docker.com>
Vendor      : Docker
URL         : https://dockerproject.org
Summary     : SELinux Policies for the open-source application container engine
```

**Comment by rhatdan** [comment]
Unrelated to Docker.
This is a leaked file descriptor from firewalld into iptables.

**Comment by damon-atkins** [comment]
The docker logs say it can not execute iptable commands, was not aware docker called firewalld.

**Comment by rhatdan** [comment]
I believe that docker will call out to firewalld, but I think the message you are showing is happening when firewalld starts.

**Comment by damon-atkins** [comment]
It happens if you restart docker as well. All other firewall rules work fine.  Is docker writing something to tmpfs and iptables is not allowed to read from tmpfs. The selinux messages are hard to read.

**Comment by rhatdan** [comment]
I guess docker is sending a message to firewalld, which is then execing iptables to change some rules. When firewalld executes iptables it has a file open on a tmpfs that it did not FD_CLOEXEC.

fcntl(fd, FD_SETFD, FD_CLOEXEC)

This AVC would mean nothing, since SELinux just closes the leaked file descriptor and iptables does not use it.

I wrote on Leaked file descriptors a few years back.
http://danwalsh.livejournal.com/53603.html

**Comment by damon-atkins** [comment]
They are dockers logs, saying perm denied running iptables. Not sure why docker would print in the logs an iptables command if its calling firewalld.

**Comment by rhatdan** [comment]
I am talking about the AVC above.  These messages are appearing because the kernel sends a message to the audit log.  Journald is watchin the audit subsystem and recording the AVC.  How you are seeing these in docker logs, I do not know.

**Comment by andrewhsu** [comment]
@rhatdan I've updated docker-engine-selinux to the upstream version in PR #29188 and stuff works on RHEL7.3, but is not really working with CentOS7.2. Would you know if the policies crafted for docker to work on RHEL7.3 prevent docker from working on 7.2?

Related: do you know when CentOS7.3 will be released?

**Comment by runcom** [comment]
> @rhatdan I've updated docker-engine-selinux to the upstream version in PR #29188 and stuff works on RHEL7.3, but is not really working with CentOS7.2. Would you know if the policies crafted for docker to work on RHEL7.3 prevent docker from working on 7.2?
> 
> Related: do you know when CentOS7.3 will be released?

/cc @lsm5 do you know anything about this?

**Comment by lsm5** [comment]
There was a userspace change for selinux-policy in RHEL 7.3 and afaik, that made 7.2 and 7.3 incompatible (@rhatdan can probably elaborate on this)

/etc/yum.repos.d/CentOS-CR.repo should have all the dependencies needed for 7.3. Try enabling that. It should come in CentOS-Base *soon*, but not sure when exactly :|

**Comment by rhatdan** [comment]
Yes policy was changed in RHEL7.3 that required changes in container-selinux policy.  This will probably not work on a 7.2 release.

**Comment by cpuguy83** [comment]
Just want to say the effect of this policy change is really awful for packagers.

**Comment by rhatdan** [comment]
Yes their is a basic conflict between the way RHEL packagers update and the way we update atomic packages.  Around the time of a RHEL update their will be some pain points.  Hopefully it will be smoother around 7.4 time frame.

Standard release practice would have been to have two different versions of the packages, one for 7.2 and one for 7.3.  We call these Z Streams, but that atomic/extras packages come out every 6 weeks and have a single stream.

**Comment by paultbarham** [comment]
Is there a solution here?  Hard to tell from the thread.  I'm installing RH 7.3 and encountering the same issue as initially reported.  The error happens when installing:
docker-engine-selinux-1.12.4-1.el7.centos.noarch

**Comment by cpuguy83** [comment]
1.12.4 does not/will not work on 7.3

**Comment by lsm5** [comment]
On Tue, Dec 13, 2016 at 11:49:18AM -0800, Brian Goff wrote:
> 1.12.4 does not/will not work on 7.3

could you please explain what exactly does not/will not work? I do have a RHEL
7.3 build that works and I'll rebuild it soon for CentOS

> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/docker/docker/issues/28406#issuecomment-266842077

-- 
Lokesh
Freenode: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by cpuguy83** [comment]
@lsm5 The selinux policy is not compatible with 7.3
Technically docker should work, but not with `--selinux-enabled` set on the daemon.

**Comment by paultbarham** [comment]
So, I'm following the instructions on the Docker site for installing onto Red Hat:
https://docs.docker.com/engine/installation/linux/rhel/

What steps or Linux commands need to change to get around this incompatibility with selinux?
Thanks in advance,
Paul

**Comment by paultbarham** [comment]
Does anyone know if this Bug fix published today (12/15/16) should fix the issue in this thread?
[Bug Fix Advisory] RHBA-2016:2865 Selinux-policy bug fix update

**Comment by rshariffdeen** [comment]
I was able to install docker and deploy containers, but couldn't ping two containers on the same network. Tried with linking and creating a separate bridge, IP seem to resolve but ping hangs. Can this be related to selinux update? I am using docker 1.12.5  in rhel-3

**Comment by rhatdan** [comment]
One way to see if SELinux is an issue, is to put the machine into permissive mode, if this fixes the issue, then gather the SELinux errors.

ausearch -m avc -ts recent

If this does not resolve the issue, then it is NOT an SELinux issue.  (I doubt that this is an SELinux issue).  SELinux policy defaults to blocking file system access in containers, not blocking networks.

**Comment by sandys** [comment]
@rhatdan @rshariffdeen did you guys debug this issue ? im facing a similar situation

**Comment by rshariffdeen** [comment]
@sandys I downgraded to 1.12.4 and it worked for me.

**Comment by cpuguy83** [comment]
```
type=SYSCALL msg=audit(1483631287.469:1203): arch=c000003e syscall=59 success=no exit=-13 a0=c42012a180 a1=c42012a190 a2=c4200f0c60 a3=0 items=0 ppid=27312 pid=27321 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts1 ses=4294967295 comm="runc:[2:INIT]" exe="/usr/bin/docker-runc" subj=system_u:system_r:unconfined_service_t:s0 key=(null)
type=AVC msg=audit(1483631287.469:1203): avc:  denied  { transition } for  pid=27321 comm="runc:[2:INIT]" path="/bin/sh" dev="dm-3" ino=6291585 scontext=system_u:system_r:unconfined_service_t:s0 tcontext=system_u:system_r:svirt_lxc_net_t:s0:c218,c254 tclass=process
```

This happens on 1.13-rcX in centos 7.3

**Comment by rhatdan** [comment]
This looks like runc is running directly from a systemd unit file?  We have labeled runc as container_runtime_exec_t in our latest updates which should fix this issue.

chcon -t container_runtime_exec_t /usr/bin/runc

(docker_exec_t, if you don't have container_runtime_exec_t defined)

Restart the unit file.

**Comment by cpuguy83** [comment]
@rhatdan Thanks for the quick response. Unfortunately still seeing the same error.

**Comment by cpuguy83** [comment]
`chcon -t docker_exec_t /usr/bin/dockerd` seems to do the trick.... now to figure out why it's not being set already.

**Comment by cpuguy83** [comment]
Another update on progress... for 1.13 packages to "work" (not really work, be in the same boat as  7.3) on centos 7.2 (and the like), the `selinux-policy` package must be updated, which also updates systemd and a few other libs.

With 7.3 (and updated 7.2) there's still an issue with the post-install script for the docker-engine-selinux package:

```
  Installing : docker-engine-selinux-1.13.0-0.0.20170104.122703.git43cc971.el7.centos.noarch                                                                                                                             1/1
/etc/selinux/final/targeted/contexts/files/file_contexts: Multiple same specifications for /var/lib/docker/vfs(/.*)?.
/etc/selinux/final/targeted/contexts/files/file_contexts: Invalid argument
libsemanage.semanage_validate_and_compile_fcontexts: setfiles returned error code 1.
/usr/sbin/semodule:  Failed!
libsemanage.semanage_direct_install_info: Overriding docker module at lower priority 100 with module at priority 400.
restorecon:  lstat(/var/lib/docker) failed:  No such file or directory
warning: %post(docker-engine-selinux-1.13.0-0.0.20170104.122703.git43cc971.el7.centos.noarch) scriptlet failed, exit status 255
Non-fatal POSTIN scriptlet failure in rpm package docker-engine-selinux-1.13.0-0.0.20170104.122703.git43cc971.el7.centos.noarch
```

**Comment by rhatdan** [comment]
@cpuguy83 The file context labeling in docker-selinux probably did not cover dockerd just docker.  So you need to update.  But we don't support the newer container policy on rhel7.2, only rhel7.3

We are splitting out container-selinux into a separate package from docker and should be able to handle these better.   But currently we match the packaging to the current release of the OS, rather then supporting different versions depending on the OS Version.

**Comment by cpuguy83** [comment]
Ok, I'm working on a PR that seems to fix the issues with 7.3
At the moment it's just:

<details>

```diff
diff --git a/contrib/selinux/docker-engine-selinux/docker.fc b/contrib/selinux/docker-engine-selinux/docker.fc
index fe9c58a..467d659 100644
--- a/contrib/selinux/docker-engine-selinux/docker.fc
+++ b/contrib/selinux/docker-engine-selinux/docker.fc
@@ -7,8 +7,6 @@
 /etc/docker(/.*)?		gen_context(system_u:object_r:docker_config_t,s0)
 
 /var/lib/docker(/.*)?		gen_context(system_u:object_r:docker_var_lib_t,s0)
-/var/lib/kublet(/.*)?		gen_context(system_u:object_r:docker_var_lib_t,s0)
-/var/lib/docker/vfs(/.*)?	gen_context(system_u:object_r:svirt_sandbox_file_t,s0)
 
 /var/run/docker\.pid		--	gen_context(system_u:object_r:docker_var_run_t,s0)
 /var/run/docker\.sock		-s	gen_context(system_u:object_r:docker_var_run_t,s0)
diff --git a/contrib/selinux/docker-engine-selinux/docker.te b/contrib/selinux/docker-engine-selinux/docker.te
index 999742f..bad0bb6 100644
--- a/contrib/selinux/docker-engine-selinux/docker.te
+++ b/contrib/selinux/docker-engine-selinux/docker.te
@@ -5,13 +5,6 @@ policy_module(docker, 1.0.0)
 # Declarations
 #
 
-## <desc>
-## <p>
-## Allow sandbox containers manage fuse files
-## </p>
-## </desc>
-gen_tunable(virt_sandbox_use_fusefs, false)
-
 ## <desc>
 ##  <p>
 ##  Determine whether docker can
```

</details>

Still looking to see if I can get 7.2 supported simultaneously.

**Comment by rhatdan** [comment]
You should add

/usr/bin/docker.*		--	gen_context(system_u:object_r:docker_exec_t,s0)

And maybe 
/usr/libexec/docker/docker.*	--	gen_context(system_u:object_t:docker_exec_t,s0)

**Comment by cpuguy83** [comment]
@rhatdan The /usr/bin/docker.* doesn't work because it seems there's some default policy installed that conflicts with it:

<details>

```
[root@localhost data]#  semanage fcontext -l | grep docker
/etc/docker(/.*)?                                  all files          system_u:object_r:docker_config_t:s0
/var/log/lxc(/.*)?                                 all files          system_u:object_r:docker_log_t:s0
/var/lock/lxc(/.*)?                                all files          system_u:object_r:docker_lock_t:s0
/var/lib/docker(/.*)?                              all files          system_u:object_r:docker_var_lib_t:s0
/var/lib/kublet(/.*)?                              all files          system_u:object_r:docker_var_lib_t:s0
/var/run/docker(/.*)?                              all files          system_u:object_r:docker_var_run_t:s0
/var/lib/docker/.*/config\.env                     all files          system_u:object_r:docker_share_t:s0
/etc/docker/certs\.d(/.*)?                         all files          system_u:object_r:cert_t:s0
/var/lib/docker/vfs(/.*)?                          all files          system_u:object_r:svirt_sandbox_file_t:s0
/var/lib/docker/init(/.*)?                         all files          system_u:object_r:docker_share_t:s0
/var/run/docker-client(/.*)?                       all files          system_u:object_r:docker_var_run_t:s0
/var/lib/docker/overlay(/.*)?                      all files          system_u:object_r:docker_share_t:s0
/var/run/docker/plugins(/.*)?                      all files          system_u:object_r:docker_plugin_var_run_t:s0
/var/lib/docker/containers/.*/hosts                all files          system_u:object_r:docker_share_t:s0
/var/lib/docker/containers/.*/hostname             all files          system_u:object_r:docker_share_t:s0
/usr/lib/systemd/system/docker.service             regular file       system_u:object_r:docker_unit_file_t:s0
/usr/lib/systemd/system/docker-novolume-plugin.service regular file       system_u:object_r:docker_unit_file_t:s0
/root/\.docker                                     all files          system_u:object_r:docker_home_t:s0
/usr/bin/docker                                    regular file       system_u:object_r:docker_exec_t:s0
/var/run/docker\.pid                               regular file       system_u:object_r:docker_var_run_t:s0
/var/run/docker\.sock                              socket             system_u:object_r:docker_var_run_t:s0
/usr/bin/docker-novolume-plugin                    regular file       system_u:object_r:docker_auth_exec_t:s0
/usr/lib/docker/docker-novolume-plugin             regular file       system_u:object_r:docker_auth_exec_t:s0
```

</details

Why is there docker related policy installed by default even without the docker package being installed?

**Comment by rhatdan** [comment]
It was originally installed as a part of the selinux-policy package.  Later we have moved it to container-selinux, but we still have it in rhel7. We are now overriding it in the post install script of container-selinux.

I just updated container-selinux to match the post install we are using in RHEL.

```

%post
#
# Install all modules in a single transaction
#
if [ $1 -eq 1 ]; then
    %{_sbindir}/setsebool -P -N virt_use_nfs=1 virt_sandbox_use_all_caps=1
fi
%_format MODULES %{_datadir}/selinux/packages/$x.pp.bz2
%{_sbindir}/semodule -n -s %{selinuxtype} -r container 2> /dev/null
%{_sbindir}/semodule -n -s %{selinuxtype} -d %{repo} 2> /dev/null
%{_sbindir}/semodule -n -s %{selinuxtype} -d gear 2> /dev/null
%{_sbindir}/semodule -n -X 200 -s %{selinuxtype} -i $MODULES > /dev/null
if %{_sbindir}/selinuxenabled ; then
    %{_sbindir}/load_policy
    %relabel_files
    if [ $1 -eq 1 ]; then
	restorecon -R %{_sharedstatedir}/%{repo} &> /dev/null || :
    fi
fi
```

**Comment by cpuguy83** [comment]
#29958

**Comment by mwiora** [comment]
hi all - still having the same issue on centos 7.3.1611 and docker 1.12.6 - is there a working workaround?

**Comment by rhatdan** [comment]
You can disable the docker policy on the system with

semodule -d docker
yum reinstall container-selinux
Does this give you an issue?

**Comment by cpuguy83** [comment]
Closing as this is resolved by #29959 and was backported to 1.13.0

**Comment by lordkow** [comment]
@cpuguy83 Hi,
I noticed that this issue was fixed for version 1.13.0, am I correct?
But I am trying to install docker engine 1.13.0-1 in my RedHat 7.3 VM and facing this issue:

`# rpm -Uvh docker-engine-1.13.0-1.el7.centos.x86_64.rpm
warning: docker-engine-1.13.0-1.el7.centos.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 2c52609d: NOKEY
Preparing...                          ################################# [100%]
Updating / installing...
   1:docker-engine-1.13.0-1.el7.centos################################# [100%]
/var/tmp/rpm-tmp.EmEaXO: line 8: groupadd: command not found
warning: %post(docker-engine-1.13.0-1.el7.centos.x86_64) scriptlet failed, exit status 127
`
Could you try to support me on this?

BR

**Comment by cpuguy83** [comment]
@lordkow The issue is completely unrelated and seems to be caused by the `groupadd` command not being available on your system.

**Comment by lordkow** [comment]
@cpuguy83 alright, you were right. After installing 1.13, the main problem seems to be fixed. But from docker-engine-selinux i still have some warnings:

`# rpm -Uvh docker-engine-selinux-1.13.1-1.el7.centos.noarch.rpm
warning: docker-engine-selinux-1.13.1-1.el7.centos.noarch.rpm: Header V4 RSA/SHA512 Signature, key ID 2c52609d: NOKEY
Preparing...                          ################################# [100%]
Updating / installing...
   1:docker-engine-selinux-1.13.1-1.el################################# [100%]
setsebool:  SELinux is disabled.
libsemanage.semanage_direct_install_info: Overriding docker module at lower priority 100 with module at priority 400.
libsemanage.semanage_direct_install_info: docker module will be disabled after install due to default enabled status.
`

Is this a problem? Is there anything wrong? I remember when I installed docker in redhat 7.2 i did not have any of these "warnings" with priority 100 and docker module will be disable, etc..

**Comment by cpuguy83** [comment]
There's no issue.
Also, consider upgrading to a newer version of Docker. 1.13 is old and EOL.
17.06 just uses the RH supplied `container-selinux` package from the extras repo.

**Comment by lordkow** [comment]
@cpuguy83 Oh i see then.
Thank you for the support.

I can't just update it. I am checking with our developers if there is no problem updating it.
What is guarantee is that version "Docker version 1.11.2, build b9f10c9" there is no problem.
I installed version 1.13 just to check if problem with RedHat 7.3 was solved. In my homologation and production env, we do have redhat 7.2 with docker 1.11.2.
