### ISSUE TITLE
docker --rm does not delete container after exit

### ISSUE THREAD

**Issue by frank-dspeed** [docker/docker#30341]
**Description**

Docker don't cleans up up container after close. but starts as suggested.
i add the --rm flag as also add a disown because i don't want to keep the shell open 
that leads me to think that rm don't gets executed by the daemon or why does that fail.

**Steps to reproduce the issue:**
```
docker run -it --rm --net host     --cpuset-cpus 0     --memory 512mb     -v /tmp/.X11-unix:/tmp/.X11-unix     -e DISPLAY=unix$DISPLAY     -v $HOME/Downloads:/root/Downloads     -v $HOME/.config/google-chrome/:/data     --device /dev/snd     --name chrome     jess/chrome & disown
```

**Describe the results you received:**
used --rm container don't got deleted after exiting
```
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS                     PORTS               NAMES
6e76d1638aea        jess/chrome         "google-chrome --user"   About a minute ago   Exited (0) 9 seconds ago                       chrome
frank@frank-MS-7821:~$ docker ps -l
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS                      PORTS               NAMES
6e76d1638aea        jess/chrome         "google-chrome --user"   About a minute ago   Exited (0) 13 seconds ago                       chrome
```

**Describe the results you expected:**
container should be away on exit

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   6b644ec
 Built:        Mon, 19 Dec 2016 09:20:48 +1300
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   23cf638
 Built:        Tue, 27 Sep 2016 12:25:38 +1300
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 58
 Running: 7
 Paused: 0
 Stopped: 51
Images: 380
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1010
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-59-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.6 GiB
Name: frank-MS-7821
ID: WTQP:OU5X:FHWE:DL36:FPLC:FVDS:GTPQ:KMZ6:GVHI:DH3F:PJLG:ZETF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: dockerimages
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
Local Desktop PC
```

**Comment by thaJeztah** [comment]
The `--rm` flag in docker 1.12 is implemented client side; once the connection with the container is stopped, the client does a `rm` call to cleanup the container. There are cases where this is known to not work.

Docker 1.13 moves `--rm` to the daemon, which also allows you to use `--rm` with "detached" containers (`-d`).

Could you try upgrading to 1.13 and see if that addresses your use case?

**Comment by frank-dspeed** [comment]
@thaJeztah will do thanks

**Comment by thaJeztah** [comment]
Let me close this issue for now, because I think it's addressed by docker 1.13, but happy to hear if it addresses your use case 👍

**Comment by mikedickey** [comment]
This problem also exists in Docker CS Engine for Linux 1.13.1-cs2

You can reproduce it using something as simple as this:

`docker run --rm alpine echo hello world`

Undefining DOCKER_API_VERSION "fixes" it.

**Comment by djs55** [comment]
@thaJeztah I think there's still a problem with `17.03.0-ce`. @iostat provided a repro example in the comment https://github.com/docker/for-mac/issues/1420#issuecomment-287517014 

It looks like setting the old API version `DOCKER_API_VERSION=1.24` tells the server that it shouldn't `rm` the container (because the client should do it with that API version) but the new client code isn't prepared to call `rm` any more. Presumably an old client binary would actually work as expected? Should the new client still call `rm` when using an old `DOCKER_API_VERSION`?

**Comment by thaJeztah** [comment]
@djs55 There was an issue in 17.03.0, which should be resolved by https://github.com/docker/docker/pull/31692

@mikedickey what API version does `DOCKER_API_VERSION` specify?

**Comment by softwarevamp** [comment]
still exists in Windows Docker version 17.12.0-ce, build c97c6d6

**Comment by ninjaboy** [comment]
I am experiencing the same issue on Docker for Windows:

Version 18.05.0-ce-rc1-win63 (17439)
Channel: edge
3b5a9a4

**Comment by thaJeztah** [comment]
@ninjaboy if you have steps to reproduce, could you open a new ticket with those steps?

**Comment by minatafreshi** [comment]
I think there's still a problem with docker for linux version 18.06.3-ce, build d7080c1.

**Comment by thaJeztah** [comment]
@minatafreshi Docker 18.06 reached EOL in september 2018; if you're still able to reproduce on a current (19.03 at time of writing) version, please open a new ticket with steps to reproduce
