### ISSUE TITLE
Enable multicast between containers?

### ISSUE THREAD

**Issue by benbooth493** [docker/docker#3043]
I currently have a bunch of containers configured using veth as the network type. The host system has a bridge device and can ping 224.0.0.1 but the containers can't.

Any ideas?

**Comment by hmeerlo** [comment]
Ok, so --net=host is no option, it can not be used together with --link. Has anyone tried what @defunctzombie said? Does it work? If so, why not integrate it? IMHO multicast is used by too many applications for discovery to ignore this issue.

**Comment by hmeerlo** [comment]
Ok, I gave it a try myself but to no avail. I modified the code to set the IFF_MULTICAST flag. I see the veth interfaces coming up with MULTICAST enabled, but once the interface is up multicast is gone (ip monitor all):

```
[LINK]79: vethe9774fa: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN
    link/ether a2:ae:8c:b8:6c:0a brd ff:ff:ff:ff:ff:ff
[LINK]79: vethe9774fa: <BROADCAST,MULTICAST> mtu 1500 qdisc noop master docker0 state DOWN
    link/ether a2:ae:8c:b8:6c:0a brd ff:ff:ff:ff:ff:ff
[LINK]79: vethe9774fa: <BROADCAST,MULTICAST> mtu 1500 qdisc noop master docker0 state DOWN
    link/ether a2:ae:8c:b8:6c:0a brd ff:ff:ff:ff:ff:ff
[NEIGH]dev vethe9774fa lladdr a2:ae:8c:b8:6c:0a PERMANENT
[LINK]79: vethe9774fa: <BROADCAST,MULTICAST> mtu 1500 master docker0 state DOWN
    link/ether a2:ae:8c:b8:6c:0a
[LINK]79: vethe9774fa: <NO-CARRIER,BROADCAST,UP> mtu 1500 qdisc noqueue master docker0 state DOWN
    link/ether a2:ae:8c:b8:6c:0a brd ff:ff:ff:ff:ff:ff
[LINK]79: vethe9774fa: <NO-CARRIER,BROADCAST,UP> mtu 1500 master docker0 state DOWN
    link/ether a2:ae:8c:b8:6c:0a
[LINK]79: vethe9774fa: <NO-CARRIER,BROADCAST,UP> mtu 1500 master docker0 state DOWN
    link/ether a2:ae:8c:b8:6c:0a
[LINK]Deleted 78: vethf562f68: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN
    link/ether 56:28:af:c2:e9:a0 brd ff:ff:ff:ff:ff:ff
[ROUTE]ff00::/8 dev vethe9774fa  table local  metric 256
[ROUTE][ROUTE]fe80::/64 dev vethe9774fa  proto kernel  metric 256
[LINK]79: vethe9774fa: <BROADCAST,UP,LOWER_UP> mtu 1500
    link/ether a2:ae:8c:b8:6c:0a
[LINK]79: vethe9774fa: <BROADCAST,UP,LOWER_UP> mtu 1500 master docker0 state UP
    link/ether a2:ae:8c:b8:6c:0a
[LINK]79: vethe9774fa: <BROADCAST,UP,LOWER_UP> mtu 1500 master docker0 state UP
    link/ether a2:ae:8c:b8:6c:0a
[LINK]79: vethe9774fa: <BROADCAST,UP,LOWER_UP> mtu 1500 master docker0 state UP
    link/ether a2:ae:8c:b8:6c:0a
[LINK]79: vethe9774fa: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP
    link/ether a2:ae:8c:b8:6c:0a brd ff:ff:ff:ff:ff:ff
```

**Comment by Lawouach** [comment]
I'd be intrested in helping working on this issue but, at this stage, it's unclear about the multicast support status. Does a docker container fail at being routed multicast stream at all? Or just between running containers?

**Comment by hmeerlo** [comment]
Well, the plot thickens because I overlooked @rhasselbaum comment. Multicast actually works fine between containers. It is just that the ifconfig or 'ip address show' output doesn't indicate this. I ran the exact same tests as @rhasselbaum and the test was successful. After that I tried my own solution with a distributed EHCache that uses multicast for discovery and that worked as well. So there doesn't seem to be a problem anymore...

**Comment by Lawouach** [comment]
Alright. So the stock docker seems to have multicast working between containers. I'm not sure I understand regarding the last part of your comment. More specifically, I'm wondering if multicast can be forwarded from the host to the contaienr with --net host (which is, well, expected).

**Comment by hmeerlo** [comment]
I can not confirm your question about --net host because I require --link but that combination is impossible.

**Comment by Lawouach** [comment]
As do I. Okay, I will play with it as well and report here.

**Comment by rhasselbaum** [comment]
@hmeerlo Multicast works fine between containers *on the same host*. But I think more work is needed (or a HOWTO) on getting it to work across hosts. I'm sure it would work with `--net host` but that has other drawbacks.

**Comment by Lawouach** [comment]
I finally got the time to try for myself and I was able to use multicast in the various scenarios that I was interested in:

* container to container
* host to container
* container to host

For the last two, just make sure you have the appropriate route, something along the lines:

$ sudo route add -net 224.0.0.0/4 dev docker0

This worked with the stock docker 1.3.3 without --net host.

**Comment by rivallu** [comment]
@Lawouach when you said "container to container" it's on the same host ?

**Comment by dlintw** [comment]
I require the default docker interface eth0 provide MULTICAST, and trying to patch, but it can not work.

diff --git a/vendor/src/github.com/docker/libcontainer/netlink/netlink_linux.go b/vendor/src/github.com/docker/libcontainer/netlink/netlink_linux.go
index 3ecb81f..c78cd14 100644
--- a/vendor/src/github.com/docker/libcontainer/netlink/netlink_linux.go
+++ b/vendor/src/github.com/docker/libcontainer/netlink/netlink_linux.go
@@ -713,7 +713,7 @@ func NetworkCreateVethPair(name1, name2 string, txQueueLen int) error {
        }
        defer s.Close()
 
-       wb := newNetlinkRequest(syscall.RTM_NEWLINK, syscall.NLM_F_CREATE|syscall.NLM_F_EXCL|syscall.NLM_F_ACK)
+       wb := newNetlinkRequest(syscall.RTM_NEWLINK, syscall.NLM_F_CREATE|syscall.NLM_F_EXCL|syscall.NLM_F_ACK|syscall.IFF_MULTICAST)
 
        msg := newIfInfomsg(syscall.AF_UNSPEC)
        wb.AddData(msg)

**Comment by gonberdeal** [comment]
@Lawouach I am using Docker 1.6 and adding the route you mention:

$ sudo route add -net 224.0.0.0/4 dev docker0

but my container is not capable of receving multicast. I can not use --net="host" because of its incompatibility with --link.

I have also tried to add that route inside the container but it has no effect.

Any news about this issue?

**Comment by Lawouach** [comment]
@gonberdeal Back then I had misread my results and wasn't able to receive multicast with just the route you mention. What I ended up doing (which isn't ideal but is a suitable workaround for now for my own use case) is to enslave a second physical network interface to the docker bridge.

$ brctl addif docker0 eth2
$ route add -net 224.0.0.0/4 dev eth2

That way, I can receive multicast without relying on --net=host.

**Comment by Hugne** [comment]
The lack of IFF_MULTICAST is preventing mDNS from working.
I have a small app that tries to resolve a service (mDNS-SD), but this fails early
during interface enumeration because it can't find any capable netdevs.
It may be that the veth devices do in fact support multicasting, even if the IFF_MULTICAST is not set (as it seems after reading through the comments here). But any application that tries to behave nicely will not work (avahi for example).
Creating a veth device using 'ip link' does give it IFF_MULTICAST capability by default.

haze ~/dev/iproute2/ip (master)$ sudo ip link add link eth0 type veth 
haze ~/dev/iproute2/ip (master)$ ip addr show veth0
109: veth0@veth1: <BROADCAST,MULTICAST,M-DOWN> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 36:ab:e1:be:c0:94 brd ff:ff:ff:ff:ff:ff

**Comment by cpuguy83** [comment]
ping @mavenugo

**Comment by christianhuening** [comment]
Hi there,

I face the same problem as @Hugne . Have a Mono application running inside docker which iterates all interface and looks for multicast enabled devices (which is a built-in function of Mono / .NET). this doesn't work and therefore breaks my zero-conf discovery mechanism. .

any news on this, would be highty appreciated!

Cheers,
christian

**Comment by aiker** [comment]
I confirm that avahi is not working due to missing IFF_MULTICAST. I have to use pipework.

**Comment by Lawouach** [comment]
@aiker would you mind explaining how you're using it to that effect please?

**Comment by aiker** [comment]
@Lawouach I start docker container with --net=none option and use command:
`pipework docker0 -i eth0 CONTAINER_ID IP_ADDRESS/IP_MASK@DEFAULT_ROUTE_IP` which creates eth0 interface inside container with IFF_MULTICAST flag and defined IP address.

**Comment by Lawouach** [comment]
Thanks. Will try it out then :)

**Comment by Hugne** [comment]
Good that there's a workaround for this, but the fact that MLD does not work with standard Docker is not.

**Comment by christianhuening** [comment]
@Hugne  agreed! Actually I don't want to use pipework (my toolbox and tech stack already are huge enough) to just get an active multicast flag.

**Comment by rcarmo** [comment]
+1 for `IFF_MULTICAST`being the default in... 1.7.1? :)

**Comment by RoryHunter** [comment]
+1, this would make multi-host Elasticsearch clusters easier

**Comment by fernandoneto** [comment]
+1

**Comment by christianhuening** [comment]
@mavenugo cool! So we'll see this in 1.9 ?

**Comment by emsi** [comment]
I'm on 1.9-dev. The veth/eth pair is created as such:
```
40: veth660ec14: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default
(...)
39: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
```

Yet the multicasts do not seem to work with overlay multihost network

**Comment by Lawouach** [comment]
@emsi: have you properly configured your routes?

**Comment by emsi** [comment]
On underlay? Yes, as the unicast on overlay is working. 
On overlay there is no need for routing as it's just one segment.

**Comment by ugurarpaci** [comment]
Just a workaround for multicast enabled hazelcast cluster;

You can use hazelcast with version 1.6 by setting trusted subnet block enabled=true in default-cluster.xml configuration as follows: 

```
<interfaces enabled="true">
  <interface>192.168.1.*</interface>
</interfaces>
```

Then; for sure you need to run your docker by setting the parameters bu --net=host options.
Anyway, still looking forward to see multicast enabling merge from libnetwork library.

**Comment by perrocontodo** [comment]
@icecrime care to comment why this has been removed from 1.9.0?

**Comment by cpuguy83** [comment]
Becaus it's not ready and 1.9 is code freeze as of last week.

**Comment by christianhuening** [comment]
oddly enough since Docker 1.8.1 I seem to have the multicast flag and my app is working just fine. 
![image](https://cloud.githubusercontent.com/assets/738953/10692338/2a3a3d4e-7991-11e5-8ccd-72f3a6e686c4.png)

**Comment by eyalfez** [comment]
Same here. I am running two Elasticsearch official docker containers on different hosts which are on the same sub-net with the same broadcast address. Elasticsearch multicast discovery just do not work between the two containers even though multicast is defined on the NIC. The docker version is: 1.8.2.

**Comment by WooDzu** [comment]
And same here. Internal app using multicast for service discovery. Broadcast/multicast enabled within ubuntu container. Docker 1.8.3

**Comment by alvinr** [comment]
+1 for multicast over the overlay network - I used Aerospike, which will do self discovery over multicast.

**Comment by oobles** [comment]
+1 for multicast over the overlay network.  This should also be listed in documentation as a limitation.

**Comment by thaJeztah** [comment]
There's an open ticket in libnetwork for supporting multicast in overlay, see: https://github.com/docker/libnetwork/issues/552

**Comment by Lawouach** [comment]
As a side note, I've been using weave successfully for multicast. For those who may add it to their toolbox.

**Comment by jumanjiman** [comment]
:+1: for weave

**Comment by mavenugo** [comment]
@Lawouach @jumanjiman i havent looked into weave myself. does it support native multicast using IGMP (snooping) ?

**Comment by bboreham** [comment]
@mavenugo Weave doesn't specifically look at IGMP but it does let containers attached to the Weave network multicast to each other.

**Comment by emsi** [comment]
So you actually mean "braodcast"?

**Comment by bboreham** [comment]
Assuming @emsi meant that question to refer to Weave Net: multicast packets are transported to every host but only delivered to individual containers that are listening for them.  So somewhere inbetween.

**Comment by awh** [comment]
> So you actually mean "braodcast"?

It behaves like a switch hierarchy without IGMP snooping enabled - we effectively compute an unweighted minimum spanning tree and use it to forward broadcast and multicast traffic. IGMP snooping is an optimisation which only has any effect on multicast applications that use IGMP subscriptions...

**Comment by dreamcat4** [comment]
A part of multicast protocol (uPNP / bonjour / mdns) requires the sending
and receiving of broadcast packets to the 239.*** listen address. That is
the SSDP part

https://en.wikipedia.org/wiki/Simple_Service_Discovery_Protocol

On Thu, Dec 10, 2015 at 10:46 AM, Mariusz Woloszyn <notifications@github.com

**Comment by rcarmo** [comment]
Just saw the 1.10 release notes. Are we there yet?

**Comment by dreamcat4** [comment]
@rcarmo until then I have been using pipework. ANd multicast works well enough with that. Just that avahi-daemon needs the DBUS service dependancy to be installed right alongside it (in same container).

But for other reasons it certainly would be nice to reture pipework one day. Pipework sets up host-side L2 macvlan bridges. Its the same functionality as VMWare or VirtualBox 'Bridged mode' networking.

**Comment by mavenugo** [comment]
It seems like this issue is being used to discuss the multicast support for both bridge and overlay driver.
As indicated by this : https://github.com/docker/docker/issues/3043#issuecomment-51825140, multicast works just fine in bridge driver. (I tried 1.9 & 1.10).

Yes, the overlay driver needs multicast support (https://github.com/docker/libnetwork/issues/552). 

Given that, should we close this issue and use the above issue to track the multicast support in overlay driver ?

**Comment by tiborvass** [comment]
Agreed with @mavenugo. This issue was opened specificly for single-host which seems to have been resolved a long ago. I suggest opening a new issue for multicast in overlay drivers. In the meantime there is an issue on libnetwork people can follow.

**Comment by combitel** [comment]
Multicast between containers works, but containers still cannot receive multicast from outside. It doesn't work both in bridge and overlay networks.  I've created separate issue for this use case https://github.com/docker/docker/issues/23659 . Can somebody please provide more information on why it doesn't work natively?

**Comment by dreamcat4** [comment]
Maybe you should switch over to the new macvlan driver

http://stackoverflow.com/questions/35742807/docker-1-10-containers-ip-in-lan/36470828#36470828

**Comment by combitel** [comment]
Thanks @dreamcat4, but I need fully isolated network behind NAT which means that I need to use IPVlan L3 mode and authors of MACVLAN driver explicitly state [here](https://gist.github.com/nerdalert/c0363c15d20986633fda#ipvlan-l3-mode-example) that 
> -Ipvlan L3 mode drops all broadcast and multicast traffic.
