### ISSUE TITLE
changing network services is not supported

### ISSUE THREAD

**Issue by hutchic** [docker/docker#30688]
moving from https://github.com/docker/compose/issues/4417

docker-compose.yml
```
version: '3'
services:
  nginx1:
    image: nginx
    networks:
      - consul
      - frontends

  nginx2:
    image: nginx
    networks:
      - frontends
      - backends

networks:
  consul:
  frontends:
  backends:
```
run it on docker swarm twice in a row
```
 docker stack deploy --compose-file nginx
Creating network mashape_consul
Creating network mashape_backends
Creating network mashape_frontends
Creating service mashape_nginx1
Creating service mashape_nginx2
```

```
docker stack deploy --compose-file docker-compose.yml nginx
Updating service mashape_nginx1 (id: no2qi4r84aufbh6m1hzgwb3ge)
Error response from daemon: rpc error: code = 2 desc = changing network in service is not supported
```

It only seems to happen when two services have two networks and one of those networks is shared between them

The docker swarm was setup using docker for aws

docker info
```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 22
Server Version: 1.13.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: awslogs
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: qo6z5tlg5h00u839gj1cpsdpt
 Is Manager: true
 ClusterID: mmngj1f0qiwkjdfqfclq7f2tn
 Managers: 3
 Nodes: 8
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.31.17.99
 Manager Addresses:
  172.31.10.251:2377
  172.31.17.99:2377
  172.31.44.228:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.4-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.38 GiB
Name: ip-172-31-17-99.ec2.internal
ID: ZKRK:6FCI:DFG2:5AVP:DRD6:FHGY:NXQN:OPXC:RUGV:HPWY:5FAP:RTUL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 193
 Goroutines: 343
 System Time: 2017-02-02T17:52:03.524284036Z
 EventsListeners: 0
Username: hutchic
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
Thanks for reporting! This is a known issue in docker 1.13.0, and has been fixed by https://github.com/docker/docker/pull/29732, which will be in the upcoming 1.13.1 release.

The problem is caused by the "Go" runtime shuffling the order of the networks, see https://github.com/docker/docker/issues/29676#issuecomment-269100301 for some explanation (that issue is about environment variables, but the root cause is the same)

I'll close this issue, because this has been fixed, but feel free to continue the conversation

**Comment by deschaefer** [comment]
I am using 

Version 1.13.1-rc1-beta40 (15241)
Channel: beta
0d026e19d7

On my mac and am still seeing this issue.

**Comment by thaJeztah** [comment]
@deschaefer the error itself is correct (i.e., you cannot currently update change networks for services), but should not be shown when doing repeated `docker stack deploy --compose-file....` calls. It's possible existing stacks still show the issue though; see https://github.com/docker/docker/pull/29732#issuecomment-276924232, can you try if you're able to reproduce with a _new_ stack?
