### ISSUE TITLE
[Flaky Test] DockerSwarmSuite.TearDown

### ISSUE THREAD

**Issue by vdemeester** [docker/docker#32173]
This is failing pretty consistently on arm. /cc @aaronlehmann @aboch 

```
23:43:51 ----------------------------------------------------------------------
23:43:51 FAIL: check_test.go:353: DockerSwarmSuite.TearDownTest
23:43:51 
23:43:51 unmount of /tmp/docker-execroot/d84fa846414ee/netns failed: invalid argument
23:43:51 unmount of /tmp/docker-execroot/d84fa846414ee/netns failed: no such file or directory
23:43:51 check_test.go:358:
23:43:51     d.Stop(c)
23:43:51 daemon/daemon.go:392:
23:43:51     t.Fatalf("Error while stopping the daemon %s : %v", d.id, err)
23:43:51 ... Error: Error while stopping the daemon d4f89393cf6cd : exit status 130
23:43:51 
23:43:51 
23:43:51 ----------------------------------------------------------------------
23:43:51 PANIC: docker_api_swarm_test.go:316: DockerSwarmSuite.TestAPISwarmRaftQuorum
23:43:51 
23:43:51 [d84fa846414ee] waiting for daemon to start
23:43:51 [d84fa846414ee] daemon started
23:43:51 
23:43:51 [d4f89393cf6cd] waiting for daemon to start
23:43:51 [d4f89393cf6cd] daemon started
23:43:51 
23:43:51 [d491a1864e62c] waiting for daemon to start
23:43:51 [d491a1864e62c] daemon started
23:43:51 
23:43:51 [d4f89393cf6cd] exiting daemon
23:43:51 [d491a1864e62c] exiting daemon
23:43:51 [d4f89393cf6cd] waiting for daemon to start
23:43:51 [d4f89393cf6cd] daemon started
23:43:51 
23:43:51 [d84fa846414ee] exiting daemon
23:43:51 [d4f89393cf6cd] daemon started
23:43:51 Attempt #2: daemon is still running with pid 387
23:43:51 Attempt #3: daemon is still running with pid 387
23:43:51 Attempt #4: daemon is still running with pid 387
23:43:51 [d4f89393cf6cd] exiting daemon
23:43:51 ... Panic: Fixture has panicked (see related PANIC)
23:43:51 
23:43:51 ----------------------------------------------------------------------
```

**Comment by aaronlehmann** [comment]
Is this a recent regression, or has it been failing for a long time?

**Comment by vdemeester** [comment]
@aaronlehmann I think it has been present, fixed and now it's recently back 😅

**Comment by aboch** [comment]
I might know where the problem is.
Will take a look at his.

**Comment by anusha-ragunathan** [comment]
Seeing this on powerpc CI. https://jenkins.dockerproject.org/job/Docker-PRs-powerpc/1672/console

```
02:02:29 FAIL: check_test.go:353: DockerSwarmSuite.TearDownTest
02:02:29 
02:02:29 unmount of /tmp/docker-execroot/d1cf26ca047e0/netns failed: invalid argument
02:02:29 unmount of /tmp/docker-execroot/d1cf26ca047e0/netns failed: no such file or directory
02:02:29 check_test.go:358:
02:02:29     d.Stop(c)
02:02:29 daemon/daemon.go:392:
02:02:29     t.Fatalf("Error while stopping the daemon %s : %v", d.id, err)
02:02:29 ... Error: Error while stopping the daemon d20c51ae39680 : exit status 130
```

**Comment by anusha-ragunathan** [comment]
PR seeing this CI failure: https://github.com/docker/docker/pull/32525

**Comment by vdemeester** [comment]
😭

**Comment by tophj-ibm** [comment]
couple of errors from the logs, any ideas?
```sh
time="2017-04-12T02:02:01.842300000Z" level=error msg="failed to remove node" error="rpc error: code = 10 desc = dispatcher is stopped" method="(*Dispatcher).Session" node.id=plshsqztl3cj9e6bwifv9xd3k node.session=6nl0grn5dy3pbmw6ezdsb9lq1 
time="2017-04-12T02:02:01.843665000Z" level=error msg="LogBroker exited with an error" error="context canceled" module=node node.id=b5elynswmbdl7emu2fisqapt7 
time="2017-04-12T02:02:01.852132000Z" level=debug msg="stop transport" 
time="2017-04-12T02:02:01.852470000Z" level=info msg="Manager shut down" module=node node.id=b5elynswmbdl7emu2fisqapt7 
time="2017-04-12T02:02:01.852611000Z" level=error msg="cluster exited with error: manager stopped: context canceled" 
time="2017-04-12T02:02:01.852680000Z" level=debug msg="start clean shutdown of all containers with a 15 seconds timeout..." 
time="2017-04-12T02:02:01.852746000Z" level=debug msg="start clean shutdown of cluster resources..." 
time="2017-04-12T02:02:06.853234000Z" level=error msg="failed to send node leave: timed out broadcasting node event" 
```

**Comment by aboch** [comment]
Looking at daemon `d20c51ae39680` logs:
```
time="2017-04-12T02:02:10.510836000Z" level=warning msg="libcontainerd: unknown container bd765fff972c7719b69faa2fd5c78e5703853489d93f861083596d81254c6141" 
time="2017-04-12T02:02:25.230994000Z" level=error msg="agent failed to clean up assignments" error="context deadline exceeded" 
time="2017-04-12T02:02:25.231115000Z" level=error msg="failed to shut down cluster node: context deadline exceeded" 
goroutine 1 [running]:
github.com/docker/docker/pkg/signal.DumpStacks(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/pkg/signal/trap.go:82 +0xbc
github.com/docker/docker/daemon/cluster.(*Cluster).Cleanup(0xc4200701a0)
        /go/src/github.com/docker/docker/daemon/cluster/cluster.go:350 +0x4a8
main.(*DaemonCli).start(0xc4201416e0, 0xc420141600, 0x116bb13e, 0x17, 0xc42002fc00, 0xc420145040, 0xc420226a20, 0x0, 0x0)
        /go/src/github.com/docker/docker/cmd/dockerd/daemon.go:335 +0x1f7c
main.runDaemon(0x1144b200, 0x116bb13e, 0x17, 0xc42002fc00, 0xc420145040, 0xc420226a20, 0x0, 0x0)
        /go/src/github.com/docker/docker/cmd/dockerd/docker.go:91 +0x1c0
main.newDaemonCommand.func1(0xc4200a7680, 0xc42035f100, 0x0, 0x10, 0x0, 0x0)
        /go/src/github.com/docker/docker/cmd/dockerd/docker.go:42 +0x98
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0xc4200a7680, 0xc42000c370, 0x10, 0x11, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:646 +0x558
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4200a7680, 0xc4200a7680, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:742 +0x40c
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4200a7680, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:695 +0x34
main.main()
        /go/src/github.com/docker/docker/cmd/dockerd/docker.go:118 +0x170
```

in this case I think the issue is the one being fixed by #32449

**Comment by tophj-ibm** [comment]
I'm still seeing this on #32571. Which was started after #32449 was merged
```sh
FAIL: check_test.go:355: DockerSwarmSuite.TearDownTest
09:30:47 
09:30:47 unmount of /tmp/docker-execroot/d356464a78ade/netns failed: invalid argument
09:30:47 unmount of /tmp/docker-execroot/d356464a78ade/netns failed: no such file or directory
09:30:47 unmount of /tmp/docker-execroot/dee4084aad09b/netns failed: no such file or directory
09:30:47 check_test.go:360:
09:30:47     d.Stop(c)
09:30:47 daemon/daemon.go:392:
09:30:47     t.Fatalf("Error while stopping the daemon %s : %v", d.id, err)
09:30:47 ... Error: Error while stopping the daemon d55cb5523a94d : exit status 2
09:30:47 
09:30:47 
09:30:47 ----------------------------------------------------------------------
```
from https://jenkins.dockerproject.org/job/Docker-PRs-powerpc/1784/console

**Comment by aboch** [comment]
@tophj-ibm 

Looking at the test daemon logs it is a different issue.
Although I think the locks change might have changed some timing and now this issue is exposed in the ci.

```
time="2017-04-14T14:30:47.905942000Z" level=info msg="Processing signal 'interrupt'" 
time="2017-04-14T14:30:47.908059000Z" level=error msg="Leaving cluster with 0 managers left out of 3. Raft quorum will be lost." 
time="2017-04-14T14:30:47.908232000Z" level=debug msg="(*worker).Assign" len(assignments)=0 module="node/agent" node.id=ain5ls68njkuuecp4brbkydcg 
time="2017-04-14T14:30:47.908266000Z" level=debug msg="(*worker).reconcileSecrets" len(removedSecrets)=0 len(updatedSecrets)=0 module="node/agent" node.id=ain5ls68njkuuecp4brbkydcg 
time="2017-04-14T14:30:47.908297000Z" level=debug msg="(*worker).reconcileTaskState" len(removedTasks)=0 len(updatedTasks)=0 module="node/agent" node.id=ain5ls68njkuuecp4brbkydcg 
time="2017-04-14T14:30:47.909654000Z" level=info msg="Stopping manager" module=node node.id=ain5ls68njkuuecp4brbkydcg 
time="2017-04-14T14:30:47.909726000Z" level=info msg="shutting down certificate renewal routine" module="node/tls" node.id=ain5ls68njkuuecp4brbkydcg node.role=swarm-manager 
time="2017-04-14T14:30:47.909773000Z" level=debug msg="(*Agent).run exited" module="node/agent" node.id=ain5ls68njkuuecp4brbkydcg 
time="2017-04-14T14:30:47.910372000Z" level=error msg="failed to remove node" error="rpc error: code = 10 desc = dispatcher is stopped" method="(*Dispatcher).Session" node.id=ain5ls68njkuuecp
4brbkydcg node.session=t3wxcjat2ukvycrctudewu4f2 
time="2017-04-14T14:30:47.910535000Z" level=error msg="LogBroker exited with an error" error="context canceled" module=node node.id=ain5ls68njkuuecp4brbkydcg 
time="2017-04-14T14:30:47.911378000Z" level=debug msg="stop transport" 
time="2017-04-14T14:30:47.911504000Z" level=info msg="Manager shut down" module=node node.id=ain5ls68njkuuecp4brbkydcg 
time="2017-04-14T14:30:47.911679000Z" level=info msg="Initializing Libnetwork Agent Listen-Addr=0.0.0.0 Local-addr=127.0.0.1 Adv-addr=127.0.0.1 Remote-addr =127.0.0.1" 
time="2017-04-14T14:30:47.911705000Z" level=error msg="cluster exited with error: manager stopped: context canceled" 
time="2017-04-14T14:30:47.911797000Z" level=info msg="Gossip cluster hostname b522b86f50c0-e8054d52beaf" 
time="2017-04-14T14:30:47.911847000Z" level=debug msg="Encryption key 1: 96939" 
time="2017-04-14T14:30:47.911816000Z" level=debug msg="start clean shutdown of all containers with a 15 seconds timeout..." 
time="2017-04-14T14:30:47.911868000Z" level=debug msg="Encryption key 2: fd09f" 
time="2017-04-14T14:30:47.911887000Z" level=debug msg="Encryption key 3: 5630c" 
time="2017-04-14T14:30:47.911908000Z" level=debug msg="start clean shutdown of cluster resources..." 
panic: runtime error: index out of range

goroutine 203 [running]:
panic(0x11461900, 0xc420016090)
        /usr/local/go/src/runtime/panic.go:500 +0x3a8
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).getKeys(0xc42000ae00, 0x116adf01, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/agent.go:245 +0x3b4
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).agentInit(0xc42000ae00, 0xc4208e8300, 0x7, 0xc4209a8530, 0x9, 0xc4209a8530, 0x9, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/agent.go:308 +0x684
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).agentSetup(0xc42000ae00, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/agent.go:199 +0x368
github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).clusterAgentInit(0xc42000ae00)
        /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:326 +0x184
created by github.com/docker/docker/vendor/github.com/docker/libnetwork.(*controller).SetClusterProvider
        /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/controller.go:252 +0xd4
```
