### ISSUE TITLE
docker pull without crazytown control code central

### ISSUE THREAD

**Issue by SamSaffron** [docker/docker#3694]
Take:

```
docker pull mattdm/fedora > test_it
```

then 

```
sam@ubuntu:~$ ls -al test_it 
-rw-rw-r-- 1 sam sam 32969 Jan 20 20:26 test_it
```

![image](https://f.cloud.github.com/assets/5213/1960623/3edab214-8254-11e3-81cd-3fc03f4050b6.png)

This format though wonderful from the console, is very hostile to scripting, it makes it completely impossible to track progress from a log file. 

Instead, offer a flag (which is also applicable to docker run since it does a pull) which allows for the following format:

```
Pulling repository mattdm/fedora
7c8cf65e1efa: Pulling image (f19) from mattdm/fedora
373dc830edcd:: Pulling image (f19) from mattdm/fedora
#######################################################
7c8cf65e1efa: Image downloaded (f19) from mattdm/fedora
#############################################################
373dc830edcd: Image downloaded (f19) from mattdm/fedora
```

One # for every say 256 kb downloaded

**Comment by thedug** [comment]
I'm running a docker pull in a cloud-init script and the cloud init output log is filled with blank lines and no output.

**Comment by clkao** [comment]
@thedug you probably want `> /dev/null` when using docker pull in cloud-init scripts.

**Comment by thedug** [comment]
Good point. I was hoping there was a mode that would at least print some output upon competition.

**Comment by adambiggs** [comment]
+1

On CircleCI the output of `$ docker pull` shows up as a bunch of blank lines.

**Comment by thedug** [comment]
@adambiggs as @clkao mentioned use add > /dev/null to your docker pull command and it will be quiet. Lame that output is lost, but the alternative is worse.

**Comment by halfvector** [comment]
+1 less noise in deployment scripts without losing errors in /dev/null

**Comment by mcandre** [comment]
+1

**Comment by jfrazelle** [comment]
I believe this was fixed if piped to something, @SamSaffron let me know if we can close

**Comment by SamSaffron** [comment]
Its pretty close to what I originally wanted, still not exactly what curl
offers, curl gives some progress by printing # every n bytes that are
downloaded, new mechanism provides zero progress info.

**Comment by Supermathie** [comment]
The progress update code should check to see if stdout is a full tty and if so, print the full spiffy progress output whereas if it's not, it should print minimal incremental output.

**Comment by powdahound** [comment]
+1 - Getting a bunch of blank lines in tools like @circleci is a bummer. In the meantime I'm running the following in a script as a workaround:

    touch push.out
    tail -f push.out &
    TAIL_PID=$!
    docker push $DOCKER_IMAGE_TAG > push.out
    kill $TAIL_PID
    rm push.out

**Comment by pugnascotia** [comment]
#dibs

**Comment by andrewnguyen** [comment]
#dibs (assuming pugnascotia doesn't mind)

**Comment by pugnascotia** [comment]
Go for it - bit snowed under ATM.

**Comment by andrewnguyen** [comment]
I'm having trouble coming up with a solution I like. I guess I #undibs this.

**Comment by thaJeztah** [comment]
No problem @andrewnguyen, thanks for trying!

**Comment by joshk0** [comment]
The canonical unix way to deal with this is to only send control codes if stdout is a tty (interactive console.)

**Comment by jeffminard-ck** [comment]
For now, this is a nice simple fix:

```
docker pull yourimage | tee
```

The `tee` would split output to a file and stdout, but without a file it's kind of a no-op, but since the pipe is there, docker gets less verbose and more script friendly.

**Comment by ljrittle** [comment]
@jeffminard-ck @adambiggs @powdahound Beware: `docker pull yourimage | tee` will hide docker failures.  We use this command form with @circleci currently:

`set -o pipefail; docker push image | while read i; do echo $SECONDS $i; done | awk '{if(t[$2]==0)t[$2]=$1;$1=$1-t[$2];print}'`

both to avoid the blank line issue that was cited in this Issue and to keep a record of per-layer push timing with a second granularity.

**Comment by pugnascotia** [comment]
What scenarios *definitely* trigger this issue? I'm trying to replicate it (v1.8.3) but without success e.g.

* docker pull debian | less
* docker pull ubunu > foo

**Comment by LK4D4** [comment]
I know that issue is pretty old. But anyone still interested in it? I think about totally disabling progress bars with some flag.

**Comment by mrwacky42** [comment]
@LK4D4  - Yes, I'm still interested!

**Comment by LK4D4** [comment]
@mrwacky42 Do you think only progressbars should be disabled or output overall?

**Comment by mrwacky42** [comment]
@LK4D4  - I think some sort of output that doesn't involve curses or 'crazytown control code central' is desirable. A `--quiet` option that quashes all output is less necessary IMO, since you can just send everything to `/dev/null`.

**Comment by LK4D4** [comment]
@mrwacky42 Okay, it requires minor changes in graph, which conflicts with #17924, will do after merge. It'll be in 1.10 release.

**Comment by LK4D4** [comment]
@mrwacky42 Would you mind to try with master?

**Comment by icecrime** [comment]
This is fixed on master, sorry I don't know through which PR though...

**Comment by davidneudorfer** [comment]
@icecrime I still have this issue on CircleCI.
```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Mar  2 01:11:00 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:57:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

This thread is one of the first results on Google but I'm not sure what I'm missing if it's fixed on master.

**Comment by atombender** [comment]
For those who want this behaviour in a script (e.g. CI server) and want to avoid putting `| tee` or `| cat` or whatever after every `docker` command, you can add this at the top of your script:

```
exec 1> >(cat) 2>&1
```

It causes all of the current process' stdout/stderr to redirected to `cat`, which makes it lose the TTY. It needs to be done within a shell script, however.
