### ISSUE TITLE
no such process error when container state is inconsistent

### ISSUE THREAD

**Issue by crosbymichael** [docker/docker#5938]
Error that @discordianfish received when upgrading.  A container's state file says that the container is running but there is no pid and you cannot make docker kill the container because it is returning an error that is cannot find the process.

**Comment by CBarraford** [comment]
is this a duplicate or maybe relating to https://github.com/docker/docker/issues/5165?

**Comment by sheerun** [comment]
Do docker perform some stress testing in order to discover such bugs?

**Comment by opyate** [comment]
@OAGr :+1: 

> This did happen after I used Docker exec to get into the container.

I was also exec'ed into a container, the stack restarted (fig), and ```stop```'ing that container yields  ```no such process```.

**Comment by LK4D4** [comment]
@opyate yes, your case is fixed there.

**Comment by ccrouch** [comment]
@benjy @cyphar 
I think I can still reproduce @benjy's issue with a recent build, i.e.
"This issue still occurs for me. Easily reproducible by logging into the container with docker exec and stopping the service/process that was started by CMD."

This is with the most recent docker client from master.dockerproject.com:
The client version:
$ ./docker-1.4.1-dev -v
Docker version 1.4.1-dev, build 5a56361

The system installed docker version (i.e. daemon):
$ docker -v
Docker version 1.4.1, build 5bc2ff8

Steps to reproduce
1)  ./docker-1.4.1-dev run -it --name test ubuntu bash
2) root@e95907f6ed90:/# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.4  0.0  18168  1996 ?        Ss   22:37   0:00 bash
root        21  0.0  0.0  15568  1136 ?        R+   22:37   0:00 ps aux
3) ctrl-p-q
[drop back to host]
4)  ./docker-1.4.1-dev exec -it test bash
5) root@e95907f6ed90:/# kill 1
[get dropped back to host]
6)  ./docker-1.4.1-dev stop test
Error response from daemon: Cannot stop container test: no such process
FATA[0000] Error: failed to stop one or more containers
7)  ./docker-1.4.1-dev rm -f  test
Error response from daemon: Could not kill running container, cannot remove - no such process
FATA[0000] Error: failed to remove one or more containers
8) sudo service docker restart
9)  ./docker-1.4.1-dev rm test
test

**Comment by skozin** [comment]
Got this problem just now, using boot2docker and without any `docker exec`.

I started a simple node.js app (`docker run --rm -p 3000:3000 test-app`), then stopped it with `Ctrl+C`, but `docker run` command didn't return and the container didn't disappeared from `docker ps` output. Now I am unable to stop/kill/force remove this container:

```text
$ docker ps -a
CONTAINER ID        IMAGE                   COMMAND                CREATED             STATUS                    PORTS                              NAMES
5ce9dfa67ac8        test-app:latest         "/nodejs/bin/npm sta   5 minutes ago       Up 5 minutes              8080/tcp, 0.0.0.0:3000->3000/tcp   gloomy_albattani

$ docker kill 5ce9dfa67ac8
Error response from daemon: Cannot kill container 5ce9dfa67ac8: no such process

$ docker rm -f 5ce9dfa67ac8
Error response from daemon: Could not kill running container, cannot remove - no such process

$ boot2docker ssh ps -ef
PID   USER     COMMAND
...
  723 root     /usr/local/bin/docker -d -D -g /var/lib/docker -H unix:// -H tcp://0.0.0.0:2376 --tlsverify --tlscacert=/var/lib/boot2docker/tls/ca.pem --tlscert=/var/lib/boot2docker/tls/server.pem --tlskey=/var/lib/boot2docker/tls/serverkey.pem
...
12538 root     docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 3000 -container-ip 172.17.0.108 -container-port 3000
...

$ docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): darwin/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
```

On the host boot2docker machine, there are no `node` processes, but there is a zombie `docker-proxy` process that prevents starting another container built from the same image using the same host-port.

Previously I ran containers built from that same image with that same command multiple times, and killed them using `Ctrl+C` without any problems, so there seems to be some kind of race condition.

**Comment by skozin** [comment]
@crosbymichael, do you have any timing for 1.4.2 release? I really need the `exec` fix from #9795, as I am using `exec` to run periodic health checks.

**Comment by LK4D4** [comment]
@skozin I'm not sure that there will be 1.4.2. There will be 1.5.0 at the beginning of February.

**Comment by skozin** [comment]
@LK4D4, thank you for the quick response! As for 1.4.2, I just saw #9699 (exec issue) assigned to this milestone.

Seems that I'll have to find some workaround to run commands inside my containers without using `exec`, as I need to deploy the whole thing before February :(

**Comment by LK4D4** [comment]
@skozin If you're brave enough you can use binaries https://master.dockerproject.com/ :)

**Comment by skozin** [comment]
@LK4D4, thank you for the tip, I'll definitely try this :)

**Comment by yeasy** [comment]
Meet this frequently with 1.4.1.
Will try the old release.

**Comment by ataraxus** [comment]
have the same issue with: 

```
clumsys-mbp:proark_services atx$ docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS                              NAMES
1ba991a1b734        proark:latest       "/opt/proark_service   43 minutes ago      Up 43 minutes       8888/tcp, 0.0.0.0:8889->8889/tcp   proarkserver 
```
```
clumsys-mbp:proark_services atx$ docker kill 1ba991a1b734
Error response from daemon: Cannot kill container 1ba991a1b734: no such process
FATA[0000] Error: failed to kill one or more containers 
```
```
clumsys-mbp:proark_services atx$ docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): darwin/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
```

I also killed the main application within  an attached bash.

**Comment by yairlev** [comment]
Any estimation to when this fix is going out officially ? Will the next
version also include the option to stop/kill a long running or hanging
process that started with the "exec" command ?

On Sun, Dec 28, 2014 at 8:49 PM, Alexander Morozov <notifications@github.com

**Comment by cpuguy83** [comment]
@yairlev I think this is fixed on master. Feel free to test: https://master.dockerproject.com

```bash
docker run -d -it busybox /bin/sh
1c95f0fc40ed65f958fd327f03462cdb06fa76cfdef47a34b30a1600f9d67ffa
docker exec -it 1c95f0fc40ed65f958fd327f03462cdb06fa76cfdef47a34b30a1600f9d67ffa /bin/sh
/ #

# in separate terminal
docker kill 1c95f0fc40ed65f958fd327f03462cdb06fa76cfdef47a34b30a1600f9d67ffa
```

**Comment by nehemiascr** [comment]
I am having the same problem
```Shell
bash-3.2$ docker ps
CONTAINER ID        IMAGE                      COMMAND                CREATED             STATUS              PORTS                     NAMES
6e9d20dfab3c        training/webapp:latest     "python app.py"        2 hours ago         Up 2 hours          0.0.0.0:49155->5000/tcp   web                 
79d6a02d6e03        training/postgres:latest   "su postgres -c '/us   2 hours ago         Up 2 hours          5432/tcp                  db    
```
```Shell
bash-3.2$ docker stop 6e9d20dfab3c
Error response from daemon: Cannot stop container 6e9d20dfab3c: no such process
FATA[0000] Error: failed to stop one or more containers 
```
```Shell
bash-3.2$ docker rm -f 6e9d20dfab3c
Error response from daemon: Could not kill running container, cannot remove - no such process
FATA[0000] Error: failed to remove one or more containers 
```
It happened after I ran 
```Shell
bash-3.2$ docker exec web ping db
```
now I am getting this
```Shell
bash-3.2$ docker exec web ping db
Cannot run exec command f1b9e2fbd8bab3bbe8c23943772a9ff57c6955c5c6b04d3b68a9fe9f007ca664 in container 6e9d20dfab3c9fc85a504b918437df31c645ce47ce469d39a49a8629c1cfaf56: State unavailable for container with ID 6e9d20dfab3c9fc85a504b918437df31c645ce47ce469d39a49a8629c1cfaf56. The container may have been cleaned up already. Error: open /mnt/sda1/var/lib/docker/execdriver/native/6e9d20dfab3c9fc85a504b918437df31c645ce47ce469d39a49a8629c1cfaf56/state.json: no such file or directory
Error starting exec command in container f1b9e2fbd8bab3bbe8c23943772a9ff57c6955c5c6b04d3b68a9fe9f007ca664: Cannot run exec command f1b9e2fbd8bab3bbe8c23943772a9ff57c6955c5c6b04d3b68a9fe9f007ca664 in container 6e9d20dfab3c9fc85a504b918437df31c645ce47ce469d39a49a8629c1cfaf56: State unavailable for container with ID 6e9d20dfab3c9fc85a504b918437df31c645ce47ce469d39a49a8629c1cfaf56. The container may have been cleaned up already. Error: open /mnt/sda1/var/lib/docker/execdriver/native/6e9d20dfab3c9fc85a504b918437df31c645ce47ce469d39a49a8629c1cfaf56/state.json: no such file or directory
```

**Comment by cpuguy83** [comment]
@nehemiascr this is fixed and will be in the 1.5 release

**Comment by lennartcl** [comment]
Which PR/commit(s) exactly address this issue?

**Comment by skozin** [comment]
@lennartcl, see [docker/#9795](https://github.com/docker/docker/pull/9795) and [libcontainer/#308](https://github.com/docker/libcontainer/pull/308).

**Comment by lennartcl** [comment]
@skozin thanks! Also, another related PR: https://github.com/docker/docker/pull/10183

**Comment by dreamcat4** [comment]
Getting this error message on docker 1.5.0. No idea why... pls read here:

https://github.com/dreamcat4/docker-images/issues/1

**Comment by rkulla** [comment]
I'm also having this issue with client 1.4.1. Can't docker kill, rm, or even rm -f it. It happened after I 'docker attach'd succesfully and tried to 'exit' (which hung). Now I can't even reattach or kill it.

$ docker info
Containers: 13
Images: 198
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 224
Execution Driver: native-0.2
Kernel Version: 3.13.0-44-generic
Operating System: Ubuntu 14.04.1 LTS

**Comment by dreamcat4** [comment]
It happens because the command `docker stop` only sends a `TERM` signal to the launched process e.g. the `entrypoint` command (or whatever replaces it).

For example: If you use `#!/bin/sh` - then that launches the `dash` shell in most distros. Well it turns out that any subshell in `dash` e.g. with back ticks `\`\`` or `$()` or pipe `|` creates a non-child (=orphaned) process.

Other spawned processes don't get killed unless you run a process supervisor inside your containers. Really docker should be fixed to send a `TERM` to every un-killed process that is running inside that container's namespace. Whether it is a child process or not.

It would save us having to complicated run process supervisors inside our containers (even for simple shell scripts!).

**Comment by wyaeld** [comment]
devils advocate viewpoint: why should it be dockers problem that users run
complex multi-process setups inside a container.  There are plenty of
lightweight task supervisors that can handle that, and they all have
different tradeoffs, so any choice on task management design by the core
docker team is likely to frustrate people.

There are plenty of lightweight task managers like runit and s6 that might
fit your purposes.

**Comment by cyphar** [comment]
@dreamcat4 I can't help thinking that trying to kill all processes in a namespace would be racy. If you read the whole task list of the namespace and then kill each one, what happens if a new task starts between reading the task list and killing all the tasks? If you read each entry and then kill it immediately, how do you know that changes would appear after your cursor?

**Comment by dreamcat4** [comment]
@wyaeld Because the example given was not "complex", it was a very simple `#!/bin/sh` shell script. It was not concocted in any way - this is something that has happened to me in real life, while trying to use docker in it's intended fashion.

@cyphar That is a good point. A way to get around such issues would be implement as a `--force` flag.

**Comment by tdterry** [comment]
Just experienced this with a container. I tried to stop the container. The process stopped, but the container still has an "Up" status. Additional calls to docker stop/kill/rm respond with an error:

# docker stop 577a315aa6a7
Error response from daemon: Cannot stop container 577a315aa6a7: no such process
FATA[0000] Error: failed to stop one or more containers

**Comment by dreamcat4** [comment]
@tdterry You can restart the docker daemon to clear that error off. The problem is most likely un-killed orphaned (zombie) processes still running inside the container.

Until docker is eventually improved, you can work around the issue by installing a process sopervisor inside of your container / docker images. *For example, you can install s6-overlay like this:*

https://gist.github.com/dreamcat4/e202bac73aa79bb805cb

**Comment by samos123** [comment]
@dreamcat4 any other workaround other than restarting the docker daemon? It worked for me but it will cause all containers to be restarted on my environment. So preferably would be a workaround that leaves working containers intact..

**Comment by dreamcat4** [comment]
@samos123 Yeah the proper solution is to make the containers exit cleanly in the first place. Either by docker properly fixing it's process cleanup management, or else in the meantime by using s6-overlay or other process supervisor inside your containers.
