### ISSUE TITLE
cap_set_file not permitted on aufs storage driver only

### ISSUE THREAD

**Issue by jakedt** [docker/docker#6980]
When running this minimal Dockerfile:

```
FROM centos
RUN yum install -y httpd mod_ssl
```

The following error occurs only when using the aufs storage driver:
```
Installing : httpd-2.4.6-17.el7.centos.1.x86_64                           8/9
Error unpacking rpm package httpd-2.4.6-17.el7.centos.1.x86_64
 
error: unpacking of archive failed on file /usr/sbin/suexec: cpio: cap_set_file
```

When running with the devicemapper driver the command succeeds successfully. The capabilities listed for the process are identical under both storage drivers and include ```CAP_SETFCAP``` and ```CAP_FOWNER``` which are listed by ```set_cap_file``` as requirements.

Here is the full list of capabilities which both processes have:
```
Capabilities for `11004': =ep cap_chown,cap_dac_override,cap_fowner,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_mknod,cap_setfcap+i cap_dac_read_search,cap_fsetid,cap_linux_immutable,cap_net_broadcast,cap_net_admin,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_lease,cap_audit_write,cap_audit_control,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend-ep
```

**Comment by testn** [comment]
Any updates on this. I tried to switch to use devicemapper which eliminates the problem. However, devicemapper is way slower than aufs. So I would like to see this fixed in aufs eventually.

**Comment by PositiveAlex** [comment]
@metal3d thank you, your solution works on ubuntu

**Comment by Thorndike** [comment]
Problem still existing in the latest docker version:

==== docker version =====
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
===== docker info ====
Containers: 2
Images: 70
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 74
Execution Driver: native-0.2
Kernel Version: 3.13.0-44-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 8
Total Memory: 15.6 GiB
Name: PC10004846
ID: 5A67:DFNS:TJIG:MIY3:KHD4:EERC:Q5HD:T4FF:LTHU:LYUY:O4Z4:XYTN
WARNING: No swap limit support
==== failed ====
Running transaction
  Installing : apr-1.4.8-3.el7.x86_64                                       1/5 
  Installing : apr-util-1.5.2-6.el7.x86_64                                  2/5 
  Installing : httpd-tools-2.4.6-19.el7.centos.x86_64                       3/5 
  Installing : mailcap-2.1.41-2.el7.noarch                                  4/5 
Error unpacking rpm package httpd-2.4.6-19.el7.centos.x86_64
  Installing : httpd-2.4.6-19.el7.centos.x86_64                             5/5 
error: unpacking of archive failed on file /usr/sbin/suexec: cpio: cap_set_file
  Verifying  : mailcap-2.1.41-2.el7.noarch                                  1/5 
  Verifying  : httpd-tools-2.4.6-19.el7.centos.x86_64                       2/5 
  Verifying  : apr-util-1.5.2-6.el7.x86_64                                  3/5 
  Verifying  : apr-1.4.8-3.el7.x86_64                                       4/5 
  Verifying  : httpd-2.4.6-19.el7.centos.x86_64                             5/5 

Dependency Installed:
  apr.x86_64 0:1.4.8-3.el7                     apr-util.x86_64 0:1.5.2-6.el7    
  httpd-tools.x86_64 0:2.4.6-19.el7.centos     mailcap.noarch 0:2.1.41-2.el7    

Failed:
  httpd.x86_64 0:2.4.6-19.el7.centos

**Comment by testn** [comment]
The problem still happens in Docker 1.5

**Comment by shibuya-jk** [comment]
That happens to me too the same as @testn in Docker 1.5
I hope this issue fix soon~

**Comment by PositiveAlex** [comment]
I solved this problem deciding not to use `update` for all packages in the system. But if a package you definitely want to install is failing with aufs, ya, that's trouble. But in most cases, one docker is for one app, so you shouldn't update all system.

**Comment by mffrench** [comment]
I'm interested to know when this issue will be fixed but is there any ticket raised on AUFS regarding that problem ?

**Comment by robbyt** [comment]
For boot2docker users, here's how to change your storage driver:
http://pkgfarm.tumblr.com/post/114104687791/fixing-yum-install-on-boot2docker

**Comment by joncon** [comment]
@robbyt link fixed it for me.

**Comment by tiborvass** [comment]
Anybody can provide a VM to test in?

**Comment by pstengel** [comment]
You need a newer version of AUFS with support for `CONFIG_AUFS_XATTR`, and that kernel config option must be enabled. That fixes the `cpio: cap_set_file` on boot2docker (boot2docker/boot2docker#818), and should fix it on any Linux using AUFS.

**Comment by jefferai** [comment]
This does not only affect boot2docker. Can you please re-open this?

**Comment by pstengel** [comment]
The fix is the same outside of boot2docker. This isn't a bug with Docker itself, it was a missing feature in AUFS. You'll need to update to a newer version of AUFS in your kernel and enable `CONFIG_AUFS_XATTR` to fix it.

**Comment by Thorndike** [comment]
That basically means I am out of docker business with Ubuntu 14.04 LTS in a corporate environment where I can only use ubuntu packages.

**Comment by pstengel** [comment]
@Thorndike Could you switch to a different storage driver? `overlay` and `devicemapper` both look to be supported by 14.04 LTS.

**Comment by Thorndike** [comment]
Thanks for that hint! Missed it in all those configs. Added in my /etc/default/docker "-s devicemapper" to the DOCKER_OPTS and now I can build an image with httpd installed.

**Comment by cpuguy83** [comment]
You just have to make sure you aren't using the statically compiled docker if you are using devicemapper

**Comment by perj** [comment]
Does anyone know if there's some workaround for this when using `docker-machine` ? Specifically `docker-machine create --driver amazonec2 mymachine` is affected by default.

**Comment by joshuacox** [comment]
I'm running into this same issue with both Debian Jessie and Ubuntu Trusty here https://github.com/adelton/docker-freeipa/issues/22 my workaround is to build externally and pull the image in, seems to work fine that way.  But I'm tempted to fool around with AUFS or try out BTRFS

**Comment by AlienOnEarth** [comment]
I am also facing similar problem with Ubuntu host and centos container. Error:

Installed:
  systemd-libs.x86_64 0:208-20.el7_1.5                                          

Dependency Installed:
  acl.x86_64 0:2.2.51-12.el7                                                    
  cryptsetup-libs.x86_64 0:1.6.6-3.el7                                          
  dbus.x86_64 1:1.6.12-11.el7                                                   
  device-mapper.x86_64 7:1.02.93-3.el7_1.1                                      
  device-mapper-libs.x86_64 7:1.02.93-3.el7_1.1                                 
  fipscheck.x86_64 0:1.4.1-5.el7                                                
  fipscheck-lib.x86_64 0:1.4.1-5.el7                                            
  kmod.x86_64 0:14-10.el7                                                       
  kmod-libs.x86_64 0:14-10.el7                                                  
  qrencode-libs.x86_64 0:3.4.1-3.el7                                            
  tcp_wrappers-libs.x86_64 0:7.6-77.el7                                         

Failed:
  systemd.x86_64 0:208-20.el7_1.5                                               

Complete!

**Comment by AlienOnEarth** [comment]
I am building centos docker container on ubuntu host. But I am also facing similar issues: Failed:
  systemd.x86_64 0:208-20.el7_1.5.

**Comment by sjoeboo** [comment]
+1 , centos:7 container on a ubuntu 14.04 host

**Comment by WanliTian** [comment]
+1 centos:centos7 on ubuntu 14.04 host

**Comment by SchwarzM** [comment]
+1 centos container on ubuntu 14.04 host

**Comment by Rudolph-Miller** [comment]
+1

**Comment by patrickallaert** [comment]
Just for the record, I had the same issue (/cc @asinus666 on Gentoo as well). In my case, the culprit was a kernel compiled without:

    CONFIG_EXT4_FS_SECURITY=y

**Comment by deferraz** [comment]
@patrickallaert I`m using a Debian Jessie box with CONFIG_EXT4_FS_SECURITY enabled and the problem still persists , looks like it is another issue

**Comment by buley** [comment]
Happens with `centos7` boxen building on continuous integration platforms circleci and shippable. They are Ubuntu. For me the freshest working build is `centos6.6`.

**Comment by smiller171** [comment]
[+1]

**Comment by MBoretto** [comment]
I got this issue when try to install wireshark on a fedora 22 container.
What can I do?

Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
warning: Unable to get systemd shutdown inhibition lock
  Installing  : wireshark-1.12.7-2.fc22.x86_64                                                                                                                                                                   
Error unpacking rpm package wireshark-1.12.7-2.fc22.x86_64
error: unpacking of archive failed on file /usr/sbin/dumpcap;56269be8: cpio: cap_set_file



**Docker version**
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64


**docker info**
Containers: 48
Images: 15
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 111
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-37-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 4
Total Memory: 7.705 GiB
Name: feinfren
ID: QXUH:OMU2:QZM3:62T2:CGTG:2RXE:QT7V:FXDQ:2IDW:Q4IH:JSAD:UR4W
WARNING: No swap limit support

**Comment by Thorndike** [comment]
@MBoretto: What I have done is to use a computer with CentOS to build those images. Once build they are running on Ubuntu just fine.

**Comment by fedya** [comment]
still valid for centos7 
Containers: 2
Images: 22
Storage Driver: aufs
 Root Dir: /var/cache/docker/aufs
 Backing Filesystem: extfs
 Dirs: 26
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.3-nrjQL-desktop-3omv
Operating System: OpenMandriva Lx 2014.0 (Phosphorus)
CPUs: 8
Total Memory: 15.58 GiB
Name: localhost.localdomain
ID: COKL:J2ED:CDNE:NYZM:5ZR2:JMEW:73RD:MKKB:K7BD:I53Q:253G:3KB7
Username: fedya
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support

**Comment by The-Judge** [comment]
This happens on Docker's own infrastructure, when using Automated Builds; see [here for example](https://hub.docker.com/r/derjudge/piwik/builds/bxuek8hyve8vgojulejtzq5/). Changing the local Build Host or storage driver seems like a poor workaround, since it only enables one to build the image locally.

**Comment by thaJeztah** [comment]
@The-Judge have you contacted support@docker.com for that? Perhaps the support team for docker hub can look into that

**Comment by matanster** [comment]
Same problem here so it seems (client version 1.10.1).

What does it mean:
> The following error occurs only when using the aufs storage driver
Doesn't docker always use aufs?

In the same vein:

> Now, Docker is using devicemapper and not AUFS
As per the workaround suggestion above, what are the overall ramifications of switching docker to devicemapper?

**Comment by thaJeztah** [comment]
@matanster see the storage driver section of the docs for more in-depth information on the differences between drivers https://docs.docker.com/engine/userguide/storagedriver/imagesandcontainers/

**Comment by Nagoo** [comment]
+1 , centos:7 container on a ubuntu 15.10 host

**Comment by martinsbalodis** [comment]
This problem isn't fixed in ubuntu 16.04.

**Comment by ttroy50** [comment]
I've also seen the problem building a centos:7 image on an ubuntu 16.04 host.

To use the devicemapper workaround on 16.04 you can do the following

`systemctl stop docker`

Edit /lib/systemd/system/docker.service to add `-s devicemapper` to the ExecStart command. See https://docs.docker.com/engine/admin/systemd/

reload the service file

`systemctl daemon-reload`

start docker 

`systemctl start docker`

**Comment by crashbit666** [comment]
https://github.com/docker/hub-feedback/issues/461

**Comment by josdotso** [comment]
This issue went away for me when I upgraded to Ubuntu 16.04.1 and rebooted.

**Comment by espoelstra** [comment]
Has anybody here tested the workaround from https://github.com/docker/hub-feedback/issues/461#issuecomment-318786850 ?

> Experienced same issue, cannot install httpd in a centos container
> 
> error unpacking rpm package httpd-2.4.6-45.el7.centos.4.x86_64
> error: unpacking of archive failed on file /usr/sbin/suexec;597bcbad: cpio: cap_set_file
> error: httpd-2.4.6-45.el7.centos.4.x86_64: install failed
> 
> With the image centos/https, they set **--setopt** when installing the package:
> 
> RUN yum -y --setopt=tsflags=nodocs update && 
> yum -y --setopt=tsflags=nodocs install httpd && 
> yum clean all
> 
> Done so in my Dockerfile, now it works fine.
