### ISSUE TITLE
Docker bails on systems with btrfs + SELinux w/o regard for SELinux status

### ISSUE THREAD

**Issue by dfarrell07** [docker/docker#7952]
I'm seeing "Permission denied" errors from shared library code on a Fedora 20 systems using btrfs.

I've replicated this on two bare metal up-to-date Fedora 20 systems running btrfs, including one that was totally fresh. As a control, everything works fine on an up-to-date Fedora 20 system where Docker uses the devicemapper storage driver (running on an OpenStack deployment, also a very fresh install).

Steps to reproduce:

```
sudo yum update -y
sudo yum install docker-io -y
sudo systemctl start docker
sudo docker pull fedora
sudo docker run fedora <some command>
```

The exact result on btrfs storage driver systems varies with the command I attempt to run, but generally some shared lib fails to load with a permission denied error.

Echo (`sudo docker run fedora echo "hello world"`) causes:

```
echo: error while loading shared libraries: libc.so.6: cannot open shared object file: Permission denied
```

A Bash shell (`sudo docker run fedora /bin/bash`) causes:

```
/bin/bash: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: Permission denied
```

Results on devicemapper storage driver system are as expected.

The output of the three systems is identical for `docker version`:

```
[~]$ sudo docker version
Client version: 1.1.2
Client API version: 1.13
Go version (client): go1.2.2
Git commit (client): d84a070/1.1.2
Server version: 1.1.2
Server API version: 1.13
Go version (server): go1.2.2
Git commit (server): d84a070/1.1.2
```

Output of `docker info` for the (failing) fresh btrfs system:

```
[~]$ sudo docker info
Containers: 4
Images: 3
Storage Driver: btrfs
Execution Driver: native-0.2
Kernel Version: 3.11.10-301.fc20.x86_64
```

Output of `docker info` for the (working) nearly-fresh devicemapper system:

```
[~]$ sudo docker info
Containers: 3
Images: 5
Storage Driver: devicemapper
 Pool Name: docker-252:1-131261-pool
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 975.2 Mb
 Data Space Total: 102400.0 Mb
 Metadata Space Used: 1.3 Mb
 Metadata Space Total: 2048.0 Mb
Execution Driver: native-0.2
Kernel Version: 3.11.10-301.fc20.x86_64
```

The (working) devicemapper install and the (failing) totally fresh btrfs install have the same kernel:

```
# Fresh (failing) btrfs F20 install
[~]$ uname -a
Linux localhost.localdomain 3.11.10-301.fc20.x86_64 #1 SMP Thu Dec 5 14:01:17 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
# Nearly-fresh (working) devicemapper F20 install
[~]$ uname -a
Linux dfarrell-odl-docker 3.11.10-301.fc20.x86_64 #1 SMP Thu Dec 5 14:01:17 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
```

The (failing) not-fresh btrfs install has a newer kernel:

```
# Not-fresh (failing) btrfs F20 install
[~]$ uname -a
Linux localhost.localdomain 3.15.10-201.fc20.x86_64 #1 SMP Wed Aug 27 21:10:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Note that I can prevent this error, even on the btrfs systems, by either putting SELinux in Permissive mode (`sudo setenforce 0`, as described by the OP [here][3]) or passing the `--privileged` flag (`sudo docker run --privileged fedora echo "hello world"`, as described [here][1]).

```
# Example of proper behavior on fresh btrfs system when SELinux is in Permissive mode
[~]$ getenforce
Enforcing
[~]$ sudo setenforce 0
[~]$ getenforce
Permissive
[~]$ sudo docker run fedora echo "hello world"
hello world
[~]$ sudo setenforce 1
[~]$ sudo docker run fedora echo "hello world"
echo: error while loading shared libraries: libc.so.6: cannot open shared object file: Permission denied
```

```
# Example of proper behavior on not-fresh btrfs system when --privileged flag passed
[~]$ sudo getenforce
Enforcing
[~]$ sudo docker run --privileged fedora echo "hello world"
hello world
```

My libselinux version is the same on all three systems:

```
[~]$ sudo yum info libselinux
Installed Packages
Name        : libselinux
Arch        : x86_64
Version     : 2.2.1
Release     : 6.fc20
<snip>
```

[This Docker GitHub Issue comment][2] mentioned switching from aufs to devicemapper as a fix for a seemingly similar issue. That may support the theory that this is a btrfs-related issue.

[1]: https://ask.fedoraproject.org/en/question/50871/cant-run-docker-without-privileged-on-fedora-20/
[2]: https://github.com/docker/docker/issues/5430#issuecomment-50089471
[3]: https://bugzilla.redhat.com/show_bug.cgi?id=1112748#c0

**Comment by ross-w** [comment]
Forgive me if I'm just bad at searching, but I've tried to find the status of context mount labelling on btrfs and I'm still unable to find any detail on it.
The closest I can find is here: https://github.com/SELinuxProject/selinux/wiki/Kernel-Todo where it's on the "todo" list. Should I be looking somewhere in particular?

**Comment by rhatdan** [comment]
A lot of the discussions on this have taken place on private lists or kernel lists.  Most of the concentration now is on getting this support into Overlayfs now I am afraid.

**Comment by jfrazelle** [comment]
is this still an issue with the latest version of docker

**Comment by sammcj** [comment]
Yes, we still have to manually patch and rebuild Docker to use it with SELinux

**Comment by jfrazelle** [comment]
ah ok cool good to know thanks

**Comment by rhatdan** [comment]
BTRFS still does not support use with SELinux labels.  Most of the effort now is on OverlayFS.  people seem to be straying away from BTRFS.

**Comment by jfrazelle** [comment]
thanks @rhatdan

**Comment by ross-w** [comment]
Is there a separate ticket we can follow for OverlayFS progress?


Ross

**Comment by jfrazelle** [comment]
@ross-w its experimental in Docker right now but lots of people use it and love it!

**Comment by sammcj** [comment]
That's not very reassuring

**Comment by jfrazelle** [comment]
@sammcj It is in experimental so we can make sure it is perfect before fully supporting it & because it requires at least a 3.18 kernel which not many people have

**Comment by jfrazelle** [comment]
@sammcj I don't understand what is not reassuring about adding new features and making sure they are perfect before fully supporting it.

**Comment by sammcj** [comment]
Sorry if my comment seemed short but i thought you were saying that a new feature is being developed and is not being tracked.

Do you have the ticket number for overlayFS w/ SELinux so we can monitor its progress?

**Comment by ross-w** [comment]
Thank Jessie I was meaning SELinux progress wrt OverlayFS. 


Ross

**Comment by jfrazelle** [comment]
Oh so sorry I do not know about that, maybe @rhatdan does

**Comment by rhatdan** [comment]
Right now David Howells is in charge of this and working with the kernel teams at Red Hat and Upstream to get it integrated.  OverLayfs from Red Hat's perspective has two big problems.  

1. Can not currently use xfs on top of it.  We are close to getting this merged and working.
2. Getting SELinux support.   I am told that some patches have recently been merged upstream.

My goal is that we get this by RHEL7.2 time frame.  Which should be in the 6-9 Month time frame.  Of course if the code gets merged sooner, it would show up in Fedora Sooner

I just opened a bugzilla's tracking this https://bugzilla.redhat.com/show_bug.cgi?id=1197177

**Comment by dperson** [comment]
@rhatdan if it's being tracked on a RedHat bugzilla, can you open this bug so that we can see the status? Thanks in advance.

**Comment by dfarrell07** [comment]
> @rhatdan if it's being tracked on a RedHat bugzilla, can you open this bug so that we can see the status? Thanks in advance.

+1

**Comment by rhatdan** [comment]
I have asked to open up https://bugzilla.redhat.com/show_bug.cgi?id=1178944 but I have no control.

There is not much info there anyways.

But it is a top priority for us.

**Comment by artpol84** [comment]
Sorry if this is wrong place to post (pls forward me to the proper location if that's the case).
I'm getting the following on RHEL 6.5:
```
# /usr/bin/docker -d -s btrfs
INFO[0000] +job serveapi(unix:///var/run/docker.sock)   
INFO[0000] WARNING: You are running linux kernel version 2.6.32-431.el6.x86_64, which might be unstable running docker. Please upgrade your kernel to 3.8.0. 
FATA[0000] driver not supported
```
SELinux is disabled:
```
# getenforce
Disabled
```
The btrfs is created on the loop device by now since I don't have physical volume yet:
```
# mount
...
/dev/loop0 on /var/lib/docker type btrfs (rw)
```
I will be able to try on RHEL 6.6 as well today or tomorrow. 
The reason I want to try btrfs is that devicemapper is buggy IMHO:
1. On RHEL 6.5 it crashes the system when I build images. OS reboots and I'm seing hundreds of mount commands in `/var/log/messages`.
2. On RHEL 6.6 I can build and run my images but I can't export it getting error from device mapper. It looks related to #4036 and #4096.

Given that I can't change my distribution (wired to RHEL 6.5/6.6) what is the best way for me to go?

**Comment by rhatdan** [comment]
@artpol84 This is the wrong place.  I have no idea what your problem is.  And from a RHEL perspective docker on rhel6 is not supported.  I guess you could open a bug on EPEL, or try the upstream docker and build it yourself, and see if it works.

**Comment by matachi** [comment]
Ran `sudo dnf install docker`, which installed `docker-1.7.1-1.gitb6416b7.fc22.x86_64` and `docker-selinux-1.7.1-1.gitb6416b7.fc22.x86_64` from Fedora 22's repo. However, starting it with `sudo systemctl start docker` causes errors (since I'm running btrfs). Uncommenting the line `OPTIONS='--selinux-enabled'` from `/etc/sysconfig/docker` solved it though, as already mentioned in this thread.

I just find it strange that it's not possible to even start Docker without first having modified a system config file.

**Comment by rhatdan** [comment]
Well until btrfs grows SELinux support there is not much we can do.

**Comment by cpuguy83** [comment]
@matachi Because if you have se-linux enabled in the config, it's assumed you really want it enabled. It's better to error out if security requirements can't be met than to silently ignore the option.

**Comment by dperson** [comment]
Just for clarity, as I understand @rhatdan, RedHat is no longer working on the docker w/ SELinux and btrfs issue. They are working on SELinux w/ Overlay on ext4 / xfs.

Is *anyone* working on the btrfs SELinux issue at this point? Thanks.

**Comment by rhatdan** [comment]
I don't know.  Red Hat to the best of my knowledge is only concentrating on OverlayFS.  BTRFS from a container point of view, does not give the Memory sharing the OverlayFS does.  And from what I have heard from kernel engineers BTRFS has not been proven to be "Enterprise Quality".  Whether or not OverlayFS proves to be, I am not sure.   

I wish they would solve the memory sharing problems in devicemapper/thin-pool, but I have been told that this is also difficult.

**Comment by Djelibeybi** [comment]
We believe that this should be fixed upstream from 3.18 with the following commit to btrfs: http://marc.info/?l=git-commits-head&m=141302939209611&w=2

I'm going to build a test machine that has internal mainline kernel builds to see if this does resolve the issue.

**Comment by Djelibeybi** [comment]
FYI, Facebook and Oracle are still working generally on btrfs and SElinux. I've sent this and all the other btrfs-related bugs to our mainline btrfs development team for review as well.

**Comment by Djelibeybi** [comment]
Seems to be working now:

```
# uname -r
4.1.5-9.el7uek.x86_64

# getenforce 
Enforcing

]# docker version
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   3111aa7-dirty
 Built:        Tue Sep  1 22:23:54 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   3111aa7-dirty
 Built:        Tue Sep  1 22:23:54 UTC 2015
 OS/Arch:      linux/amd64

# docker info
Containers: 1
Images: 52
Storage Driver: btrfs
 Build Version: Btrfs v3.16.2
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.5-9.el7uek.x86_64
Operating System: Oracle Linux Server 7.1
CPUs: 4
Total Memory: 3.591 GiB
Name: dockerx.lot209.com
ID: GT53:Q5UT:5FFA:N5QV:FXWV:ZDUG:H2YX:5476:BBKO:45OZ:SCLM:OWU5

# docker run fedora echo "hello world"
hello world
```

**Comment by stephensmalley** [comment]
Can it write to the container filesystem?
What does 'docker run fedora grep context /proc/self/mounts' show?

**Comment by Djelibeybi** [comment]
1. Yes, it can:

```
$ docker run fedora echo "Hello World" >> test && cat test
Hello World
```

2. It shows nothing, i.e.no result. The entire content of /proc/self/mounts is:

```
$ docker run fedora cat /proc/self/mounts
/dev/sdb1 / btrfs rw,seclabel,relatime,space_cache 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev tmpfs rw,seclabel,nosuid,mode=755 0 0
devpts /dev/pts devpts rw,seclabel,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666 0 0
shm /dev/shm tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,size=65536k 0 0
mqueue /dev/mqueue mqueue rw,seclabel,nosuid,nodev,noexec,relatime 0 0
sysfs /sys sysfs ro,seclabel,nosuid,nodev,noexec,relatime 0 0
tmpfs /sys/fs/cgroup tmpfs ro,seclabel,nosuid,nodev,noexec,relatime,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup ro,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
cgroup /sys/fs/cgroup/cpuset cgroup ro,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup ro,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/blkio cgroup ro,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/memory cgroup ro,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/devices cgroup ro,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/freezer cgroup ro,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup ro,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/perf_event cgroup ro,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup ro,nosuid,nodev,noexec,relatime,hugetlb 0 0
/dev/sdb1 /etc/resolv.conf btrfs rw,seclabel,relatime,space_cache 0 0
/dev/sdb1 /etc/hostname btrfs rw,seclabel,relatime,space_cache 0 0
/dev/sdb1 /etc/hosts btrfs rw,seclabel,relatime,space_cache 0 0
proc /proc/asound proc ro,nosuid,nodev,noexec,relatime 0 0
proc /proc/bus proc ro,nosuid,nodev,noexec,relatime 0 0
proc /proc/fs proc ro,nosuid,nodev,noexec,relatime 0 0
proc /proc/irq proc ro,nosuid,nodev,noexec,relatime 0 0
proc /proc/sys proc ro,nosuid,nodev,noexec,relatime 0 0
proc /proc/sysrq-trigger proc ro,nosuid,nodev,noexec,relatime 0 0
tmpfs /proc/kcore tmpfs rw,seclabel,nosuid,mode=755 0 0
tmpfs /proc/timer_stats tmpfs rw,seclabel,nosuid,mode=755 0 0
```

**Comment by rhatdan** [comment]
Are you sure SELinux is enabled within the container?  IE --selinux-enabled on your docker daemon

```
docker run fedora ls -lZ /
docker run fedora cat /proc/self/attr/current
```

**Comment by Djelibeybi** [comment]
D'oh! I totally forgot that the latest docker-engine no longer reads `/etc/sysconfig/docker` on OL7. My bad. 

Ok, so with `--selinux-enabled` the container still runs, I just get SElinux exceptions:

```
$ docker run fedora ls -lZ /
ls: cannot open directory /: Permission denied
```

Which suggests to me that Docker is starting and running on btrfs with SElinux, now it's just a policy issue.

The second command:

```
$ docker run fedora cat /proc/self/attr/current
system_u:system_r:svirt_lxc_net_t:s0:c56,c894
```

**Comment by Djelibeybi** [comment]
If I run `restorecon` on `/var/lib/docker` then things start to work again:

```
# docker run --rm -t -i fedora ls -lZ /
total 16
lrwxrwxrwx.   1 root root system_u:object_r:docker_var_lib_t:s0                  7 Aug 16  2014 bin -> usr/bin
dr-xr-xr-x.   1 root root system_u:object_r:docker_var_lib_t:s0                  0 Aug 16  2014 boot
drwxr-xr-x.   5 root root system_u:object_r:svirt_sandbox_file_t:s0:c406,c977  380 Sep  3 21:00 dev
drwxr-xr-x.   1 root root system_u:object_r:docker_var_lib_t:s0               1856 Sep  3 21:00 etc
drwxr-xr-x.   1 root root system_u:object_r:docker_var_lib_t:s0                  0 May 21 23:59 home
lrwxrwxrwx.   1 root root system_u:object_r:docker_var_lib_t:s0                  7 Aug 16  2014 lib -> usr/lib
lrwxrwxrwx.   1 root root system_u:object_r:docker_var_lib_t:s0                  9 Aug 16  2014 lib64 -> usr/lib64
drwx------.   1 root root system_u:object_r:docker_var_lib_t:s0                  0 May 21 23:58 lost+found
drwxr-xr-x.   1 root root system_u:object_r:docker_var_lib_t:s0                  0 Aug 16  2014 media
drwxr-xr-x.   1 root root system_u:object_r:docker_var_lib_t:s0                  0 Aug 16  2014 mnt
drwxr-xr-x.   1 root root system_u:object_r:docker_var_lib_t:s0                  0 Aug 16  2014 opt
dr-xr-xr-x. 269 root root system_u:object_r:proc_t:s0                            0 Sep  3 21:00 proc
dr-xr-x---.   1 root root system_u:object_r:docker_var_lib_t:s0                120 May 21 23:59 root
drwxr-xr-x.   1 root root system_u:object_r:docker_var_lib_t:s0                  0 May 21 23:58 run
lrwxrwxrwx.   1 root root system_u:object_r:docker_var_lib_t:s0                  8 Aug 16  2014 sbin -> usr/sbin
drwxr-xr-x.   1 root root system_u:object_r:docker_var_lib_t:s0                  0 Aug 16  2014 srv
dr-xr-xr-x.  13 root root system_u:object_r:sysfs_t:s0                           0 Sep  3 20:52 sys
drwxrwxrwt.   1 root root system_u:object_r:docker_var_lib_t:s0                160 May 21 23:59 tmp
drwxr-xr-x.   1 root root system_u:object_r:docker_var_lib_t:s0                100 May 21 23:58 usr
drwxr-xr-x.   1 root root system_u:object_r:docker_var_lib_t:s0                160 May 21 23:58 var
```

**Comment by Djelibeybi** [comment]
Though, I'm still getting `Permission Denied` errors trying to create files, so something's not working with labelling of the filesystem. So, progress?

**Comment by rhatdan** [comment]
This means that the fix did not fix the fundamental problem with BTRFS.  We need a mechanism to change the SELinux labels on all content based on the mount command.  With devicemapper we can do this since they are full mounts.

mount -o context="system_u:object_r:svirt_sandbox_file_t:s0:c1,c2"

Causes the kernel to treat all inodes within the mount point with this label.  In order for us to get BTRFS to work with SELinux in a docker image, we need this support.

**Comment by Djelibeybi** [comment]
Well, it solved the OP by allowing Docker to start on a machine with SElinux enabled and with `--selinux-enabled` for the Docker daemon. Now we have to fix the other problem by getting Docker to add the SElinux context to btrfs-based subvolume mounts.

That's assuming that the Docker btrfs-based graph driver actually does a subvolume mount for containers like the devicemapper driver does.

**Comment by Djelibeybi** [comment]
Note that my test system is now showing exactly the same problem as the OP, so I retract my previous statements. I have to do further research, obviously.

**Comment by Djelibeybi** [comment]
Disregard the previous retraction. I had broken my VM in other ways. My Docker is now starting and running fine with SElinux enabled and btrfs, and can even start containers. It will then throw SElinux errors when trying to perform certain actions, I assume because there is no context sent to the subvolume mount.

**Comment by rhatdan** [comment]
Correct, so the underlying problem is we have to get  a way to label subvolumes differently based on mount -i context commands, or we have to solve the problem differently.  We are investigating different ways of solving this for OverlayFS, where we label the upper writable content differently then the lower level, but we don't have this working either.  :^(

**Comment by dperson** [comment]
@rhatdan If OverlayFS isn't working with docker + SELinux, is the only way to run them together on top of devicemapper/thinp? I'd like to have SELinux enforcement around Docker. Thanks.

**Comment by rhatdan** [comment]
Yes currently the only solution is devicemapper/thinp.  We have a patch to support SELinux and BTRFS 

https://github.com/docker/docker/pull/16452

We are real close to getting overlayfs with SELinux support(Although we have been real close for months) :^(

**Comment by kk580kk** [comment]
I was got a problem like this 
```
➜  ~  kubectl logs wordpress-controller-jvnij   
warning: both WORDPRESS_DB_HOST and MYSQL_PORT_3306_TCP found
  Connecting to WORDPRESS_DB_HOST (10.254.18.220)
  instead of the linked mysql container
sed: couldn't open temporary file ./sedFEDbAR: Permission denied
```
and fixed by 
remove ```--selinux-enabled```

**Comment by rhatdan** [comment]
Are you using the new version of docker with btrfs/SELinux support (Docker-1.10?)  Otherwise this is expected, although the daemon should have blocked you from executing the command?

If you are using docker-1.10, please attach the output of 

ausearch -m avc -ts recent

After the failure.

**Comment by cmurf** [comment]
Still a problem in kernel-4.4.0-0.rc3.git0.1.fc24.x86_64

Given a Btrfs volume with subvolumes A, B, C in the top level, and A and B are mounted with -o subvol=A[B] (i.e. the top level itself is not mounted), when I try to mount subvolume C using -o subvol=C,context"system_u:object_r:svirt_sandbox_file_t:s0:c1,c2" I get:

[13301.295040] SELinux: mount invalid.  Same superblock, different security settings for (dev sda7, type btrfs)

So that's the gist of the problem, is even though I'm asking for a separate fs tree and a mount time context for it, it fails because apparently a given superblock can only have one context. Where with dmthinp, a snapshot of a volume results in a completely independent filesystem copy with its own superblock.

A possible work around (untested) is to make a snapshot of the desired subvolume, and recursively relabel its contents, rather than depending on mount -o context=. Not exactly ideal of course.

$ mount /dev/sda7 /mnt
$ btrfs sub snap root root2
$ chcon -Rv "system_u:object_r:svirt_sandbox_file_t:s0:c1,c2" root2

And now root2 can be mounted whereever and it'll have the desired labeling. On an SSD this took about 9 seconds with -v, and 6 seconds without.

**Comment by rhatdan** [comment]
We have patches to do exactly this in docker now.  It would be nice to fix the kernel though so we did not need to do the chcon -r change.

**Comment by cmurf** [comment]
Mounting with -o subvol= is just a bind mount behind the scenes. I'd expect -B -o context= to fail on XFS or ext4 with a similar message, for the same reason. But with overlayfs usage, maybe there's an advantage to fixing this problem for all filesystems.

**Comment by liubogithub** [comment]
@cmurf I followed your above chcon steps, but I found that even if I use chcon -Rv to change snapshot directory's selinux value, mount -osubvol=xx,context="system_u:object_r:svirt_sandbox_file_t:s0:c1,c2" doesn't work.
I noticed that you're using context"system_u:object_r:svirt_sandbox_file_t:s0:c1,c2", which is without a '=', is it a typo?

**Comment by cmurf** [comment]
When using chcon -R on a snapshot, I don't use mount -o context at all. The = applies to the context mount option, it doesn't apply to chcon.

**Comment by liubogithub** [comment]
@cmurf I see, so the steps would be only
$ chcon -R snapshot
$ mount -osubvol=snapshot /dev /mnt

correct?

**Comment by cmurf** [comment]
Yes, except that chcon command needs a context specified in quotes. I used "system_u:object_r:svirt_sandbox_file_t:s0:c1,c2" only because I found it in some other example. I don't know if it's always c1,c2, I'm willing to bet that one of those values has to be unique in order for contexts to actually separately protect containers. If two containers have the same context, it'll probably still work but then there's a security hole I'd think.

**Comment by rhatdan** [comment]
Correct.  If you want BTRFS to work without the latest relabel patch, which I think is in docker-1.10.  Then you would need to change the labels to "system_u:object_r:svirt_sandbox_file_t:s0",  this is a label all containers can read and write, which means if a container broke out it would be allowed to attack the file systems of other running containers.

If you are running docker-1.10, BTRFS should just work with SELinux, although you will pay a startup penalty when you create a new container, usually 1-2 seconds.  While docker relabels the content in an image.

**Comment by liubogithub** [comment]
@rhatdan Do I need to install docker-selinux to enable this?
Right now, I'm using my own compile docker binary from the latest docker github repo, the version is 1.10.1.
I used 'getenforce' to make sure selinux is enabled, and ran 'docker daemon --selinux-enabled',
however after 'docker run -it ubuntu bash',  I 'secon --file' to check /var/lib/docker/btrfs/subvolumes/, 
got these,
user: system_u
role: object_r
type: var_lib_t
sensitivity: s0
clearance: s0
mls-range: s0

this doesn't look like it's been relabel..  Am I missing something?

**Comment by rhatdan** [comment]
I am pretty sure the policy for ubuntu is out of date.  You need the latest virt.* policy and you need docker-selinux installed.

I think you also need the lxc_contexts file installed in the contexts directory.

On Fedora/RHEL/Centos this is in /etc/selinux/targeted/contexts/lxc_contexts

```
 python -c "import selinux; print(selinux.selinux_lxc_contexts_path())" 
/etc/selinux/targeted/contexts/lxc_contexts
```
```
# cat /etc/selinux/targeted/contexts/lxc_contexts 
process = "system_u:system_r:svirt_lxc_net_t:s0"
content = "system_u:object_r:virt_var_lib_t:s0"
file = "system_u:object_r:svirt_sandbox_file_t:s0"
sandbox_kvm_process = "system_u:system_r:svirt_qemu_net_t:s0"
sandbox_kvm_process = "system_u:system_r:svirt_qemu_net_t:s0"
sandbox_lxc_process = "system_u:system_r:svirt_lxc_net_t:s0"
```

**Comment by liubogithub** [comment]
@rhatdan
I added mount label support for btrfs subvolumes and removed the label.relabel() part in d.Create(), now with '--selinux-enabled', by checking manually while running a container, I can see files inside the container has the security label like 

`[root@localhost ~]# ls -lZ /var/lib/docker/btrfs/mnt/5824ea0015a9695954c3d67888caf1b4e59f1504b9b6e6064470be8285dd07fa/lib/x86_64-linux-gnu/\*selinux\*

-rw-r--r--. 1 root root system_u:object_r:svirt_sandbox_file_t:s0:c568,c1009 134296 Apr 29  2014 /var/lib/docker/btrfs/mnt/5824ea0015a9695954c3d67888caf1b4e59f1504b9b6e6064470be8285dd07fa/lib/x86_64-linux-gnu/libselinux.so.1
`
However, I got the error,

`ls: error while loading shared libraries: libselinux.so.1: cannot open shared object file: No such file or directory`

It looks like a security issue because if I use --privileged or run without '--selinux-enabled', ls can find all the shared libraries it needs, but I don't see why it can have such an error, do you have any ideas?

**Comment by justincormack** [comment]
I think this was fixed in 1.10 by #16452, and anyone who is still having issues after that should open a new issue. The fix is not perfect, as there is a startup cost, but it works and any other fix would need to be upstream in Linux.
