### ISSUE TITLE
Memory usage in container is 2 orders of magnitude higher for slapd.

### ISSUE THREAD

**Issue by xcJeroen** [docker/docker#8231]
When running slapd in a docker container the memory usages increases with 700M (give or take, seen in htop). When the same installation is run on a vm it will only consume around 2M. Is there a way to find out what is causing this huge difference in memory consumption?

Even if the memory reported is not entirely accurate, I cannot run two containers with slapd on a vm that has 1G of ram. The second container just stops and errors out because it can not allocate the required memory.

```sh
$ sudo docker run -d ldap
a41c2fd...
$ sudo docker run -it --rm ldap slapd -d 4; echo $?
...
54243799 ch_calloc of 1048576 elems of 704 bytes failed
slapd: ch_malloc.c:107: ch_calloc: Assertion `0' failed.
255
```

Running just the container `sudo docker run -it --rm ldap /bin/bash` uses barely any memory (as expected). Someone else seemed to have a similar issue (#6861), but I'm not sure.

To reproduce, dockerfile and install script for archlinux: https://gist.github.com/xcJeroen/3e2b2f2eebdfcb85cef0

In case it's important the host os for the docker container is an archlinux as well.

```sh
$ uname -a
Linux sarchy 3.16.3-1-ARCH #1 SMP PREEMPT Wed Sep 17 21:54:13 CEST 2014 x86_64 GNU/Linux
```

I also tried to run a couple of other openldap containers that I could find on the docker registry, and they all seem to have the same problem.

**Comment by jfrazelle** [comment]
looks like this was resolved, ping me here if otherwise

**Comment by aidanhs** [comment]
Not fixed, but is superseded by #4717 - `open files                      (-n) 524288`.

**Comment by chrisguidry** [comment]
:+1:  Same resolution here.

I experienced the same issue with my own slapd container (memory usage in the 500+ MB range), and resolved it by changing my Dockerfile to `CMD ulimit -n 1024 && slapd -d1`.  Now the slapd container is at around 25MB.

This is on the hypriot/wheezy Raspberry Pi image with Docker 1.6.0.
