### ISSUE TITLE
Update AppArmor policy based on LXC/Ubuntu policy

### ISSUE THREAD

**Issue by jdstrand** [docker/docker#8454]
In Ubuntu we've applied the following patch against 1.2:
  * debian/patches/sync-apparmor-with-lxc.patch: update AppArmor policy to
    by in sync with LXC. Specifically this:
    - reorganizes the rules to allow for easier comparison with other
      container policy
    - adds comments for many rules
    - adds bare dbus rule
    - adds ptrace rule to allow ptracing ourselves
    - adds deny mount options=(ro, remount, silent) -> /
    - allows hugetlbfs
    - adds cgmanager mount
    - adds /sys/fs/pstore mount
    - more specific /sys/kernel/security mount options
    - more specific /sys mount options
    - more specific /proc/sys/kernel/* deny rules
    - more specific /proc/sys/net deny rules
    - more specific /sys/class deny rules
    - more specific /sys/devices deny rules
    - more specific /sys/fs deny rules

Now, Ubuntu has dbus, signal, ptrace and unix mediation whereas Debian and other distributions may not (this is is part of the upcoming AppArmor 2.9 and the corresponding kernel upstreaming is being worked on now). I imagine you would want to make the dbus, signal, ptrace and unix rules conditional on if `apparmor_parser --version` is >= 2.9 (this is the approach libvirt is taking).

Thanks for considering the patch.

**Comment by jfrazelle** [comment]
closing looks like this was resolved but lmk if otherwise

**Comment by rikwasmus** [comment]
Afaik, this still isn't resolved (Ubuntu 14.04.1 LTS, lxc-docker-1.5.0 from https://get.docker.io/ubuntu)

**Comment by jfrazelle** [comment]
there were problems where it wasn't safe everywhere see https://github.com/docker/libcontainer/pull/256#issuecomment-62223013
