### ISSUE TITLE
Docker bind mount is made on old partition instead of new mounted on the host after docker daemon started

### ISSUE THREAD

**Issue by grossws** [docker/docker#9801]
There was a partition `/opt` on my docker host. I've created and mounted new partition (at path `/opt/ssd`) without stopping/restarting docker.

After that I create container with bind mount: `docker run -v /opt/ssd/test:/data busybox:latest /bin/sh -c "echo test > /data/f"`. 

Result:
- it doesn't create `/opt/ssd/test/f` (and directory `/opt/ssd/test`) on partition mounted to `/opt/ssd`,
- it does create `/opt/ssd/test/f` (and directory `/opt/ssd/test`) on partition mounted to `/opt`.

Env:
```
# cat /etc/centos-release 
CentOS Linux release 7.0.1406 (Core)

# uname -a
Linux localhost 3.10.0-123.9.3.el7.x86_64 #1 SMP Thu Dec 18 20:10:00 MSK 2014 x86_64 x86_64 x86_64 GNU/Linux

# docker version 
Client version: 1.3.2
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 39fa2fa/1.3.2
OS/Arch (client): linux/amd64
Server version: 1.3.2
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): 39fa2fa/1.3.2

# docker -D info
[root@ac-srv-002 opt]# docker -D info
Containers: 11
Images: 200
Storage Driver: btrfs
Execution Driver: native-0.2
Kernel Version: 3.10.0-123.9.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
Debug mode (server): false
Debug mode (client): true
Fds: 53
Goroutines: 65
EventsListeners: 0
Init SHA1: c906504aa058139c1d0569ecd0aa5f462a73440f
Init Path: /usr/libexec/docker/dockerinit
```

**Comment by crosbymichael** [comment]
@grossws 

Could you give us a small reproducible case, shell script would be awesome.  I just want to see the mount options that you are using, SHARED, PRIVATE, REC, etc...

**Comment by grossws** [comment]
@crosbymichael, I'll try to reproduce this in vagrant, on the same centos version in several days, ok?

**Comment by crosbymichael** [comment]
@grossws perfect.  Thanks.  

I tried to reproduce but could not on my machine.  I tr

**Comment by gsaulmon** [comment]
I believe I ran into this issue on a fresh `Fedora 21 Server` install with a remote mount.

Here is a small script that reproduces the problem:
```
#!/bin/bash

mkdir /tmp/a
mkdir /tmp/b
touch /tmp/b/foo
mount --bind /tmp/b /tmp/a
docker run -v /tmp/a:/opt/data:rw busybox ls /opt/data
```
On the initial run there is no output from the `ls` command. However, if you restart docker after the `mount` operation the `ls` command properly shows `foo`

**Comment by grossws** [comment]
@gsaulmon, your script reproduces similar issue. It also present on centos 7 with bind mount.

Sorry for delay with checking this in vagrant.

**Comment by grossws** [comment]
To reproduce is isolated env:

```bash
# vagrant should been preinstalled
vagrant init chef/centos-7.0
vagrant up
vagrant ssh

# in vagrant
sudo -i
yum -y install docker
systemctl enable docker
systemctl start docker
docker pull busybox:latest
reboot

# vagrant ssh again, as soon as rebooted
sudo -i
mkdir /tmp/a
mkdir /tmp/b
touch /tmp/b/foo
mount --bind /tmp/b /tmp/a

# this shows nothing but after docker restart shows "foo", as @gsaulmon said
docker run -v /tmp/a:/d busybox ls /d
```

To reproduce my case:
```bash
# in same virtual machine
mkdir /opt/s
dd id=/dev/zero of=/opt/d bs=128M count=128
mkfs.ext4 /opt/d # say "y" to proceed
mount -o loop /opt/d /opt/s

docker run --rm -v /opt/s/test:/data busybox /bin/sh -c "echo test > /data/f"
# will show file before docker restart
docker run --rm -v /opt/s/test:/data busybox /bin/sh -c "ls /data/f"
# doesn't show bind-mounted volume since it was created not on mounted /opt/s but on underlying partition.
ls /opt/s

# check that it's on underlying part
umount /opt/s
ls /opt/s/test
```

**Comment by crosbymichael** [comment]
Thanks for the repo cases.  I'll take a look.

**Comment by jfrazelle** [comment]
closing as fixed by #10147

**Comment by bsod90** [comment]
It seems that this bug is still present in 1.12.6 on Amazon Linux (kernel 4.4.41-36.55.amzn1.x86_64).
1.12 is still default docker version there.

```[ec2-user@ip-10-83-79-138 ~]$ mkdir testdir
[ec2-user@ip-10-83-79-138 ~]$ cd testdir/
[ec2-user@ip-10-83-79-138 testdir]$ touch file_1
[ec2-user@ip-10-83-79-138 testdir]$ cd ..
[ec2-user@ip-10-83-79-138 ~]$ sudo mount /dev/xvdf testdir/
[ec2-user@ip-10-83-79-138 ~]$ cd testdir/
[ec2-user@ip-10-83-79-138 testdir]$ touch file_2
[ec2-user@ip-10-83-79-138 testdir]$ cd ..
[ec2-user@ip-10-83-79-138 ~]$ docker run --rm -it -v /home/ec2-user/testdir/:/mountpoint ubuntu /bin/bash
Digest: sha256:dd7808d8792c9841d0b460122f1acf0a2dd1f56404f8d1e56298048885e45535
Status: Downloaded newer image for ubuntu:latest
root@e395a98e1232:/# cd /mountpoint/
root@e395a98e1232:/mountpoint# ls
file_1
root@e395a98e1232:/mountpoint#
```

And if I do `sudo service docker restart` and then run the same container with the same mount, I'm able to see `file_2` in `mountpoint`, as expected.

**Comment by cpuguy83** [comment]
@bsod90 not the same thing.
How are you starting Docker, init.d?
Does this have an "unshare -m" call in it?

**Comment by bsod90** [comment]
Hmm.. from the description is looked the same, sorry.
Amazon Linux is init.d based and yes, there's an `unshare -m` call in init script for docker.
@cpuguy83

**Comment by cpuguy83** [comment]
@bsod90 That's the problem, you'll either need to remove `unshare -m` or after calling `unshare -m` and before starting `dockerd` run `mount --make-rslave /` (or whatever subdir you might be adding mounts to).

**Comment by bsod90** [comment]
I see
Thank you!
