### ISSUE TITLE
the ip of docker container shoud not be 172.17.42.1/16.

### ISSUE THREAD

**Issue by cc272309126** [docker/docker#9938]
Hi
we use docker to run a large number of short task.  after the task finished. we exit and remove the docker container. this will product  a large number of docker container. and for a long time, some one container will get the ip 172.17.42.1/16. this is default ip of docker0 bridge. and once the container get the ip 172.17.42.1/16. the other container will not connect the outer net, and lead to that a large number of short task blocked. So I think the container ip can not be 172.17.42.1/16 anyway

**Comment by LK4D4** [comment]
@cc272309126 Wow, this shouldn't be like this :) What version do you use?

**Comment by cc272309126** [comment]
@LK4D4  docker version as below
Client version: 1.3.1
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): c78088f/1.3.1
OS/Arch (client): linux/amd64
Server version: 1.3.1
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): c78088f/1.3.1

**Comment by LK4D4** [comment]
@cc272309126 This possibly was fixed later. I'm 100% sure, that there was PR about this. Can you try with 1.4.1?

**Comment by cc272309126** [comment]
@LK4D4 I test it on docker 1.4.1. it doesn’t fix. reproduce steps
1. start daemon with docker -d -D --bip 172.17.42.5/24
2. docker run 4 times.
3. check the ip of container. it will be 172.17.42.5

back to this issue.
if the bridge ip is 172.17.42.1/16. then the first container ip is 172.17.0.1. the last ip if  172.17.255.254.
and the 172.17.42.1 is between the first ip and last ip. so there must be a container that will get the ip 172.17.42.1. which will lead that container can not connect the outer net.

I have submit a patch, it is here. https://github.com/docker/docker/pull/9949/ 
but seems failed. i will look at it  tomorrow.

**Comment by LK4D4** [comment]
@cc272309126 Sorry, I got idea.

**Comment by MalteJ** [comment]
The bridge IP is not registered in the IP allocator. That's why at some point the ipallocator assigns the bridge IP to a container if the BridgeIP is not the first IP of the allocated subnet.
The standard subnet is 172.17.0.0/16. The IP allocator drops the first two and the last IPs: 172.17.0.0, 172.17.0.1 and 172.17.255.255. All other IPs in the subnet will be assigned to containers.
Hence this bug appears with our current default settings, where the bridge ip 172.17.41.1 is in the middle of the subnet 172.17.0.0/16.
The 10494th container (253 + 40*256 + 1) will get the bridge IP assigned.
