### ISSUE TITLE
Unable to mount devices under container

### ISSUE THREAD

**Issue by tbronchain** [docker/docker#9950]
Hi guys,

I'm trying to mount a device directly bind using the "devices" parameter into the container.
This device is an AWS typical virtual drive. It can mount on the host without any problem.

It seems like there is no problem to run `mkfs.ext3` on my mounted device, but `mount -t ext3 /dev/xvdf /mnt` fails with the following error:

    root@eg_sshd:~# mount -t ext3 /dev/xvdf /mnt
    mount: block device /dev/xvdf is write-protected, mounting read-only
    mount: cannot mount block device /dev/xvdf read-only
    root@eg_sshd:~# mount -t ext3 -o rw /dev/xvdf /mnt
    mount: block device /dev/xvdf is write-protected, mounting read-only
    mount: cannot mount block device /dev/xvdf read-only

The devices seems well recognised if I inspect the container:

        "Devices": [
            {
                "CgroupPermissions": "rwm",
                "PathInContainer": "/dev/xvdf",
                "PathOnHost": "/dev/xvdf"
            },
            {
                "CgroupPermissions": "rwm",
                "PathInContainer": "/dev/xvdg",
                "PathOnHost": "/dev/xvdg"
            }
        ],

Oh, and I'm using Ubuntu as base (just a very basic container running a sshd server - only for tests!).

Thanks for help!

**Comment by thaJeztah** [comment]
Does this look like what you're trying to do? https://github.com/docker/docker/pull/8826

Also look at this section of the documentation; https://docs.docker.com/reference/run/#runtime-privilege-linux-capabilities-and-lxc-configuration

**Comment by tbronchain** [comment]
Hi Sebastian,

Thanks for your reply, but actually this is not what I'm trying to do.

I followed the documentation. In fact, I'm mounting the volume using the API, not the docker CLI, but it doesn't (shouldn't?) matter much.
As I showed on my original post, the properties are well set.

The problem I have is I'm unable to `mount` a device bind (with the `--devices` option) within a container, although I'm able to alter the partition table.
To me, it seems like a permission bug. Or maybe there is something I didn't get?

Thanks for your help,
Thibault.

**Comment by thaJeztah** [comment]
Hi, Thibault,

I have never needed this functionality myself and don't have experience with it in Docker. I think this may be caused by the needed capabilities not being present in the container (and remember seeing a discussion on this in another issue).

I think the best way to get help on this, is to ask the question on IRC in the #docker channel.

**Comment by tbronchain** [comment]
Thanks, I'll check this out!

**Comment by nacc** [comment]
I'm guessing this was resolved, but it wasn't written into this issue. Thibault, would you mind updating it? A tester here is hitting something similar (I think it's not a very useful testcase, but still) -- and I'd like to provide them with some suggestions on what is missing.

**Comment by tbronchain** [comment]
@nacc It seems it's not resolved. I've upgraded to 1.5.0, but still the same issue. Now I can see it's possible to add specific capacities, so it's maybe what is missing.
The error is different though. Although I have the device correctly set as rwm, I get a "permission denied" in the container, or "Operation not permitted" with fdisk.
But I don't understand why I need to add any specific capacity, while the doc is saying it should work out of the box ...

**Comment by cpuguy83** [comment]
@tbronchain You cannot call `mount` unless you have CAP_SYS_ADMIN, which is not available in the default container config. You'd need to `docker run --cap-add SYS_ADMIN`

**Comment by tbronchain** [comment]
Thanks Brian. Does it means I must use the LXC driver to be able to mount
devices?

**Comment by cpuguy83** [comment]
@tbronchain No, it means you need to use the above `docker run` command to be able to use `mount` in a container.

**Comment by tbronchain** [comment]
And ... It works! Awesome @cpuguy83 , thanks a lot!

**Comment by nagendersoma** [comment]
Am hitting this same issue and the SYS_ADMIN capability is not resolving the same. 

>sudo docker run --cap-add SYS_ADMIN --device=/dev/loop0:/dev/xsdc -i -t ubuntu /bin/bash
> docker inspect cranky_bardeen
..
  "CapAdd": [
            "SYS_ADMIN"
        ]
...
 "Devices": [
            {
                "CgroupPermissions": "rwm",
                "PathInContainer": "/dev/xsdc",
                "PathOnHost": "/dev/loop0"
            }
...

In the container : 
root@ccdf48f761b1:/# mount -t ext4 -o rw /dev/xsdc /mnt/tmp
mount: block device /dev/xsdc is write-protected, mounting read-only
mount: cannot mount block device /dev/xsdc read-only
root@ccdf48f761b1:/#

**Comment by bryanpfremmer** [comment]
I am trying to use tmpfs to mount a ramdisk when specifying --cap-add SYS-ADMIN and I also get mount: tmpfs is write-protected, mounting read-only
mount: cannot mount tmpfs read-only

**Comment by SaltwaterC** [comment]
Ran into the same issue trying to do a bind mount inside a container. CAP_SYS_ADMIN works on my local dev box (OS X 10.10 with Docker Toolbox 1.8.1b) but it fails to work on the CI build agent (Ubuntu 15.04 using the docker-engine package from https://apt.dockerproject.org/repo).

I tried adding the whole cap lot (all 37 of them) to the container. No dice. The only thing that works is to run the container in privileged mode.

**Comment by drngsl** [comment]
@cpuguy83 ,hi, I also meet this problem, but when I create a container with docker run --cap-add SYS_ADMIN, it does still not work.

**Comment by thaJeztah** [comment]
@drngsl also see this issue; https://github.com/docker/docker/issues/16429 perhaps that's what you're running into?

**Comment by drngsl** [comment]
@thaJeztah , it does work, and thanks for you help.

**Comment by vmahedia** [comment]
Facing the same issue. Nothing mentioned above worked from within the container.

**Comment by thaJeztah** [comment]
Actually, you can (right-click on the comment's timestamp); https://github.com/docker/docker/issues/18191#issuecomment-159280820

**Comment by vmahedia** [comment]
@thaJeztah Thank you, kind sir.

**Comment by fryfrog** [comment]
Just wanted to say thanks for this issue, helped me resolve the same sort of error in a docker image I was working on. :)

**Comment by tamsky** [comment]
It's possible the `--security-opt` or `--privileged` flags are no longer required.

based on the hints in:
https://developers.redhat.com/blog/2016/09/13/running-systemd-in-a-non-privileged-container/

I'm able to run a `systemd`-enabled docker image[1] within `docker/for-mac`[2] using command:
`docker run -d -e=container=docker --stop-signal=SIGRTMIN+3 --tmpfs /tmp --tmpfs /run -v /sys/fs/cgroup:/sys/fs/cgroup:ro <systemd_enabled_CentOS_image_id>`

[1] https://hub.docker.com/_/centos/ with "Dockerfile for systemd base image" applied
[2] https://github.com/docker/for-mac/
